@testset "ecRad cloud scattering tables validation artifact" begin
    root = normpath(joinpath(@__DIR__, ".."))
    script = joinpath(root, "validation", "ecrad_cloud_scattering_tables_check.jl")
    test_project = Base.active_project()
    output = read(`$(Base.julia_cmd()) --project=$test_project $script`, String)

    @test occursin("ecRad Cloud Scattering Tables Check", output)
    @test occursin("Status: **passed**", output)
    @test occursin("liquid", output)
    @test occursin("ice", output)
    @test occursin("ecCKD G-Point Mapping", output)

    json_path = joinpath(root, "validation", "results", "ecrad_cloud_scattering_tables_check.json")
    md_path = joinpath(root, "validation", "results", "ecrad_cloud_scattering_tables_check.md")
    @test isfile(json_path)
    @test isfile(md_path)

    json = read(json_path, String)
    @test occursin("\"case\": \"ecrad_cloud_scattering_tables_check\"", json)
    @test occursin("\"status\": \"passed\"", json)
    @test occursin("\"medium\": \"liquid-water\"", json)
    @test occursin("\"medium\": \"ice\"", json)
    @test occursin("\"shape_ok\": true", json)
    @test occursin("\"bounded\": true", json)
    @test occursin("\"finite\": true", json)
    @test occursin("\"mappings\": [", json)
    @test occursin("\"kind\": \"shortwave\"", json)
    @test occursin("\"kind\": \"longwave\"", json)
    @test occursin("\"expected_gpoints\": 32", json)
    @test occursin("\"expected_gpoints\": 64", json)
    @test occursin("\"positive_extinction\": true", json)
end
