using JSON

@testset "goal audit check artifact" begin
    script = joinpath(@__DIR__, "..", "validation", "goal_audit_check.jl")
    output = read(`$(Base.julia_cmd()) --project=$(Base.active_project()) $script`, String)
    @test occursin("Radiative Heating Goal Audit Check", output)
    @test occursin("Status: **not_complete**", output)
    @test occursin("old ABR Breeze extension removed", output)
    @test occursin("dedicated BreezeRadiativeHeatingExt present", output)
    @test occursin("toy ecCKD Enzyme check", output)
    @test occursin("toy ecCKD Reactant check", output)
    @test occursin("full Reactant/Enzyme RRTMGP-target 16-g calibration", output)
    @test occursin("toy ecCKD training RMSE improvement", output)
    @test occursin("official/reduced ecCKD gas-optics training", output)
    @test occursin("Breeze reduced 32x16 proxy timing", output)
    @test occursin("Breeze reduced 32x16 proxy accuracy", output)
    @test occursin("Breeze GPU environment check", output)
    @test occursin("Breeze H100 acceptance runbook", output)
    @test occursin("Breeze H100 acceptance local preflight", output)
    @test occursin("Breeze RCEMIP H100 4x acceptance", output)
    @test occursin("Breeze RCEMIP Nsight Systems report", output)
    @test occursin("Breeze RCEMIP Nsight Compute report", output)
    @test occursin("Breeze validated ecCKD H100 support preflight", output)
    @test occursin("ecRad all-sky IFS gate", output)
    @test occursin("Prompt-to-Artifact Checklist", output)
    @test occursin("Realistic RCEMIP-style H100 4x RRTMGP comparison with Nsight profiling", output)
    @test occursin("32-g ecCKD/RRTMGP-compatible production gas optics", output)
    @test occursin("Dedicated Breeze Checkout", output)
    @test occursin("Fresh-clone SHA matches", output)

    json_path = joinpath(@__DIR__, "..", "validation", "results", "goal_audit_check.json")
    md_path = joinpath(@__DIR__, "..", "validation", "results", "goal_audit_check.md")
    @test isfile(json_path)
    @test isfile(md_path)

    json = read(json_path, String)
    parsed = JSON.parsefile(json_path)
    @test occursin("\"case\": \"radiative_heating_goal_audit_check\"", json)
    @test occursin("\"status\": \"not_complete\"", json)
    @test occursin("\"completion_blocker_count\":", json)
    @test occursin("\"completion_blocker_active\":", json)
    @test occursin("\"goal_steps\":", json)
    @test occursin("\"prompt_artifact_checklist\":", json)
    @test occursin("\"requirement\": \"Hard cloudless/no-aerosol official ecCKD accuracy thresholds\"", json)
    @test occursin("\"requirement\": \"32-g ecCKD/RRTMGP-compatible production gas optics\"", json)
    @test occursin("\"requirement\": \"Current IFS all-sky cloud/aerosol/scattering/overlap semantics\"", json)
    @test occursin("\"requirement\": \"Validated ecCKD Breeze CPU and H100 support path\"", json)
    @test occursin("\"requirement\": \"Realistic RCEMIP-style H100 4x RRTMGP comparison with Nsight profiling\"", json)
    @test occursin("\"status\": \"satisfied\"", json)
    @test occursin("\"name\": \"cloudless official ecCKD ecRad accuracy\"", json)
    @test occursin("\"status\": \"passed\"", json)
    @test occursin("\"name\": \"32-g ecCKD/RRTMGP-compatible gas optics\"", json)
    @test occursin("\"status\": \"passed_32g_target\"", json)
    @test occursin("\"name\": \"all-sky IFS conventions plus Breeze H100 4x\"", json)
    @test occursin("\"status\": \"passed\"", json)
    @test occursin("\"expected_present\": false", json)
    @test occursin("\"presence_matches\": true", json)
    @test occursin("\"required_text\": \"\\\"final_4x_claim_supported\\\": true\"", json)
    @test occursin("\"forbidden_text_found\": false", json)
    @test occursin("\"head_sha_matches_fresh_clone\":", json)
    @test occursin("\"origin_remote_matches\": true", json)
    @test occursin("\"name\": \"toy ecCKD Enzyme check\"", json)
    @test occursin("\"name\": \"toy ecCKD Reactant check\"", json)
    @test occursin("\"name\": \"full Reactant/Enzyme RRTMGP-target 16-g calibration\"", json)
    @test occursin("gradient-descent calibration of the 16-g model against the RRTMGP", json)
    @test occursin("\"name\": \"toy ecCKD training RMSE improvement\"", json)
    @test occursin("\"name\": \"ecRad all-sky IFS gate\"", json)
    @test occursin("\"name\": \"official/reduced ecCKD gas-optics training\"", json)
    @test occursin("production official/reduced ecCKD training improves the objective but has not quantitatively recovered a published model", json)
    @test occursin("\"flux_rmse_ratio\":", json)
    @test occursin("\"heating_rate_rmse_ratio\":", json)
    @test occursin("\"name\": \"Breeze reduced 32x16 proxy timing\"", json)
    @test occursin("\"name\": \"Breeze reduced 32x16 proxy accuracy\"", json)
    @test occursin("\"name\": \"Breeze H100 acceptance runbook\"", json)
    @test occursin("\"name\": \"Breeze H100 acceptance local preflight\"", json)
    @test occursin("\"name\": \"Breeze RCEMIP H100 4x acceptance\"", json)
    @test occursin("\"name\": \"Breeze RCEMIP Nsight Systems report\"", json)
    @test occursin("\"name\": \"Breeze RCEMIP Nsight Compute report\"", json)
    @test occursin("\"name\": \"Breeze tabulated ecCKD device column amount kernel\"", json)
    @test occursin("\"required_text\": \"tabulated_ecckd_column_amounts!\"", json)
    @test occursin("\"name\": \"Breeze tabulated ecCKD interpolation state kernel\"", json)
    @test occursin("\"required_text\": \"tabulated_ecckd_interpolation_state!\"", json)
    @test occursin("\"name\": \"Breeze tabulated ecCKD absorption optical-depth kernel\"", json)
    @test occursin("\"required_text\": \"tabulated_ecckd_absorption_optical_depths!\"", json)
    @test occursin("\"name\": \"Breeze tabulated ecCKD Rayleigh optical-depth kernel\"", json)
    @test occursin("\"required_text\": \"tabulated_ecckd_rayleigh_optical_depths!\"", json)
    @test occursin("\"name\": \"Breeze tabulated ecCKD longwave source kernel\"", json)
    @test occursin("\"required_text\": \"tabulated_ecckd_longwave_sources!\"", json)
    @test occursin("\"name\": \"Breeze tabulated ecCKD integrated optical-properties kernel\"", json)
    @test occursin("\"required_text\": \"tabulated_ecckd_optical_properties!\"", json)
    @test occursin("\"name\": \"Breeze tabulated ecCKD flux-divergence kernel\"", json)
    @test occursin("\"required_text\": \"tabulated_ecckd_flux_divergence!\"", json)
    @test occursin("\"name\": \"Breeze tabulated ecCKD device workspace\"", json)
    @test occursin("\"required_text\": \"TabulatedEcCKDDeviceWorkspace\"", json)
    @test occursin("\"name\": \"Breeze tabulated ecCKD device update path\"", json)
    @test occursin("\"required_text\": \"update_tabulated_ecckd_radiation_device!\"", json)
    @test occursin("\"name\": \"Breeze validated ecCKD H100 support preflight\"", json)
    @test occursin("\"required_text\": \"\\\"gas_model_device_support_status\\\": \\\"supported\\\"\"", json)
    @test occursin("\"name\": \"Breeze validated ecCKD H100 support source\"", json)
    @test occursin("\"required_text\": \"\\\"gas_model_device_support_source\\\": \\\"BreezeRadiativeHeatingExt\\\"\"", json)
    @test occursin("\"name\": \"Breeze validated ecCKD H100 next implementation\"", json)
    @test occursin("\"required_text\": \"\\\"next_required_implementation\\\": \\\"none\\\"\"", json)
    @test occursin("\"name\": \"Breeze validated ecCKD H100 missing kernel checklist\"", json)
    @test occursin("\"name\": \"Breeze validated ecCKD H100 parity requirement\"", json)
    @test occursin("CPU/GPU parity evidence", json)
    @test occursin("\"name\": \"Breeze reduced Pareto scaffold\"", json)
    @test occursin("\"name\": \"Breeze reduced accuracy scaffold\"", json)
    @test occursin("\"name\": \"official ecCKD 32b baseline\"", json)
    @test occursin("\"name\": \"32-g ecCKD/RRTMGP comparison\"", json)
    @test occursin("\"name\": \"reduced ecCKD acceptance decision\"", json)
    @test occursin("\"name\": \"reduced 16-g diagnostic hard-threshold record\"", json)
    @test occursin("\"name\": \"reduced ecCKD subset search\"", json)
    @test occursin("\"case\\\": \\\"radiative_heating_reduced_subset_search\\\"", json)
    @test occursin("\"name\": \"reduced ecCKD subset search threshold status\"", json)
    @test occursin("\"name\": \"reduced 16-g diagnostic optimization objective record\"", json)
    @test occursin("\"name\": \"reduced ecCKD optimization block scan\"", json)
    @test occursin("\"required_text\": \"\\\"block_trial_scan\\\"\"", json)
    @test occursin("\"name\": \"reduced ecCKD coefficient coordinate scan\"", json)
    @test occursin("\"required_text\": \"\\\"coordinate_coefficient_scan\\\"\"", json)
    @test occursin("\"name\": \"reduced ecCKD topology candidate scan\"", json)
    @test occursin("\"required_text\": \"\\\"topology_candidate_scan\\\"\"", json)
    @test occursin("\"name\": \"reduced ecCKD subset-search topology scan\"", json)
    @test occursin("\"required_text\": \"\\\"subset_search_topology_scan\\\"\"", json)

    steps = Dict(step["name"] => step for step in parsed["goal_steps"])
    @test steps["cloudless official ecCKD ecRad accuracy"]["status"] == "passed"
    @test steps["32-g ecCKD/RRTMGP-compatible gas optics"]["status"] ==
          "passed_32g_target"
    @test steps["all-sky IFS conventions plus Breeze H100 4x"]["status"] == "passed"

    checklist = Dict(item["requirement"] => item for item in parsed["prompt_artifact_checklist"])
    @test checklist["Validated ecCKD Breeze CPU and H100 support path"]["status"] in
          ("satisfied", "uncovered")
    @test checklist["Reactant and Enzyme optimization path"]["status"] == "satisfied"
    @test checklist["End-to-end gas-optics training demonstration"]["status"] == "blocked"
    @test checklist["Realistic RCEMIP-style H100 4x RRTMGP comparison with Nsight profiling"]["status"] ==
          "satisfied"
    @test checklist["32-g ecCKD/RRTMGP-compatible production gas optics"]["status"] ==
          "satisfied"
    evidence = Dict(item["artifact"] => item for item in
                    checklist["32-g ecCKD/RRTMGP-compatible production gas optics"]["evidence"])
    @test evidence["32-g ecCKD/RRTMGP comparison"]["status"] == "verified"
    @test !evidence["32-g ecCKD/RRTMGP comparison"]["completion_blocker_active"]
    @test evidence["reduced 16-g diagnostic hard-threshold record"]["status"] == "verified"
    ad_evidence = Dict(item["artifact"] => item for item in
                       checklist["Reactant and Enzyme optimization path"]["evidence"])
    @test ad_evidence["full Reactant/Enzyme RRTMGP-target 16-g calibration"]["status"] ==
          "verified"
    @test !ad_evidence["full Reactant/Enzyme RRTMGP-target 16-g calibration"]["completion_blocker_active"]
end
