# Gate-4 G2b SW-RGB MINOR-GAS TRAINING-FLUX checkpoint (dry-run generation;
# NO submission). Follow-on to G2a (rel-base, job 4100).
#
# Generates the TEN additional RGB-banded SW LBL training flux files that
# the later SW optimizer passes consume (optimize_lut_sw.sh relative-ch4 and
# relative-n2o passes, plus the present reference): present, ch4-{350,700,
# 1200,2600,3500}, n2o-{190,270,405,540}. All scenario names verified
# supported by run_sw_lbl_evaluation.sh (present = explicit branch;
# ch4-/n2o- = prefix branches). Same rgb band grid, pipeline, and
# safeguards as G2a.
#
# NO optimizer, create_lut, scale_lut, or find_g_points executable lines.

include(joinpath(@__DIR__, "validation_results.jl"))

using Dates
import JSON

const ECCKD_SRC = "/shared/home/greg/.julia/artifacts/" *
    "7b210aef53e908cfe3c709945f0763c37ca82aaa/" *
    "ecckd-6115f9b8e29a55cb0f48916857bdc77fec41badd"
const G4WORK = "/shared/home/greg/ecckd-derived-flux-work/g4-init-generation"
const CKDMIP_ROOT = "/shared/home/greg/data/ckdmip"
const CKDMIP_BIN_ROOT = "/shared/home/greg/build/ckdmip-1.0"
const PROJECT_ROOT = "/shared/home/greg/Projects/AnalyticBandRadiation-platform"
const SCENARIOS = ["present", "ch4-350", "ch4-700", "ch4-1200", "ch4-2600",
                   "ch4-3500", "n2o-190", "n2o-270", "n2o-405", "n2o-540"]

const GB_RESULTS_JSON = validation_results_path("gate4_g2b_sw_rgb_variants_checkpoint.json")
const GB_RESULTS_MD = validation_results_path("gate4_g2b_sw_rgb_variants_checkpoint.md")
const GB_SBATCH = validation_results_path("gate4_g2b_sw_rgb_dryrun.sbatch")

const SBATCH_TEXT = """
#!/bin/bash
#SBATCH --job-name=g4-g2b-sw-rgb-minor
#SBATCH --output=/shared/home/greg/data/ckdmip-logs/g4-g2b-%j.log
#SBATCH --time=16:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=60G
#SBATCH --partition=cpu-large

# Gate-4 G2b: RGB-banded SW LBL training fluxes, minor-gas + present
# scenarios ONLY (no optimizer, no create/scale/find_g_points stages).
# Generated by gate4_g2b_sw_rgb_variants_checkpoint.jl.
set -euo pipefail
if [ -z "\${SLURM_JOB_ID:-}" ]; then
    echo "REFUSED: head-node execution is not permitted; submit via sbatch." >&2
    exit 64
fi

G4WORK=$G4WORK
TESTCOPY="\$G4WORK/testcopy-rgb-g2b"
WORKRGB="\$G4WORK/work-rgb-g2b"
SCEN="$(join(SCENARIOS, " "))"

echo "=== G2b stage 0: preflight ==="
test -x "$CKDMIP_BIN_ROOT/bin/ckdmip_sw" || { echo "MISSING ckdmip_sw" >&2; exit 65; }
test -s "$CKDMIP_ROOT/evaluation1/sw_spectra/ckdmip_ssi.h5" || { echo "MISSING evaluation1 SSI" >&2; exit 65; }
for chunk in 1-10 11-20 21-30 31-40 41-50; do
    for gas in h2o o3 co2 ch4 n2o o2 n2 rayleigh; do
        ls "$CKDMIP_ROOT/evaluation1/sw_spectra/"ckdmip_evaluation1_sw_spectra_\${gas}_*_\${chunk}.h5 >/dev/null 2>&1 || { echo "MISSING evaluation1 SW spectra: \$gas \$chunk" >&2; exit 65; }
    done
done
for scen in \$SCEN; do
    test ! -e "\$WORKRGB/sw_lbl_fluxes/ckdmip_evaluation1_sw_fluxes-rgb_\$scen.h5" || { echo "REFUSED: stale consolidated rgb output \$scen" >&2; exit 70; }
    test ! -e "$CKDMIP_ROOT/evaluation1/sw_fluxes-rgb/ckdmip_evaluation1_sw_fluxes-rgb_\$scen.h5" || { echo "REFUSED: stale installed rgb output \$scen" >&2; exit 70; }
done
# partial-RAW guard (job 4103 was canceled mid-run and left header-size RAW
# chunks): run_sw_lbl_evaluation reuses nonempty RAW files, so the whole
# quarantine work dir is wiped for a clean regeneration. Under Slurm only;
# operates solely on the G2b quarantine tree, never the G2a work-rgb or any
# installed data.
if [ -e "\$WORKRGB" ]; then
    echo "clearing pre-existing G2b quarantine (partial RAW guard): \$WORKRGB"
    find "\$WORKRGB" -name 'RAW_ckdmip_evaluation1_sw_fluxes-rgb_*.h5' -printf '  partial: %p (%s B)\\n' 2>/dev/null || true
    rm -rf "\$WORKRGB"
fi

echo "=== G2b stage 1: isolated testcopy-rgb-g2b from the PINNED artifact ==="
rm -rf "\$TESTCOPY"
cp -r "$ECCKD_SRC/test" "\$TESTCOPY"
cd "\$TESTCOPY"
sed 's/@PACKAGE_VERSION@/1.2/g' version.h.in > version.h
sed -i \\
  -e 's|^CKDMIP_DIR=.*|CKDMIP_DIR=$CKDMIP_BIN_ROOT|' \\
  -e 's|^CKDMIP_DATA_DIR=.*|CKDMIP_DATA_DIR=$CKDMIP_ROOT|' \\
  -e 's|^WORK_DIR=.*|WORK_DIR=$G4WORK/work-rgb-g2b|' \\
  -e 's|^BINDIR=.*|BINDIR=/shared/home/greg/ecckd-derived-flux-work/ecckd/src/ecckd|' \\
  config.h
grep -E "^(CKDMIP_DIR|CKDMIP_DATA_DIR|WORK_DIR|BINDIR)=" config.h
# scenario override: replace the default rel-list with the G2b minor set
sed -i -E "0,/^SCENARIOS=\\"[^\\"]*\\"/s||SCENARIOS=\\"\$SCEN\\"|" run_sw_lbl_evaluation.sh
grep -E "^SCENARIOS=" run_sw_lbl_evaluation.sh
grep -qE "^SCENARIOS=\\"present ch4-350" run_sw_lbl_evaluation.sh || { echo "BAD edit: SCENARIOS" >&2; exit 68; }
# band-structure edits (identical to G2a): fluxes -> fluxes-rgb; 13-band off;
# 9-band 14300-variant on
sed -i \\
  -e 's|^BANDCODE=fluxes\$|BANDCODE=fluxes-rgb|' \\
  -e 's|^band_wavenumber1(1:13)|!band_wavenumber1(1:13)|' \\
  -e 's|^band_wavenumber2(1:13)|!band_wavenumber2(1:13)|' \\
  -e 's|^!band_wavenumber1(1:9) = 250, 2500, 4000, 8000, 14300, 16650, 20000, 25000, 31750,|band_wavenumber1(1:9) = 250, 2500, 4000, 8000, 14300, 16650, 20000, 25000, 31750,|' \\
  -e 's|^!band_wavenumber2(1:9) = 2500, 4000, 8000, 14300, 16650, 20000, 25000, 31750, 50000,|band_wavenumber2(1:9) = 2500, 4000, 8000, 14300, 16650, 20000, 25000, 31750, 50000,|' \\
  run_sw_lbl_evaluation.sh
grep -E "^BANDCODE=|^band_wavenumber" run_sw_lbl_evaluation.sh
grep -qE "^BANDCODE=fluxes-rgb\$" run_sw_lbl_evaluation.sh || { echo "BAD edit: BANDCODE" >&2; exit 68; }
test \$(grep -cE "^band_wavenumber1" run_sw_lbl_evaluation.sh) -eq 1 || { echo "BAD edit: band grid count" >&2; exit 68; }
# pipeline parity with 4078/G2a
sed -i '/^module load nco\$/s/^/# /' run_sw_lbl_evaluation.sh
sed -i 's/iverbose = 3/iverbose = 1/g' run_sw_lbl_evaluation.sh
sed -i -E 's|ncrcat -O \\\$OUTFILES \\\$OUTFILE|julia --project=$PROJECT_ROOT/test $PROJECT_ROOT/validation/concat_ckdmip_flux_chunks.jl \$OUTFILES \$OUTFILE|' run_sw_lbl_evaluation.sh
sed -i '/OUTFILES="\$OUTFILES \$OUTFILE"/a\\
\\tif [ -s "\$OUTFILE" ]\\
\\tthen\\
\\t    echo "*** REUSING \$OUTFILE ***"\\
\\t    continue\\
\\tfi' run_sw_lbl_evaluation.sh

echo "=== G2b stage 2: RGB-banded SW LBL evaluation (10 minor+present) ==="
bash run_sw_lbl_evaluation.sh

echo "=== G2b stage 3: exact-10 completeness gate + install ==="
ALL_OK=1
for scen in \$SCEN; do
    test -s "\$G4WORK/work-rgb-g2b/sw_lbl_fluxes/ckdmip_evaluation1_sw_fluxes-rgb_\$scen.h5" || { echo "MISSING consolidated rgb \$scen" >&2; ALL_OK=0; }
done
[ "\$ALL_OK" = 1 ] || { echo "REFUSED: completeness gate failed; NOT installing partial set" >&2; exit 71; }
mkdir -p "$CKDMIP_ROOT/evaluation1/sw_fluxes-rgb"
for scen in \$SCEN; do
    install -m 0644 "\$G4WORK/work-rgb-g2b/sw_lbl_fluxes/ckdmip_evaluation1_sw_fluxes-rgb_\$scen.h5" "$CKDMIP_ROOT/evaluation1/sw_fluxes-rgb/"
    cmp -s "\$G4WORK/work-rgb-g2b/sw_lbl_fluxes/ckdmip_evaluation1_sw_fluxes-rgb_\$scen.h5" "$CKDMIP_ROOT/evaluation1/sw_fluxes-rgb/ckdmip_evaluation1_sw_fluxes-rgb_\$scen.h5" || { echo "INSTALL IDENTITY MISMATCH \$scen" >&2; exit 72; }
done

echo "=== G2b outputs ==="
for scen in \$SCEN; do
    sha256sum "$CKDMIP_ROOT/evaluation1/sw_fluxes-rgb/ckdmip_evaluation1_sw_fluxes-rgb_\$scen.h5"
done
echo "=== G2b done rc=\$? \$(date -u +%FT%TZ) ==="
"""

# guarded G2a-ledger prerequisite loader (fixture-run on tmp files): a
# missing, unparseable (parse failure), parsed-non-object (JSON null/
# array DISTINGUISHED from parse failure), WRONG-CASE, or wrong-status
# artifact classifies fail-closed with a stable reason -- never an
# uncaught exception, never status-only trust: the exact case is bound
# before the FAITHFUL exact-status comparison.
function classify_g2a_ledger(path)
    isfile(path) ||
        return (false, "g2a data ledger missing: $path", nothing)
    parse_failed = false
    d = try
        JSON.parsefile(path)
    catch
        parse_failed = true
        nothing
    end
    parse_failed && return (false,
        "g2a data ledger unparseable (parse failure)", nothing)
    d isa AbstractDict || return (false,
        "g2a data ledger parses to a non-object " *
        "(JSON null/array/scalar)", nothing)
    c = get(d, "case", "")
    (c isa AbstractString && c == "gate4_g2a_data_ledger") ||
        return (false, "g2a data ledger case mismatch: $(repr(c))",
                nothing)
    s = get(d, "status", "")
    s == "sw_rgb_rel_training_fluxes_installed_and_verified" ||
        return (false, "g2a data ledger not green: $(repr(s))", nothing)
    return (true, "ok", d)
end

# the sbatch WRITE happens only behind the classified prerequisite (the
# committed script is never clobbered by a blocked run); SBATCH_TEXT is
# a load-time constant, so generation itself cannot throw and the text
# gates stay evaluated on both paths -- only the write is gated
function gb_write_script(writefn, prereq_ok)
    prereq_ok || return false
    writefn()
    return true
end

function main()
    fails = String[]
    gates = Dict{String, String}()

    # loader + write-boundary fixtures FIRST, through the SAME code
    tdir = mktempdir()
    lt = Dict{String, Bool}()
    lt["missing_fails"] =
        !classify_g2a_ledger(joinpath(tdir, "absent.json"))[1]
    fpx = joinpath(tdir, "gl.json")
    write(fpx, "{")
    lt["malformed_fails"] = begin
        okx, why = classify_g2a_ledger(fpx)
        !okx && occursin("unparseable", why)
    end
    write(fpx, "null")
    lt["null_non_object_fails"] = begin
        okx, why = classify_g2a_ledger(fpx)
        !okx && occursin("non-object", why)
    end
    write(fpx, "[1]")
    lt["array_non_object_fails"] = begin
        okx, why = classify_g2a_ledger(fpx)
        !okx && occursin("non-object", why)
    end
    write(fpx, "{\"case\": \"other\", \"status\": " *
               "\"sw_rgb_rel_training_fluxes_installed_and_verified\"}")
    lt["wrong_case_fails"] = begin
        okx, why = classify_g2a_ledger(fpx)
        !okx && occursin("case mismatch", why)
    end
    write(fpx, "{\"case\": \"gate4_g2a_data_ledger\", " *
               "\"status\": \"tampered\"}")
    lt["wrong_status_fails"] = begin
        okx, why = classify_g2a_ledger(fpx)
        !okx && occursin("not green", why)
    end
    write(fpx, "{\"case\": \"gate4_g2a_data_ledger\", \"status\": " *
               "\"sw_rgb_rel_training_fluxes_installed_and_verified\"}")
    lt["exact_green_captures"] = begin
        okx, why, dd = classify_g2a_ledger(fpx)
        okx && why == "ok" && dd isa AbstractDict
    end
    lt["blocked_never_invokes_writer"] = begin
        n = Ref(0)
        gb_write_script(() -> (n[] += 1), false) == false && n[] == 0
    end
    lt["ok_invokes_writer_once"] = begin
        n = Ref(0)
        gb_write_script(() -> (n[] += 1), true) == true && n[] == 1
    end
    rm(tdir, recursive = true, force = true)
    gates["prerequisite_loader_fixture_tests"] =
        all(values(lt)) ? "passed" : "failed"
    all(values(lt)) || push!(fails, "prerequisite loader fixture " *
        "failures: " * join(sort([k for (k, v) in lt if !v]), ", "))

    # exact case+status prerequisite binding BEFORE the script write
    g2a_ok, g2a_why, _ = classify_g2a_ledger(
        validation_results_path("gate4_g2a_data_ledger.json"))
    gates["g2a_prerequisite"] = g2a_ok ? "passed" : "failed"
    g2a_ok || push!(fails, g2a_why)

    sbatch_written = gb_write_script(() -> open(GB_SBATCH, "w") do io
        write(io, SBATCH_TEXT)
    end, g2a_ok)
    gates["sbatch_written_not_submitted"] = "passed"
    self_src = read(@__FILE__, String)
    sb_tok = "sb" * "atch "
    isempty(collect(eachmatch(Regex("run\\(`" * sb_tok), self_src))) ||
        (gates["sbatch_written_not_submitted"] = "failed";
         push!(fails, "sbatch invocation found in checkpoint unit"))
    gates["headnode_refusal_guard"] =
        occursin("REFUSED: head-node execution", SBATCH_TEXT) ? "passed" : "failed"
    exec_lines = join([l for l in split(SBATCH_TEXT, '\n')
                       if !occursin(r"^\s*#", l)], '\n')
    gates["lbl_evaluation_only"] =
        occursin("run_sw_lbl_evaluation.sh", exec_lines) &&
        !occursin("optimize_lut", exec_lines) &&
        !occursin("create_lut", exec_lines) &&
        !occursin("scale_lut", exec_lines) &&
        !occursin("find_g_points", exec_lines) ? "passed" : "failed"
    gates["lbl_evaluation_only"] == "passed" ||
        push!(fails, "forbidden stage invocation in executable lines")
    gates["scenario_override_ten"] =
        occursin("present ch4-350 ch4-700 ch4-1200 ch4-2600 ch4-3500 " *
                 "n2o-190 n2o-270 n2o-405 n2o-540", SBATCH_TEXT) &&
        length(SCENARIOS) == 10 ? "passed" : "failed"
    gates["rgb_band_grid_14300_variant"] =
        occursin("14300, 16650, 20000, 25000, 31750", SBATCH_TEXT) ?
        "passed" : "failed"
    gates["pipeline_parity"] =
        occursin("concat_ckdmip_flux_chunks.jl", SBATCH_TEXT) &&
        occursin("REUSING", SBATCH_TEXT) &&
        occursin("module load nco", SBATCH_TEXT) ? "passed" : "failed"
    gates["exact10_completeness_gate_before_install"] =
        occursin("NOT installing partial set", SBATCH_TEXT) &&
        occursin("INSTALL IDENTITY MISMATCH", SBATCH_TEXT) ? "passed" : "failed"
    gates["stale_output_refusal"] =
        occursin("stale consolidated rgb output", SBATCH_TEXT) &&
        occursin("stale installed rgb output", SBATCH_TEXT) ? "passed" : "failed"
    # quarantine must target work-rgb-g2b and must NOT contain the exact G2a
    # WORK_DIR assignment (…/work-rgb followed by end-of-token, i.e. quote or
    # newline -- NOT work-rgb-g2b). Robust regex, no backspace escape.
    gates["quarantine_separate_from_g2a"] =
        occursin("work-rgb-g2b", SBATCH_TEXT) &&
        occursin("testcopy-rgb-g2b", SBATCH_TEXT) &&
        !occursin(Regex("WORK_DIR=" * replace("$G4WORK/work-rgb", "/" => "\\/") *
                        "(\\s|\"|\$)"), SBATCH_TEXT) ? "passed" : "failed"
    gates["partial_raw_guard"] =
        occursin("partial-RAW guard", SBATCH_TEXT) &&
        occursin("rm -rf \"\$WORKRGB\"", SBATCH_TEXT) ? "passed" : "failed"

    status = isempty(fails) && all(v -> v == "passed", values(gates)) ?
        "g2b_checkpoint_ready" : "g2b_checkpoint_failed"
    branch = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --abbrev-ref HEAD`, String)) catch; "unknown" end
    ghead = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --short HEAD`, String)) catch; "unknown" end

    result = Dict(
        "case" => "gate4_g2b_sw_rgb_variants_checkpoint",
        "data_mode" => "dry_run_script_generation_only",
        "status" => status,
        "timestamp_utc" => string(Dates.now(Dates.UTC)),
        "gates" => gates, "failures" => fails,
        "prerequisite_loader_fixture_verdicts" => lt,
        "sbatch_path" => GB_SBATCH,
        "sbatch_written_this_run" => sbatch_written,
        "sbatch_scripts_state" => sbatch_written ?
            "generated this run (unsubmitted)" :
            "NOT generated this run (prerequisite blocked); any file " *
            "at sbatch_path is PRESERVED HISTORICAL output of an " *
            "earlier run, not current",
        "attempt_history" => Dict(
            "job_4103" => "CANCELED before any valid output (scancel during " *
                "monitor pre-submit review). It had produced a header-size " *
                "partial RAW chunk (RAW_...present_1-10.h5, ~20954 B) in " *
                "work-rgb-g2b; because run_sw_lbl_evaluation reuses nonempty " *
                "RAW files, the corrective sbatch now wipes the G2b " *
                "quarantine tree at stage 0 (partial-RAW guard) before " *
                "regenerating. No consolidated or installed G2b file was " *
                "ever produced by 4103."),
        "scenarios" => SCENARIOS,
        "scenario_support_verified" => "run_sw_lbl_evaluation.sh: 'present' " *
            "explicit branch (415/1921/332); ch4-/n2o- prefix branches set " *
            "the respective VMR",
        "expected_outputs" => ["$CKDMIP_ROOT/evaluation1/sw_fluxes-rgb/" *
            "ckdmip_evaluation1_sw_fluxes-rgb_$s.h5" for s in SCENARIOS],
        "shares_install_dir_with_g2a" => "same evaluation1/sw_fluxes-rgb/ " *
            "dir; disjoint filenames (G2a = rel-*, G2b = present/ch4-/n2o-); " *
            "stale-output refusal covers accidental overlap",
        "remaining_after_g2b" => [
            "evaluation2 rel-415 both bands (TRAINING_BOTH=yes) -- Greg ruling",
            "optimize_lut H5open-preinit shim",
            "LW optimizer data already complete (fsck uses plain fluxes)"],
        "provenance" => Dict("branch" => branch, "generated_from_head" => ghead,
            "provenance_note" => "artifact generated from the working tree " *
                "before its own commit"),
        "disclaimer" => "script generation only; nothing submitted by this " *
                        "unit; LBL evaluation only; no optimizer, create_lut, " *
                        "scale_lut, find_g_points, objective, floor, or " *
                        "recovery computation.",
    )
    mkpath(dirname(GB_RESULTS_JSON))
    open(GB_RESULTS_JSON, "w") do io
        JSON.print(io, result, 2)
    end
    open(GB_RESULTS_MD, "w") do io
        println(io, "# Gate-4 G2b SW-RGB minor-gas training-flux checkpoint\n")
        println(io, "Status: **$status**\n")
        println(io, result["disclaimer"], "\n")
        println(io, "| Gate | Result |")
        println(io, "|---|---|")
        for k in sort(collect(keys(gates)))
            println(io, "| $k | $(gates[k]) |")
        end
        if sbatch_written
            println(io, "\nGenerated (unsubmitted): `$(GB_SBATCH)`")
        else
            println(io, "\nNO script generated this run (prerequisite " *
                        "blocked); any file at `$(GB_SBATCH)` is " *
                        "preserved historical output of an earlier " *
                        "run, not current.")
        end
        println(io, "\n**Attempt history**: job 4103 CANCELED before any " *
                    "valid output during monitor pre-submit review; it left " *
                    "a header-size partial RAW chunk, so the corrective " *
                    "sbatch wipes the G2b quarantine tree at stage 0 " *
                    "(partial-RAW guard) before regenerating.\n")
        println(io, "\nScenarios (10): ", join(SCENARIOS, ", "))
        println(io, "\nScenario support: ", result["scenario_support_verified"])
        println(io, "\nQuarantine: work-rgb-g2b / testcopy-rgb-g2b (disjoint " *
                    "from G2a's work-rgb); shared install dir " *
                    "evaluation1/sw_fluxes-rgb with disjoint filenames.")
        println(io, "\nProvenance: branch `$branch`, generated_from_head " *
                    "`$ghead` (pre-own-commit).")
        isempty(fails) || (println(io, "\n## Failures\n");
                           foreach(f -> println(io, "- ", f), fails))
    end
    println("gate4_g2b_sw_rgb_variants_checkpoint: $status")
    for k in sort(collect(keys(gates)))
        println("  $k: $(gates[k])")
    end
    isempty(fails) || foreach(f -> println("  FAIL: $f"), fails)
    return status == "g2b_checkpoint_ready" ? 0 : 1
end

exit(main())
