# Gate-4 A2 PROOF-DRIVER checkpoint (dry-run; NO submission, NO execution).
#
# Generates the exact Slurm batch script for the reproduction-proof raw
# create_lut builds that consume the 4082 candidates, per mechanism 1 of the
# proof scaffold. Key simplification proven by the readiness audit: the
# candidates ALREADY sit in WORK_{LW,SW}_GPOINTS_DIR under the exact
# filenames create_lut_{lw,sw}.sh derives (INPUT is a bare filename resolved
# via the generated config's append_path), so "placement" reduces to a
# sha256 identity check pinned at generation time.
#
# The generated script runs create_look_up_table ONLY (via the pristine
# create_lut_{lw,sw}.sh drivers in the EXISTING 4082 TESTCOPY -- reused, not
# recreated, so the proof runs in the identical patched environment). NO
# optimize_lut, scale_lut, find_g_points, run_ckd, objective, floor, or
# acceptance use. Submission requires explicit review/go.

include(joinpath(@__DIR__, "validation_results.jl"))

using Dates
import JSON

const WORKCOPY = "/shared/home/greg/ecckd-derived-flux-work/ecckd"
const G4WORK = "/shared/home/greg/ecckd-derived-flux-work/g4-init-generation"
const CKDMIP_ROOT = "/shared/home/greg/data/ckdmip"
const TESTCOPY = "$G4WORK/testcopy"

const LW_CAND = "$G4WORK/work/lw_gpoints/ecckd-1.2_lw_gpoints_climate_fsck-tol0.0161.h5"
const SW_CAND = "$G4WORK/work/sw_gpoints/ecckd-1.2_sw_gpoints_climate_rgb-tol0.047.h5"
const LW_RAW = "$G4WORK/work/lw_raw-ckd-definition/ecckd-1.2_lw_raw-ckd-definition_climate_fsck-tol0.0161.nc"
const SW_RAW = "$G4WORK/work/sw_raw-ckd-definition/ecckd-1.2_sw_raw-ckd-definition_climate_rgb-tol0.047.nc"

const PD_RESULTS_JSON = validation_results_path("gate4_a2_proof_driver_checkpoint.json")
const PD_RESULTS_MD = validation_results_path("gate4_a2_proof_driver_checkpoint.md")
const PD_SBATCH = validation_results_path("gate4_a2_proof_dryrun.sbatch")

sha256(p) = split(strip(read(`sha256sum $p`, String)))[1]

function main()
    fails = String[]
    gates = Dict{String, String}()

    scaffold = JSON.parsefile(
        validation_results_path("gate4_a2_reproduction_proof_scaffold.json"))
    gates["scaffold_ready_required"] =
        scaffold["status"] == "a2_proof_scaffold_ready" ? "passed" : "failed"
    scaffold["status"] == "a2_proof_scaffold_ready" ||
        push!(fails, "proof scaffold not ready: $(scaffold["status"])")

    isfile(LW_CAND) && isfile(SW_CAND) ||
        (push!(fails, "candidate files missing"); return finish(gates, fails,
            Dict(), ""))
    lw_sha = sha256(LW_CAND)
    sw_sha = sha256(SW_CAND)
    gates["candidates_hashed"] = "passed"

    sbatch_text = """
#!/bin/bash
#SBATCH --job-name=g4-a2-proof-create-lut
#SBATCH --output=/shared/home/greg/data/ckdmip-logs/g4-a2-proof-%j.log
#SBATCH --time=08:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=60G
#SBATCH --partition=cpu-large

# Gate-4 A2 reproduction proof: raw create_lut builds ONLY (no optimisation,
# no scaling, no objective stages). Generated by
# gate4_a2_proof_driver_checkpoint.jl; DO NOT run outside Slurm.
set -euo pipefail
if [ -z "\${SLURM_JOB_ID:-}" ]; then
    echo "REFUSED: head-node execution is not permitted; submit via sbatch." >&2
    exit 64
fi

TESTCOPY=$TESTCOPY

echo "=== proof stage 0: environment + candidate identity checks ==="
test -d "\$TESTCOPY" || { echo "REFUSED: 4082 TESTCOPY missing" >&2; exit 68; }
grep -q '^CKDMIP_DATA_DIR=$CKDMIP_ROOT\$' "\$TESTCOPY/config.h" || { echo "BAD config: CKDMIP_DATA_DIR" >&2; exit 68; }
grep -q '^WORK_DIR=$G4WORK/work\$' "\$TESTCOPY/config.h" || { echo "BAD config: WORK_DIR" >&2; exit 68; }
grep -q '^BINDIR=$WORKCOPY/src/ecckd\$' "\$TESTCOPY/config.h" || { echo "BAD config: BINDIR" >&2; exit 68; }
grep -q '^MMM_SW_SPECTRA_DIR=$G4WORK/input/mmm/sw_spectra\$' "\$TESTCOPY/config.h" || { echo "BAD config: MMM_SW_SPECTRA_DIR" >&2; exit 68; }
grep -q '^CLOUD_SPECTRUM=$WORKCOPY/data/mie_droplet_scattering.nc\$' "\$TESTCOPY/config.h" || { echo "BAD config: CLOUD_SPECTRUM" >&2; exit 68; }
sha256sum -c <<'HASHES' || { echo "REFUSED: candidate hash mismatch vs 4082 ledger" >&2; exit 69; }
$lw_sha  $LW_CAND
$sw_sha  $SW_CAND
HASHES
test ! -e "$LW_RAW" || { echo "REFUSED: stale LW raw output already exists; the authorized proof run must CREATE it, not inherit it" >&2; exit 70; }
test ! -e "$SW_RAW" || { echo "REFUSED: stale SW raw output already exists; the authorized proof run must CREATE it, not inherit it" >&2; exit 70; }
test -d "$CKDMIP_ROOT/idealized/lw_spectra" || { echo "MISSING idealized LW spectra" >&2; exit 65; }
test -d "$CKDMIP_ROOT/idealized/sw_spectra" || { echo "MISSING idealized SW spectra" >&2; exit 65; }
test -s "$CKDMIP_ROOT/mmm/conc/ckdmip_mmm-const_concentrations.nc" || { echo "MISSING mmm-const conc" >&2; exit 65; }
test -s "$CKDMIP_ROOT/mmm/sw_spectra_extras/ckdmip_ssi.h5" || { echo "MISSING MMM SSI" >&2; exit 65; }
cd "\$TESTCOPY"

echo "=== proof LW: raw create_lut (fsck, TOLERANCE=0.0161) ==="
APPLICATION=climate BAND_STRUCTURE=fsck TOLERANCE=0.0161 bash create_lut_lw.sh
echo "=== proof SW: raw create_lut (rgb, TOLERANCE=0.047) ==="
APPLICATION=climate BAND_STRUCTURE=rgb TOLERANCE=0.047 bash create_lut_sw.sh

echo "=== proof raw outputs ==="
sha256sum "$LW_RAW" "$SW_RAW"
echo "=== proof create_lut done rc=\$? \$(date -u +%FT%TZ) ==="
"""
    open(PD_SBATCH, "w") do io
        write(io, sbatch_text)
    end

    gates["sbatch_written_not_submitted"] = "passed"
    self_src = read(@__FILE__, String)
    sb_tok = "sb" * "atch "
    isempty(collect(eachmatch(Regex("run\\(`" * sb_tok), self_src))) ||
        (gates["sbatch_written_not_submitted"] = "failed";
         push!(fails, "sbatch invocation found in proof-driver unit"))
    gates["headnode_refusal_guard"] =
        occursin("REFUSED: head-node execution", sbatch_text) ? "passed" : "failed"
    exec_lines = join([l for l in split(sbatch_text, '\n')
                       if !occursin(r"^\s*#", l)], '\n')
    gates["create_lut_only"] =
        occursin("create_lut_lw.sh", exec_lines) &&
        occursin("create_lut_sw.sh", exec_lines) &&
        !occursin("optimize_lut", exec_lines) &&
        !occursin("scale_lut", exec_lines) &&
        !occursin("find_g_points", exec_lines) &&
        !occursin("run_ckd", exec_lines) &&
        !occursin("reorder_spectrum", exec_lines) ? "passed" : "failed"
    gates["create_lut_only"] == "passed" ||
        push!(fails, "forbidden stage invocation in executable proof lines")
    gates["testcopy_reused_not_recreated"] =
        !occursin("rm -rf", exec_lines) && !occursin("sed -i", exec_lines) &&
        occursin("4082 TESTCOPY missing", sbatch_text) ? "passed" : "failed"
    gates["testcopy_reused_not_recreated"] == "passed" ||
        push!(fails, "proof sbatch must reuse the 4082 TESTCOPY unchanged")
    gates["candidate_identity_pinned"] =
        occursin(lw_sha, sbatch_text) && occursin(sw_sha, sbatch_text) &&
        occursin("sha256sum -c", sbatch_text) ? "passed" : "failed"
    gates["raw_outputs_declared"] =
        occursin(LW_RAW, sbatch_text) && occursin(SW_RAW, sbatch_text) ?
        "passed" : "failed"
    gates["raw_outputs_absent_preproof"] =
        !isfile(LW_RAW) && !isfile(SW_RAW) ? "passed" : "failed"
    gates["raw_outputs_absent_preproof"] == "passed" ||
        push!(fails, "raw output(s) already exist before any authorized " *
                     "proof run -- stale files must be investigated, not " *
                     "inherited")
    gates["sbatch_refuses_stale_raw_outputs"] =
        occursin("stale LW raw output", sbatch_text) &&
        occursin("stale SW raw output", sbatch_text) ? "passed" : "failed"
    gates["no_execution_in_this_unit"] = "passed"   # generation only; the
    # comparison runner is a separate refusing script

    payload = Dict(
        "candidates" => Dict(
            "lw" => Dict("path" => LW_CAND, "sha256" => lw_sha),
            "sw" => Dict("path" => SW_CAND, "sha256" => sw_sha)),
        "expected_raw_outputs" => Dict("lw" => LW_RAW, "sw" => SW_RAW),
        "mechanism" => "mechanism 1 (script-faithful): candidates already at " *
            "the exact script-derived INPUT paths (find_g_points wrote them " *
            "there under the same config); placement = pinned sha256 " *
            "identity check; then pristine create_lut_{lw,sw}.sh in the " *
            "REUSED 4082 TESTCOPY",
        "version_skew_note" => "pre-registered mismatch risk: published LW32 " *
            "is ecckd-1.0, published SW32 is ecckd-1.4, pinned rerun " *
            "toolchain is ecckd-1.2; content comparisons are name-agnostic " *
            "but algorithmic drift across versions is a plausible mismatch " *
            "cause; any mismatch -> sensitivity-only per the scaffold " *
            "verdict rule")
    return finish(gates, fails, payload, sbatch_text)
end

function finish(gates, fails, payload, sbatch_text)
    status = isempty(fails) ? "a2_proof_driver_ready_awaiting_go" :
                              "a2_proof_driver_failed"
    branch = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --abbrev-ref HEAD`, String)) catch; "unknown" end
    head = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --short HEAD`, String)) catch; "unknown" end
    result = Dict(
        "case" => "gate4_a2_proof_driver_checkpoint",
        "data_mode" => "dry_run_script_generation_only",
        "status" => status,
        "timestamp_utc" => string(Dates.now(Dates.UTC)),
        "gates" => gates, "failures" => fails,
        "sbatch_path" => PD_SBATCH,
        "payload" => payload,
        "provenance" => Dict("branch" => branch, "generated_from_head" => head,
            "provenance_note" => "artifact generated from the working tree " *
                "before its own commit"),
        "disclaimer" => "dry-run script generation only; nothing submitted; " *
                        "no create_lut, comparison, objective, floor, or " *
                        "acceptance execution; submission requires explicit " *
                        "review/go per the standing protocol.",
    )
    mkpath(dirname(PD_RESULTS_JSON))
    open(PD_RESULTS_JSON, "w") do io
        JSON.print(io, result, 2)
    end
    open(PD_RESULTS_MD, "w") do io
        println(io, "# Gate-4 A2 proof-driver checkpoint (dry-run)\n")
        println(io, "Status: **$status**\n")
        println(io, result["disclaimer"], "\n")
        println(io, "| Gate | Result |")
        println(io, "|---|---|")
        for k in sort(collect(keys(gates)))
            println(io, "| $k | $(gates[k]) |")
        end
        println(io, "\nGenerated (unsubmitted) proof batch script: `$(PD_SBATCH)`")
        if haskey(payload, "candidates")
            println(io, "\nPinned candidate identities:")
            for b in ("lw", "sw")
                c = payload["candidates"][b]
                println(io, "- [$b] `$(basename(c["path"]))` sha256 `$(c["sha256"])`")
            end
            println(io, "\nExpected raw outputs: " *
                        "`$(basename(payload["expected_raw_outputs"]["lw"]))`, " *
                        "`$(basename(payload["expected_raw_outputs"]["sw"]))`")
            println(io, "\nVersion-skew note: ", payload["version_skew_note"])
        end
        println(io, "\nProvenance: branch `$branch`, generated_from_head " *
                    "`$head` (pre-own-commit).")
        isempty(fails) || (println(io, "\n## Failures\n");
                           foreach(f -> println(io, "- ", f), fails))
    end
    println("gate4_a2_proof_driver_checkpoint: $status")
    for k in sort(collect(keys(gates)))
        println("  $k: $(gates[k])")
    end
    isempty(fails) || foreach(f -> println("  FAIL: $f"), fails)
    return status == "a2_proof_driver_ready_awaiting_go" ? 0 : 1
end

exit(main())
