# Gate-4 A2 EXECUTION CHECKPOINT + proof scaffold (dry-run; NO submission).
#
# Generates the exact Slurm batch script for the A2 merge_well_mixed +
# reorder + find_g_points run (LW fsck tol 0.0161, SW rgb tol 0.047 FIRST,
# per the pinned do_all stage lists) and records the follow-on
# exact-reproduction proof plan. The batch script is WRITTEN but never
# submitted by this unit; it refuses head-node execution by guard. No
# find_g_points/create_lut/objective/floor execution.
#
# REVISED after job 4079 FAILED at LW reorder: the previous script skipped
# do_all stage 1 (merge_well_mixed_{lw,sw}.sh), so the quarantined WORK_DIR
# had no composite spectra. Additionally the SW composite requires
# ckdmip_mmm_sw_spectra_rayleigh_present.h5 (COMPOSITE_SW_INCLUDES_RAYLEIGH=yes
# in the pinned config), absent from the local MMM tree and 404 on ECPDS;
# it is provisioned in a QUARANTINED INPUT OVERLAY (never mutating
# $CKDMIP_ROOT) using the upstream author's own pinned recipe
# (ckdmip-1.0/work/sw/make_rayleigh_mmm.sh): ckdmip_tool --grid
# <mmm sw h2o_median> --rayleigh.

include(joinpath(@__DIR__, "validation_results.jl"))

using Dates
import JSON

const WORKCOPY = "/shared/home/greg/ecckd-derived-flux-work/ecckd"
const G4WORK = "/shared/home/greg/ecckd-derived-flux-work/g4-init-generation"
const CKDMIP_ROOT = "/shared/home/greg/data/ckdmip"
const CKDMIP_BIN = "/shared/home/greg/build/ckdmip-1.0/bin"
const CKDMIP_TOOL = "$CKDMIP_BIN/ckdmip_tool"
const RAYLEIGH_RECIPE = "/shared/home/greg/build/ckdmip-1.0/work/sw/make_rayleigh_mmm.sh"

# binaries every A2 stage needs (relocation-proof preflight)
const CKDMIP_BINARIES = ["ckdmip_lw", "ckdmip_sw", "ckdmip_tool"]
const ECCKD_BINARIES = ["reorder_spectrum", "find_g_points",
                        "reorder_cloud_spectrum"]

# per-gas MMM spectra consumed by merge_well_mixed_{lw,sw}.sh (present +
# climate --conc-scaled merges), by the reorder GAS_LISTs, and by
# find_g_points climate (h2o/o3 minimum as background_input)
const MERGE_GASES = ["o2_constant", "n2_constant", "co2_present",
                     "ch4_present", "n2o_present",
                     "cfc11_present-equivalent", "cfc12_present"]
const REORDER_FIND_GASES = ["h2o_median", "o3_median",
                            "h2o_minimum", "o3_minimum"]

const AX_RESULTS_JSON = validation_results_path("gate4_a2_execution_checkpoint.json")
const AX_RESULTS_MD = validation_results_path("gate4_a2_execution_checkpoint.md")
const AX_SBATCH = validation_results_path("gate4_a2_dryrun.sbatch")

const SBATCH_TEXT = """
#!/bin/bash
#SBATCH --job-name=g4-a2-find-g-points
#SBATCH --output=/shared/home/greg/data/ckdmip-logs/g4-a2-%j.log
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=60G
#SBATCH --partition=cpu-large

# Gate-4 A2: merge_well_mixed + reorder_spectrum + find_g_points ONLY (no
# LUT-creation, no optimisation, no objective stages). Generated by
# gate4_a2_execution_checkpoint.jl; DO NOT run outside Slurm.
set -euo pipefail
if [ -z "\${SLURM_JOB_ID:-}" ]; then
    echo "REFUSED: head-node execution is not permitted; submit via sbatch." >&2
    exit 64
fi

WORKCOPY=$WORKCOPY
G4WORK=$G4WORK
mkdir -p "\$G4WORK"

# scoped test-dir copy with WORK_DIR redirected to the quarantined g4 tree
# ISOLATED test-copy: never mutate the 4078 working copy; config.h
# hard-codes CKDMIP_DATA_DIR/WORK_DIR/BINDIR, so env-only localization is
# INSUFFICIENT -- all three are sed-patched ABSOLUTE in the copy (BINDIR in
# the pristine file is ../src/ecckd relative to test/, which would break in
# a relocated copy).
TESTCOPY="\$G4WORK/testcopy"
rm -rf "\$TESTCOPY"
cp -r "\$WORKCOPY/test" "\$TESTCOPY"
# MMM_SW_SPECTRA_DIR is redirected to a QUARANTINED INPUT OVERLAY (symlinks
# to the official per-gas files + locally generated rayleigh); the official
# data tree under CKDMIP_DATA_DIR is never written to.
sed -i \
  -e 's|^CKDMIP_DATA_DIR=.*|CKDMIP_DATA_DIR=$CKDMIP_ROOT|' \
  -e 's|^WORK_DIR=.*|WORK_DIR=$G4WORK/work|' \
  -e 's|^BINDIR=.*|BINDIR=$WORKCOPY/src/ecckd|' \
  -e 's|^MMM_SW_SPECTRA_DIR=.*|MMM_SW_SPECTRA_DIR=$G4WORK/input/mmm/sw_spectra|' \
  -e 's|^CLOUD_SPECTRUM=.*|CLOUD_SPECTRUM=$WORKCOPY/data/mie_droplet_scattering.nc|' \
  "\$TESTCOPY/config.h"
grep -E "^(CKDMIP_DATA_DIR|WORK_DIR|BINDIR|MMM_SW_SPECTRA_DIR|CLOUD_SPECTRUM)=" "\$TESTCOPY/config.h"
cd "\$TESTCOPY"

echo "=== A2 stage 0: binary + composite-input preflight + SW rayleigh overlay ==="
for b in $(join(CKDMIP_BINARIES, " ")); do
    test -x "$CKDMIP_BIN/\$b" || { echo "MISSING binary: \$b" >&2; exit 67; }
done
for b in $(join(ECCKD_BINARIES, " ")); do
    test -x "$WORKCOPY/src/ecckd/\$b" || { echo "MISSING binary: \$b" >&2; exit 67; }
done
test -s "$WORKCOPY/data/mie_droplet_scattering.nc" || { echo "MISSING cloud spectrum (mie)" >&2; exit 65; }
test -s "$CKDMIP_ROOT/evaluation1/sw_spectra/ckdmip_ssi.h5" || { echo "MISSING training SSI (cloud reorder wavenumber_input)" >&2; exit 65; }
MMM_LW=$CKDMIP_ROOT/mmm/lw_spectra
MMM_SW=$CKDMIP_ROOT/mmm/sw_spectra
for gas in $(join(vcat(MERGE_GASES, REORDER_FIND_GASES), " ")); do
    test -s "\$MMM_LW/ckdmip_mmm_lw_spectra_\${gas}.h5" || { echo "MISSING LW input: \$gas" >&2; exit 65; }
    test -s "\$MMM_SW/ckdmip_mmm_sw_spectra_\${gas}.h5" || { echo "MISSING SW input: \$gas" >&2; exit 65; }
done
test -s "$CKDMIP_ROOT/mmm/sw_spectra_extras/ckdmip_ssi.h5" || { echo "MISSING MMM SSI" >&2; exit 65; }
OVERLAY=\$G4WORK/input/mmm/sw_spectra
mkdir -p "\$OVERLAY"
ln -sf "\$MMM_SW"/*.h5 "\$OVERLAY/"
RAYLEIGH=\$OVERLAY/ckdmip_mmm_sw_spectra_rayleigh_present.h5
if [ ! -s "\$RAYLEIGH" ]; then
    # upstream author's pinned recipe (ckdmip-1.0/work/sw/make_rayleigh_mmm.sh)
    $CKDMIP_TOOL --grid "\$MMM_SW/ckdmip_mmm_sw_spectra_h2o_median.h5" --rayleigh -o "\$RAYLEIGH"
fi
test -s "\$RAYLEIGH" || { echo "MISSING SW rayleigh after overlay generation" >&2; exit 66; }
echo "rayleigh overlay provenance:"; sha256sum "\$RAYLEIGH"

echo "=== A2 LW stage 1: merge_well_mixed (composite spectra) ==="
APPLICATION=climate bash merge_well_mixed_lw.sh
echo "=== A2 LW: reorder (fsck) ==="
APPLICATION=climate BAND_STRUCTURE=fsck bash reorder_spectrum_lw.sh
echo "=== A2 LW: find_g_points (fsck, TOLERANCE=0.0161) ==="
APPLICATION=climate BAND_STRUCTURE=fsck TOLERANCE=0.0161 bash find_g_points_lw.sh
echo "=== A2 SW stage 1: merge_well_mixed (composite spectra incl rayleigh) ==="
APPLICATION=climate bash merge_well_mixed_sw.sh
echo "=== A2 SW: reorder (rgb) ==="
APPLICATION=climate BAND_STRUCTURE=rgb bash reorder_spectrum_sw.sh
echo "=== A2 SW: find_g_points (rgb, TOLERANCE=0.047) ==="
APPLICATION=climate BAND_STRUCTURE=rgb TOLERANCE=0.047 bash find_g_points_sw.sh

echo "=== A2 outputs ==="
find "$G4WORK/work" -name "*gpoints*" -o -name "*order*" | head -40
echo "=== A2 done rc=\$? \$(date -u +%FT%TZ) ==="
"""

function main()
    fails = String[]
    gates = Dict{String, String}()

    a2 = JSON.parsefile(
        validation_results_path("gate4_a2_find_g_points_rerun_manifest.json"))
    a2["status"] == "a2_manifest_ready" ||
        push!(fails, "A2 manifest not ready: $(a2["status"])")

    # write the dry-run sbatch (artifact; never submitted here)
    open(AX_SBATCH, "w") do io
        write(io, SBATCH_TEXT)
    end

    # gates
    gates["sbatch_written_not_submitted"] = "passed"   # structural: this
    # script contains no `sbatch` invocation (self-scan with split token)
    self_src = read(@__FILE__, String)
    sb_tok = "sb" * "atch "
    n_direct = length(collect(eachmatch(Regex("run\\(`" * sb_tok), self_src)))
    n_direct == 0 || (gates["sbatch_written_not_submitted"] = "failed";
                      push!(fails, "sbatch invocation found in checkpoint unit"))
    gates["headnode_refusal_guard"] =
        occursin("REFUSED: head-node execution", SBATCH_TEXT) ? "passed" : "failed"
    # scan EXECUTABLE lines only (comments stripped) so the script may
    # mention forbidden stages in prose without failing itself
    exec_lines = join([l for l in split(SBATCH_TEXT, '\n')
                       if !occursin(r"^\s*#", l)], '\n')
    gates["merge_reorder_find_only"] =
        !occursin("create_lut", exec_lines) &&
        !occursin("create_look_up_table", exec_lines) &&
        !occursin("optimize_lut", exec_lines) ? "passed" : "failed"
    gates["merge_reorder_find_only"] == "passed" ||
        push!(fails, "forbidden stage invocation in executable sbatch lines")
    # 4079 failure fix: stage-1 merge must precede reorder per band
    i_mlw = findfirst("merge_well_mixed_lw.sh", exec_lines)
    i_rlw = findfirst("reorder_spectrum_lw.sh", exec_lines)
    i_msw = findfirst("merge_well_mixed_sw.sh", exec_lines)
    i_rsw = findfirst("reorder_spectrum_sw.sh", exec_lines)
    gates["stage1_merge_before_reorder"] =
        (!isnothing(i_mlw) && !isnothing(i_rlw) && !isnothing(i_msw) &&
         !isnothing(i_rsw) && first(i_mlw) < first(i_rlw) &&
         first(i_msw) < first(i_rsw)) ? "passed" : "failed"
    gates["stage1_merge_before_reorder"] == "passed" ||
        push!(fails, "merge_well_mixed stages missing or misordered")
    # SW rayleigh provisioned in a quarantined overlay, never into the
    # official data tree
    gates["rayleigh_overlay_provisioned"] =
        (occursin("--rayleigh", exec_lines) &&
         occursin("$G4WORK/input/mmm/sw_spectra", SBATCH_TEXT) &&
         occursin("MMM_SW_SPECTRA_DIR=$G4WORK/input/mmm/sw_spectra", SBATCH_TEXT) &&
         !occursin(Regex("--rayleigh[^\n]*-o[^\n]*" * CKDMIP_ROOT), exec_lines)) ?
        "passed" : "failed"
    gates["rayleigh_overlay_provisioned"] == "passed" ||
        push!(fails, "SW rayleigh overlay provisioning missing or mutates data tree")
    # checkpoint-side composite-input preflight (files on disk NOW);
    # rayleigh counts as satisfied if present in overlay OR generatable via
    # the pinned recipe (grid file + pinned tool both present)
    input_manifest = Any[]
    inputs_ok = true
    for band in ("lw", "sw"), gas in vcat(MERGE_GASES, REORDER_FIND_GASES)
        p = joinpath(CKDMIP_ROOT, "mmm", "$(band)_spectra",
                     "ckdmip_mmm_$(band)_spectra_$(gas).h5")
        ok = isfile(p) && filesize(p) > 0
        inputs_ok &= ok
        push!(input_manifest, Dict("input" => basename(p), "present" => ok))
    end
    ssi = joinpath(CKDMIP_ROOT, "mmm/sw_spectra_extras/ckdmip_ssi.h5")
    inputs_ok &= isfile(ssi)
    push!(input_manifest, Dict("input" => basename(ssi), "present" => isfile(ssi)))
    for (label, p) in [
        ("mie_droplet_scattering.nc (CLOUD_SPECTRUM, sed-patched absolute)",
         joinpath(WORKCOPY, "data/mie_droplet_scattering.nc")),
        ("evaluation1 ckdmip_ssi.h5 (TRAINING_SW_SSI, cloud-reorder " *
         "wavenumber_input)",
         joinpath(CKDMIP_ROOT, "evaluation1/sw_spectra/ckdmip_ssi.h5"))]
        ok = isfile(p) && filesize(p) > 0
        inputs_ok &= ok
        push!(input_manifest, Dict("input" => label, "present" => ok))
    end
    for b in CKDMIP_BINARIES
        ok = isfile(joinpath(CKDMIP_BIN, b))
        inputs_ok &= ok
        push!(input_manifest, Dict("input" => "binary $b", "present" => ok))
    end
    for b in ECCKD_BINARIES
        ok = isfile(joinpath(WORKCOPY, "src/ecckd", b))
        inputs_ok &= ok
        push!(input_manifest, Dict("input" => "binary $b", "present" => ok))
    end
    overlay_rayleigh = joinpath(G4WORK, "input/mmm/sw_spectra",
                                "ckdmip_mmm_sw_spectra_rayleigh_present.h5")
    grid = joinpath(CKDMIP_ROOT, "mmm/sw_spectra",
                    "ckdmip_mmm_sw_spectra_h2o_median.h5")
    rayleigh_ok = (isfile(overlay_rayleigh) && filesize(overlay_rayleigh) > 0) ||
                  (isfile(grid) && isfile(CKDMIP_TOOL))
    inputs_ok &= rayleigh_ok
    push!(input_manifest, Dict(
        "input" => "ckdmip_mmm_sw_spectra_rayleigh_present.h5 (overlay)",
        "present" => isfile(overlay_rayleigh),
        "generatable_via_pinned_recipe" => isfile(grid) && isfile(CKDMIP_TOOL),
        "recipe" => RAYLEIGH_RECIPE))
    gates["composite_inputs_preflight"] = inputs_ok ? "passed" : "failed"
    inputs_ok || push!(fails, "composite-stage inputs missing (see input_manifest)")
    gates["target_tolerances_narrowed"] =
        occursin("TOLERANCE=0.0161", SBATCH_TEXT) &&
        occursin("TOLERANCE=0.047", SBATCH_TEXT) ? "passed" : "failed"
    gates["workdir_quarantined"] =
        occursin("g4-init-generation/work", SBATCH_TEXT) ? "passed" : "failed"
    running_4078 = try
        !isempty(strip(read(`squeue -j 4078 -h -o "%T"`, String)))
    catch; false end
    contention = Dict(
        "job_4078_running" => running_4078,
        "policy" => "A2 may run CONCURRENTLY with 4078 on a different " *
                    "cpu-large node (partition has 4 nodes); do not submit " *
                    "if the partition is saturated; never share the node " *
                    "running 4078",
    )
    gates["contention_policy_recorded"] = "passed"
    gates["config_copy_patched_not_env_only"] =
        occursin("sed -i", SBATCH_TEXT) &&
        occursin("CKDMIP_DATA_DIR=", SBATCH_TEXT) &&
        occursin("BINDIR=" * WORKCOPY * "/src/ecckd", SBATCH_TEXT) &&
        occursin("MMM_SW_SPECTRA_DIR=$G4WORK/input/mmm/sw_spectra", SBATCH_TEXT) &&
        occursin("CLOUD_SPECTRUM=$WORKCOPY/data/mie_droplet_scattering.nc",
                 SBATCH_TEXT) &&
        occursin("INSUFFICIENT", SBATCH_TEXT) ? "passed" : "failed"
    gates["config_copy_patched_not_env_only"] == "passed" ||
        push!(fails, "config.h copy-patch of all five path vars not present " *
                     "(CLOUD_SPECTRUM is ../data-relative in the pristine " *
                     "file and breaks in a relocated TESTCOPY)")
    gates["no_mutation_of_4078_workcopy"] =
        !occursin(Regex("sed -i[^\n]*\\\$WORKCOPY/test/config"), SBATCH_TEXT) &&
        occursin("cp -r \"\$WORKCOPY/test\"", SBATCH_TEXT) ? "passed" : "failed"

    proof_plan = Dict(
        "unit" => "gate4_a2_reproduction_proof (follow-on; not implemented here)",
        "inputs" => ["rerun gpoints candidates: " *
                     "$G4WORK/work/**/ecckd-*_{lw,sw}_gpoints_*tol{0.0161,0.047}*.h5",
                     "raw create_lut outputs built FROM those candidates " *
                     "(init-generation manifest commands)",
                     "published LW32/SW32 definitions (verification targets)"],
        "gates" => ["g-counts exactly 32/32",
                    "gpoint_fraction elementwise EXACT vs published",
                    "wavenumber1_band/wavenumber2_band/band_number EXACT",
                    "on any mismatch: candidates are sensitivity-only; " *
                    "report, do not proceed to floor"],
        "refusal" => "proof runner refuses when candidate files are absent",
    )

    status = isempty(fails) ? "a2_execution_checkpoint_ready" :
                              "a2_execution_checkpoint_failed"
    branch = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --abbrev-ref HEAD`, String)) catch; "unknown" end
    head = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --short HEAD`, String)) catch; "unknown" end

    result = Dict(
        "case" => "gate4_a2_execution_checkpoint",
        "data_mode" => "dry_run_script_generation_only",
        "status" => status,
        "timestamp_utc" => string(Dates.now(Dates.UTC)),
        "gates" => gates, "failures" => fails,
        "sbatch_path" => AX_SBATCH,
        "env_localization" => Dict(
            "mechanism" => "ALL THREE hard-coded config.h path variables " *
                "are sed-patched ABSOLUTE inside the isolated TESTCOPY; " *
                "env-only localization is insufficient and gated; the " *
                "active 4078 working copy is read only as a copy source, " *
                "never mutated",
            "CKDMIP_DATA_DIR" => "$CKDMIP_ROOT (sed-patched in TESTCOPY)",
            "WORK_DIR" => "$G4WORK/work (sed-patched in TESTCOPY; " *
                          "quarantined from 4078's workdir)",
            "BINDIR" => "$WORKCOPY/src/ecckd (sed-patched ABSOLUTE in " *
                        "TESTCOPY; pristine relative ../src/ecckd would " *
                        "break in a relocated copy)",
            "MMM_SW_SPECTRA_DIR" => "$G4WORK/input/mmm/sw_spectra " *
                "(sed-patched to the QUARANTINED overlay: symlinks to the " *
                "official per-gas files + rayleigh generated by the pinned " *
                "recipe $RAYLEIGH_RECIPE with $CKDMIP_TOOL; the official " *
                "data tree is never written to)",
            "APPLICATION" => "climate",
            "BAND_STRUCTURE/TOLERANCE" => "fsck/0.0161 (LW), rgb/0.047 (SW) " *
                                          "first; 16-g sanity later"),
        "input_manifest" => input_manifest,
        "expected_outputs" => Dict(
            "gpoints" => "$G4WORK/work/**/ecckd-*_gpoints_climate_" *
                         "{fsck-tol0.0161,rgb-tol0.047}.h5",
            "reorder" => "$G4WORK/work/**/{lw,sw}_order_*_*.h5",
            "log" => "/shared/home/greg/data/ckdmip-logs/g4-a2-<jobid>.log"),
        "contention" => contention,
        "proof_plan" => proof_plan,
        "provenance" => Dict("branch" => branch, "generated_from_head" => head,
            "provenance_note" => "artifact generated from the working tree " *
                "before its own commit"),
        "disclaimer" => "dry-run script generation only; nothing submitted; " *
                        "no find_g_points/create_lut/objective/floor " *
                        "execution; the generated script runs " *
                        "merge_well_mixed + reorder + find_g_points only; " *
                        "submission requires explicit authorization per the " *
                        "standing protocol.",
    )
    mkpath(dirname(AX_RESULTS_JSON))
    open(AX_RESULTS_JSON, "w") do io
        JSON.print(io, result, 2)
    end
    open(AX_RESULTS_MD, "w") do io
        println(io, "# Gate-4 A2 execution checkpoint (dry-run)\n")
        println(io, "Status: **$status**\n")
        println(io, result["disclaimer"], "\n")
        println(io, "| Gate | Result |")
        println(io, "|---|---|")
        for k in sort(collect(keys(gates)))
            println(io, "| $k | $(gates[k]) |")
        end
        println(io, "\nGenerated (unsubmitted) batch script: `$(AX_SBATCH)`")
        n_present = count(m -> get(m, "present", false), input_manifest)
        println(io, "\nComposite-input preflight: $n_present/" *
                    "$(length(input_manifest)) present " *
                    "(SW rayleigh provisioned in the quarantined overlay " *
                    "via the pinned recipe when absent).")
        println(io, "\nContention: 4078 running = $(contention["job_4078_running"]); " *
                    contention["policy"])
        println(io, "\nFollow-on proof plan: g-counts 32/32; gpoint_fraction " *
                    "and band arrays elementwise EXACT vs published; any " *
                    "mismatch -> sensitivity-only, no floor.")
        println(io, "\nProvenance: branch `$branch`, generated_from_head " *
                    "`$head` (pre-own-commit).")
        isempty(fails) || (println(io, "\n## Failures\n");
                           foreach(f -> println(io, "- ", f), fails))
    end
    println("gate4_a2_execution_checkpoint: $status")
    for k in sort(collect(keys(gates)))
        println("  $k: $(gates[k])")
    end
    isempty(fails) || foreach(f -> println("  FAIL: $f"), fails)
    return status == "a2_execution_checkpoint_ready" ? 0 : 1
end

exit(main())
