# Gate-4 G2c EVALUATION2 SPECTRA FETCH checkpoint (dry-run generation; NO
# submission). Option A data gate: faithful TRAINING_BOTH=yes recovery needs
# ckdmip_evaluation2_{lw,sw}_fluxes_rel-415 flux files, generated from the
# evaluation2 LBL spectra. This unit fetches ONLY the spectra a rel-415 run
# reads (recon-verified): 7 species x 5 chunks per band = 70 files, ~330 GB
# (LW 219.6 GB + SW 110.4 GB). cfc11/cfc12 are skipped (rel-415 RELATIVE
# branch never reads them); SW rayleigh is NOT on S3/ECPDS and is generated
# in the follow-on flux unit; SSI reuses evaluation1's local copy.
#
# Source: s3://aeolus-dev/users/greg@aeolus.earth/ckdmip/evaluation2/
# (byte-verified archive of the ECPDS originals per archive_to_s3.log
# 2026-05-27; ECPDS itself confirmed live as fallback). Greg re-authed SSO
# and said "keep going" (2026-08-12). aws s3 sync is idempotent/resumable.
#
# NO optimizer, LBL, create/scale/find stages. Fetch + verify only.

include(joinpath(@__DIR__, "validation_results.jl"))

using Dates
import JSON

const S3_BASE = "s3://aeolus-dev/users/greg@aeolus.earth/ckdmip/evaluation2"
const DEST = "/shared/home/greg/data/ckdmip/evaluation2"
const SPECIES = ["h2o_present", "o3_present", "co2_present", "ch4_present",
                 "n2o_present", "n2_constant", "o2_constant"]
const CHUNKS = ["1-10", "11-20", "21-30", "31-40", "41-50"]

const GC_RESULTS_JSON = validation_results_path("gate4_g2c_eval2_fetch_checkpoint.json")
const GC_RESULTS_MD = validation_results_path("gate4_g2c_eval2_fetch_checkpoint.md")
const GC_SBATCH = validation_results_path("gate4_g2c_eval2_fetch.sbatch")

incl_args(band) = join(["--include \"ckdmip_evaluation2_$(band)_spectra_$(sp)_*.h5\""
                        for sp in SPECIES], " ")

const SBATCH_TEXT = """
#!/bin/bash
#SBATCH --job-name=g4-g2c-eval2-fetch
#SBATCH --output=/shared/home/greg/data/ckdmip-logs/g4-g2c-%j.log
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16G
#SBATCH --partition=cpu-large

# Gate-4 G2c: evaluation2 spectra fetch ONLY (no LBL, no optimizer, no
# create/scale/find stages). Generated by gate4_g2c_eval2_fetch_checkpoint.jl.
set -euo pipefail
if [ -z "\${SLURM_JOB_ID:-}" ]; then
    echo "REFUSED: head-node execution is not permitted; submit via sbatch." >&2
    exit 64
fi

DEST=$DEST

echo "=== G2c stage 0: preflight ==="
command -v aws >/dev/null || { echo "MISSING aws CLI on compute node" >&2; exit 65; }
aws sts get-caller-identity >/dev/null || { echo "REFUSED: AWS auth unavailable (SSO expired?)" >&2; exit 66; }
avail_kb=\$(df --output=avail /shared | tail -1)
[ "\$avail_kb" -gt 419430400 ] || { echo "REFUSED: <400GB free on /shared" >&2; exit 67; }
mkdir -p "\$DEST/lw_spectra" "\$DEST/sw_spectra"

echo "=== G2c stage 1: sync LW spectra (7 species x 5 chunks, ~220 GB) ==="
aws s3 sync "$S3_BASE/lw_spectra/" "\$DEST/lw_spectra/" \\
  --exclude "*" $(incl_args("lw")) --no-progress
echo "=== G2c stage 2: sync SW spectra (7 species x 5 chunks, ~110 GB) ==="
aws s3 sync "$S3_BASE/sw_spectra/" "\$DEST/sw_spectra/" \\
  --exclude "*" $(incl_args("sw")) --no-progress

echo "=== G2c stage 3: exact-70 completeness + size verification ==="
MISSING=0
for band in lw sw; do
    for sp in $(join(SPECIES, " ")); do
        for chunk in $(join(CHUNKS, " ")); do
            f="\$DEST/\${band}_spectra/ckdmip_evaluation2_\${band}_spectra_\${sp}_\${chunk}.h5"
            [ -s "\$f" ] || { echo "MISSING \$f" >&2; MISSING=1; }
        done
    done
done
[ "\$MISSING" = 0 ] || { echo "REFUSED: completeness gate failed" >&2; exit 71; }
# re-run sync as identity check: any transfer line means a size/mtime
# mismatch survived stage 1-2 (sync copies only on mismatch, so a clean
# second pass proves local == S3 for every included file)
RESYNC=\$(aws s3 sync "$S3_BASE/lw_spectra/" "\$DEST/lw_spectra/" --exclude "*" $(incl_args("lw")) --no-progress 2>&1 | head -5)
RESYNC2=\$(aws s3 sync "$S3_BASE/sw_spectra/" "\$DEST/sw_spectra/" --exclude "*" $(incl_args("sw")) --no-progress 2>&1 | head -5)
[ -z "\$RESYNC\$RESYNC2" ] || { echo "REFUSED: resync transferred data (mismatch): \$RESYNC \$RESYNC2" >&2; exit 72; }

echo "=== G2c outputs ==="
echo "lw files: \$(ls "\$DEST/lw_spectra/" | wc -l)  bytes: \$(du -sb "\$DEST/lw_spectra" | cut -f1)"
echo "sw files: \$(ls "\$DEST/sw_spectra/" | wc -l)  bytes: \$(du -sb "\$DEST/sw_spectra" | cut -f1)"
echo "=== G2c done rc=\$? \$(date -u +%FT%TZ) ==="
"""

function main()
    fails = String[]
    gates = Dict{String, String}()

    ident_ok = try
        occursin("aeolus", read(`aws sts get-caller-identity`, String))
    catch; false end
    gates["aws_auth_at_generation"] = ident_ok ? "passed" : "failed"
    ident_ok || push!(fails, "AWS auth unavailable at checkpoint generation")

    open(GC_SBATCH, "w") do io
        write(io, SBATCH_TEXT)
    end
    gates["sbatch_written_not_submitted"] = "passed"
    self_src = read(@__FILE__, String)
    sb_tok = "sb" * "atch "
    isempty(collect(eachmatch(Regex("run\\(`" * sb_tok), self_src))) ||
        (gates["sbatch_written_not_submitted"] = "failed";
         push!(fails, "sbatch invocation found in checkpoint unit"))
    gates["headnode_refusal_guard"] =
        occursin("REFUSED: head-node execution", SBATCH_TEXT) ? "passed" : "failed"
    exec_lines = join([l for l in split(SBATCH_TEXT, '\n')
                       if !occursin(r"^\s*#", l)], '\n')
    gates["fetch_only"] =
        occursin("aws s3 sync", exec_lines) &&
        !occursin("optimize_lut", exec_lines) &&
        !occursin("create_lut", exec_lines) &&
        !occursin("scale_lut", exec_lines) &&
        !occursin("find_g_points", exec_lines) &&
        !occursin("lbl_evaluation", exec_lines) &&
        !occursin("ckdmip_lw", exec_lines) &&
        !occursin("ckdmip_sw", exec_lines) ? "passed" : "failed"
    gates["fetch_only"] == "passed" ||
        push!(fails, "forbidden stage invocation in executable lines")
    gates["species_scope_correct"] =
        length(SPECIES) == 7 && !occursin("cfc", join(SPECIES)) &&
        occursin("n2_constant", join(SPECIES)) ? "passed" : "failed"
    gates["exact70_gate"] =
        occursin("completeness gate failed", SBATCH_TEXT) &&
        occursin("resync transferred data", SBATCH_TEXT) ? "passed" : "failed"
    gates["disk_guard"] = occursin("400GB free", SBATCH_TEXT) ? "passed" : "failed"

    status = isempty(fails) && all(v -> v == "passed", values(gates)) ?
        "g2c_checkpoint_ready" : "g2c_checkpoint_failed"
    branch = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --abbrev-ref HEAD`, String)) catch; "unknown" end
    ghead = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --short HEAD`, String)) catch; "unknown" end

    result = Dict(
        "case" => "gate4_g2c_eval2_fetch_checkpoint",
        "data_mode" => "dry_run_script_generation_only",
        "status" => status,
        "timestamp_utc" => string(Dates.now(Dates.UTC)),
        "gates" => gates, "failures" => fails,
        "authorization" => "Greg: 'go with option A' (2026-07-30) + SSO " *
            "re-auth and 'keep going' (2026-08-12)",
        "sbatch_path" => GC_SBATCH,
        "source" => "$S3_BASE (byte-verified ECPDS archive per " *
                    "archive_to_s3.log 2026-05-27; ECPDS live as fallback)",
        "scope" => Dict(
            "species" => SPECIES, "chunks" => CHUNKS,
            "expected_files" => 70,
            "expected_bytes_approx" => "LW 219.6 GB + SW 110.4 GB = ~330 GB",
            "skipped" => "cfc11/cfc12 (rel-415 never reads them); rayleigh " *
                "(not on S3/ECPDS -- generated in the follow-on flux unit); " *
                "ssi (evaluation1 local copy reused)"),
        "followon" => "G2d: rayleigh generation (make_rayleigh_evaluation.sh " *
            "recipe, ckdmip_tool --rayleigh on the 5 eval2 h2o_present SW " *
            "chunks) + rel-415 LBL runs (LW plain, SW rgb-banded) -> 2 flux " *
            "files -> ledger -> G3",
        "provenance" => Dict("branch" => branch, "generated_from_head" => ghead,
            "provenance_note" => "artifact generated from the working tree " *
                "before its own commit"),
        "disclaimer" => "script generation only; nothing submitted by this " *
                        "unit; fetch+verify only; no LBL, optimizer, " *
                        "objective, floor, or recovery computation.",
    )
    mkpath(dirname(GC_RESULTS_JSON))
    open(GC_RESULTS_JSON, "w") do io
        JSON.print(io, result, 2)
    end
    open(GC_RESULTS_MD, "w") do io
        println(io, "# Gate-4 G2c evaluation2 spectra fetch checkpoint\n")
        println(io, "Status: **$status**\n")
        println(io, result["disclaimer"], "\n")
        println(io, "Authorization: ", result["authorization"], "\n")
        println(io, "| Gate | Result |")
        println(io, "|---|---|")
        for k in sort(collect(keys(gates)))
            println(io, "| $k | $(gates[k]) |")
        end
        println(io, "\nSource: ", result["source"])
        println(io, "\nScope: 7 species x 5 chunks x 2 bands = 70 files, " *
                    "~330 GB; cfc/rayleigh/ssi excluded (see JSON).")
        println(io, "\nFollow-on: ", result["followon"])
        println(io, "\nProvenance: branch `$branch`, generated_from_head " *
                    "`$ghead` (pre-own-commit).")
        isempty(fails) || (println(io, "\n## Failures\n");
                           foreach(f -> println(io, "- ", f), fails))
    end
    println("gate4_g2c_eval2_fetch_checkpoint: $status")
    for k in sort(collect(keys(gates)))
        println("  $k: $(gates[k])")
    end
    isempty(fails) || foreach(f -> println("  FAIL: $f"), fails)
    return status == "g2c_checkpoint_ready" ? 0 : 1
end

exit(main())
