# Gate-4 G2c EVALUATION2 SPECTRA FETCH checkpoint (dry-run generation; NO
# submission). Option A data gate: faithful TRAINING_BOTH=yes recovery needs
# ckdmip_evaluation2_{lw,sw}_fluxes_rel-415 flux files, generated from the
# evaluation2 LBL spectra. This unit fetches ONLY the spectra a rel-415 run
# reads (recon-verified): 7 species x 5 chunks per band = 70 files, ~330 GB
# (LW 219.6 GB + SW 110.4 GB). cfc11/cfc12 are skipped (rel-415 RELATIVE
# branch never reads them); SW rayleigh is NOT on S3/ECPDS and is generated
# in the follow-on flux unit; SSI reuses evaluation1's local copy.
#
# Source: s3://aeolus-dev/users/greg@aeolus.earth/ckdmip/evaluation2/
# (byte-verified archive of the ECPDS originals per archive_to_s3.log
# 2026-05-27; ECPDS itself confirmed live as fallback). Greg re-authed SSO
# and said "keep going" (2026-08-12). aws s3 sync is idempotent/resumable.
#
# NO optimizer, LBL, create/scale/find stages. Fetch + verify only.

include(joinpath(@__DIR__, "validation_results.jl"))

using Dates
import JSON

const S3_BASE = "s3://aeolus-dev/users/greg@aeolus.earth/ckdmip/evaluation2"
const DEST = "/shared/home/greg/data/ckdmip/evaluation2"
const PROJECT_ROOT = "/shared/home/greg/Projects/AnalyticBandRadiation-platform"
const SPECIES = ["h2o_present", "o3_present", "co2_present", "ch4_present",
                 "n2o_present", "n2_constant", "o2_constant"]
const CHUNKS = ["1-10", "11-20", "21-30", "31-40", "41-50"]

const GC_RESULTS_JSON = validation_results_path("gate4_g2c_eval2_fetch_checkpoint.json")
const GC_RESULTS_MD = validation_results_path("gate4_g2c_eval2_fetch_checkpoint.md")
const GC_SBATCH = validation_results_path("gate4_g2c_eval2_fetch.sbatch")

incl_args(band) = join(["--include \"ckdmip_evaluation2_$(band)_spectra_$(sp)_*.h5\""
                        for sp in SPECIES], " ")

const SBATCH_TEXT = """
#!/bin/bash
#SBATCH --job-name=g4-g2c-eval2-fetch
#SBATCH --output=/shared/home/greg/data/ckdmip-logs/g4-g2c-%j.log
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16G
#SBATCH --partition=cpu-large

# Gate-4 G2c: evaluation2 spectra fetch ONLY (no LBL, no optimizer, no
# create/scale/find stages). Generated by gate4_g2c_eval2_fetch_checkpoint.jl.
set -euo pipefail
if [ -z "\${SLURM_JOB_ID:-}" ]; then
    echo "REFUSED: head-node execution is not permitted; submit via sbatch." >&2
    exit 64
fi

DEST=$DEST

echo "=== G2c stage 0: preflight ==="
command -v aws >/dev/null || { echo "MISSING aws CLI on compute node" >&2; exit 65; }
aws sts get-caller-identity >/dev/null || { echo "REFUSED: AWS auth unavailable (SSO expired?)" >&2; exit 66; }
avail_kb=\$(df --output=avail /shared | tail -1)
[ "\$avail_kb" -gt 419430400 ] || { echo "REFUSED: <400GB free on /shared" >&2; exit 67; }
# uid-quota headroom guard (job 4440 lesson: df cannot see Lustre uid
# quotas). Audited selected-source total: 329,989,234,896 B; margin 40 GiB.
source $PROJECT_ROOT/validation/gate4_quota_guard.sh
quota_guard "\$DEST" "$PROJECT_ROOT/validation/gate4_eval2_selected_manifest.tsv" \$((40*1024*1024*1024)) || { echo "REFUSED: quota headroom insufficient" >&2; exit 67; }
mkdir -p "\$DEST/lw_spectra" "\$DEST/sw_spectra"

echo "=== G2c stage 1: sync LW spectra (7 species x 5 chunks, ~220 GB) ==="
aws s3 sync "$S3_BASE/lw_spectra/" "\$DEST/lw_spectra/" \\
  --exclude "*" $(incl_args("lw")) --no-progress
echo "=== G2c stage 2: sync SW spectra (7 species x 5 chunks, ~110 GB) ==="
aws s3 sync "$S3_BASE/sw_spectra/" "\$DEST/sw_spectra/" \\
  --exclude "*" $(incl_args("sw")) --no-progress

echo "=== G2c stage 3: exact-70 completeness + size verification ==="
MISSING=0
for band in lw sw; do
    for sp in $(join(SPECIES, " ")); do
        for chunk in $(join(CHUNKS, " ")); do
            f="\$DEST/\${band}_spectra/ckdmip_evaluation2_\${band}_spectra_\${sp}_\${chunk}.h5"
            [ -s "\$f" ] || { echo "MISSING \$f" >&2; MISSING=1; }
        done
    done
done
[ "\$MISSING" = 0 ] || { echo "REFUSED: completeness gate failed" >&2; exit 71; }
# re-run sync as identity check: any transfer line means a size/mtime
# mismatch survived stage 1-2 (sync copies only on mismatch, so a clean
# second pass proves local == S3 for every included file)
RESYNC=\$(aws s3 sync "$S3_BASE/lw_spectra/" "\$DEST/lw_spectra/" --exclude "*" $(incl_args("lw")) --no-progress 2>&1 | head -5)
RESYNC2=\$(aws s3 sync "$S3_BASE/sw_spectra/" "\$DEST/sw_spectra/" --exclude "*" $(incl_args("sw")) --no-progress 2>&1 | head -5)
[ -z "\$RESYNC\$RESYNC2" ] || { echo "REFUSED: resync transferred data (mismatch): \$RESYNC \$RESYNC2" >&2; exit 72; }

echo "=== G2c outputs ==="
echo "lw files: \$(ls "\$DEST/lw_spectra/" | wc -l)  bytes: \$(du -sb "\$DEST/lw_spectra" | cut -f1)"
echo "sw files: \$(ls "\$DEST/sw_spectra/" | wc -l)  bytes: \$(du -sb "\$DEST/sw_spectra" | cut -f1)"
echo "=== G2c done rc=\$? \$(date -u +%FT%TZ) ==="
"""

function main()
    fails = String[]
    gates = Dict{String, String}()

    ident_ok = try
        occursin("aeolus", read(`aws sts get-caller-identity`, String))
    catch; false end
    gates["aws_auth_at_generation"] = ident_ok ? "passed" : "failed"
    ident_ok || push!(fails, "AWS auth unavailable at checkpoint generation")

    open(GC_SBATCH, "w") do io
        write(io, SBATCH_TEXT)
    end
    gates["sbatch_written_not_submitted"] = "passed"
    self_src = read(@__FILE__, String)
    sb_tok = "sb" * "atch "
    isempty(collect(eachmatch(Regex("run\\(`" * sb_tok), self_src))) ||
        (gates["sbatch_written_not_submitted"] = "failed";
         push!(fails, "sbatch invocation found in checkpoint unit"))
    gates["headnode_refusal_guard"] =
        occursin("REFUSED: head-node execution", SBATCH_TEXT) ? "passed" : "failed"
    exec_lines = join([l for l in split(SBATCH_TEXT, '\n')
                       if !occursin(r"^\s*#", l)], '\n')
    gates["fetch_only"] =
        occursin("aws s3 sync", exec_lines) &&
        !occursin("optimize_lut", exec_lines) &&
        !occursin("create_lut", exec_lines) &&
        !occursin("scale_lut", exec_lines) &&
        !occursin("find_g_points", exec_lines) &&
        !occursin("lbl_evaluation", exec_lines) &&
        !occursin("ckdmip_lw", exec_lines) &&
        !occursin("ckdmip_sw", exec_lines) ? "passed" : "failed"
    gates["fetch_only"] == "passed" ||
        push!(fails, "forbidden stage invocation in executable lines")
    gates["species_scope_correct"] =
        length(SPECIES) == 7 && !occursin("cfc", join(SPECIES)) &&
        occursin("n2_constant", join(SPECIES)) ? "passed" : "failed"
    gates["exact70_gate"] =
        occursin("completeness gate failed", SBATCH_TEXT) &&
        occursin("resync transferred data", SBATCH_TEXT) ? "passed" : "failed"
    gates["disk_guard"] = occursin("400GB free", SBATCH_TEXT) ? "passed" : "failed"
    gates["quota_aware_preflight"] =
        occursin("gate4_quota_guard.sh", SBATCH_TEXT) &&
        occursin("gate4_eval2_selected_manifest.tsv", SBATCH_TEXT) ? "passed" : "failed"
    # audited manifest integrity (checkpoint-side mirror of the guard's check)
    manifest_path = joinpath(PROJECT_ROOT, "validation/gate4_eval2_selected_manifest.tsv")
    mrows = [split(l, '\t') for l in eachline(manifest_path)
             if !startswith(l, '#') && !isempty(strip(l))]
    mnames = [r[1] for r in mrows]
    msizes = Dict(r[1] => parse(Int, r[2]) for r in mrows)
    gates["manifest_integrity"] =
        (length(mrows) == 70 && length(unique(mnames)) == 70 &&
         sum(values(msizes)) == 329989234896) ? "passed" : "failed"
    gates["manifest_integrity"] == "passed" ||
        push!(fails, "manifest count/uniqueness/sum drift")

    # --- quota-guard fixture tests (same sourced logic the sbatch runs) ---
    guard = joinpath(PROJECT_ROOT, "validation/gate4_quota_guard.sh")
    run_guard(pathdir, destdir; mani=manifest_path) = success(pipeline(
        `/usr/bin/env PATH=$pathdir /bin/bash -c "source $guard; quota_guard $destdir $mani 42949672960"`,
        stdout=devnull, stderr=devnull))
    fx = mktempdir()
    bin_min = joinpath(fx, "bin_min"); mkpath(bin_min)   # awk/stat/id, NO lfs
    for t in ("awk", "stat", "id", "grep", "sed", "sort", "wc")
        tp = Sys.which(t); tp === nothing || symlink(tp, joinpath(bin_min, t))
    end
    mkfix(name, rowscript) = begin
        d = joinpath(fx, name); mkpath(d)
        for t in readdir(bin_min); symlink(joinpath(bin_min, t), joinpath(d, t)); end
        lf = joinpath(d, "lfs")
        write(lf, "#!/bin/bash\n" * rowscript * "\n"); chmod(lf, 0o755)
        d
    end
    emptydest = joinpath(fx, "dest"); mkpath(joinpath(emptydest, "lw_spectra")); mkpath(joinpath(emptydest, "sw_spectra"))
    # (a) live-fixture: today's actual lfs row baked into a stub; expected
    #     verdict computed independently in Julia from the same row
    live_row = try
        uid = strip(read(`id -u`, String))
        strip(split(read(`lfs quota -q -u $uid /shared`, String), "\n")[1])
    catch; "" end
    tests = Dict{String, Bool}()
    if !isempty(live_row)
        d = mkfix("live", "echo \"$live_row\"")
        used_kib = parse(Int, replace(split(live_row)[2], "*" => ""))
        hard_kib = parse(Int, split(live_row)[4])
        headroom = max(hard_kib - used_kib, 0) * 1024
        expect_pass = hard_kib > 0 && headroom >= 329989234896 + 42949672960
        tests["live_fixture_matches_independent_computation"] =
            run_guard(d, emptydest) == expect_pass
    else
        tests["live_fixture_matches_independent_computation"] = false
    end
    # (b) sufficient quota -> pass
    d = mkfix("sufficient", "echo \"/shared 100 0 2000000000 - 1 0 0 -\"")
    tests["sufficient_quota_passes"] = run_guard(d, emptydest) == true
    # (c) missing lfs -> refusal
    tests["missing_lfs_refuses"] = run_guard(bin_min, emptydest) == false
    # (d) malformed output -> refusal
    d = mkfix("malformed", "echo \"/shared abc* def ghi -\"")
    tests["malformed_refuses"] = run_guard(d, emptydest) == false
    # (e) hard limit 0/unlimited -> deliberate refusal
    d = mkfix("zerohard", "echo \"/shared 12345 0 0 -\"")
    tests["zero_hard_limit_refuses"] = run_guard(d, emptydest) == false
    # (f) finalized-file subtraction changes the VERDICT, exact-size only:
    # sparse file of EXACTLY the manifest size for lw h2o_present_1-10;
    # stub headroom 370,000,000,000 B = (361328225-100) KiB * 1024 sits
    # strictly between need(empty) = total+margin = 372,938,907,856 B
    # (-> REFUSE) and need(with exact file) = 372,938,907,856 -
    # manifest_size (-> PASS).
    fsz = msizes["ckdmip_evaluation2_lw_spectra_h2o_present_1-10.h5"]
    @assert 372938907856 - fsz < 370000000000 < 372938907856
    d2 = joinpath(fx, "dest2"); mkpath(joinpath(d2, "lw_spectra")); mkpath(joinpath(d2, "sw_spectra"))
    open(joinpath(d2, "lw_spectra/ckdmip_evaluation2_lw_spectra_h2o_present_1-10.h5"), "w") do io
        seek(io, fsz - 1); write(io, UInt8(0))
    end
    d = mkfix("between", "echo \"/shared 100 0 361328225 - 1 0 0 -\"")
    tests["subtraction_refuses_on_empty_dest"] = run_guard(d, emptydest) == false
    tests["subtraction_passes_with_exact_size_file"] = run_guard(d, d2) == true
    # (g) present-but-WRONG-size file must REFUSE even under huge quota
    # (10 GiB bogus at an expected name; sync would replace it)
    d3 = joinpath(fx, "dest3"); mkpath(joinpath(d3, "lw_spectra")); mkpath(joinpath(d3, "sw_spectra"))
    open(joinpath(d3, "lw_spectra/ckdmip_evaluation2_lw_spectra_h2o_present_1-10.h5"), "w") do io
        seek(io, 10 * 1024^3 - 1); write(io, UInt8(0))
    end
    d = mkfix("hugequota", "echo \"/shared 100 0 2000000000 - 1 0 0 -\"")
    tests["wrong_size_file_refuses"] = run_guard(d, d3) == false
    gates["quota_guard_fixture_tests"] =
        all(values(tests)) ? "passed" : "failed"
    all(values(tests)) ||
        push!(fails, "quota-guard fixture failures: " *
                     join([k for (k, v) in tests if !v], ", "))

    status = isempty(fails) && all(v -> v == "passed", values(gates)) ?
        "g2c_checkpoint_ready" : "g2c_checkpoint_failed"
    branch = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --abbrev-ref HEAD`, String)) catch; "unknown" end
    ghead = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --short HEAD`, String)) catch; "unknown" end

    result = Dict(
        "case" => "gate4_g2c_eval2_fetch_checkpoint",
        "data_mode" => "dry_run_script_generation_only",
        "status" => status,
        "timestamp_utc" => string(Dates.now(Dates.UTC)),
        "gates" => gates, "failures" => fails,
        "authorization" => "Greg: 'go with option A' (2026-07-30) + SSO " *
            "re-auth and 'keep going' (2026-08-12)",
        "sbatch_path" => GC_SBATCH,
        "source" => "$S3_BASE (byte-verified ECPDS archive per " *
                    "archive_to_s3.log 2026-05-27; ECPDS live as fallback)",
        "quota_guard_fixture_verdicts" => tests,
        "scope" => Dict(
            "species" => SPECIES, "chunks" => CHUNKS,
            "expected_files" => 70,
            "expected_bytes_approx" => "LW 219.6 GB + SW 110.4 GB = ~330 GB",
            "skipped" => "cfc11/cfc12 (rel-415 never reads them); rayleigh " *
                "(not on S3/ECPDS -- generated in the follow-on flux unit); " *
                "ssi (evaluation1 local copy reused)"),
        "followon" => "G2d: rayleigh generation (make_rayleigh_evaluation.sh " *
            "recipe, ckdmip_tool --rayleigh on the 5 eval2 h2o_present SW " *
            "chunks) + rel-415 LBL runs (LW plain, SW rgb-banded) -> 2 flux " *
            "files -> ledger -> G3",
        "provenance" => Dict("branch" => branch, "generated_from_head" => ghead,
            "provenance_note" => "artifact generated from the working tree " *
                "before its own commit"),
        "disclaimer" => "script generation only; nothing submitted by this " *
                        "unit; fetch+verify only; no LBL, optimizer, " *
                        "objective, floor, or recovery computation.",
    )
    mkpath(dirname(GC_RESULTS_JSON))
    open(GC_RESULTS_JSON, "w") do io
        JSON.print(io, result, 2)
    end
    open(GC_RESULTS_MD, "w") do io
        println(io, "# Gate-4 G2c evaluation2 spectra fetch checkpoint\n")
        println(io, "Status: **$status**\n")
        println(io, result["disclaimer"], "\n")
        println(io, "Authorization: ", result["authorization"], "\n")
        println(io, "| Gate | Result |")
        println(io, "|---|---|")
        for k in sort(collect(keys(gates)))
            println(io, "| $k | $(gates[k]) |")
        end
        println(io, "\nSource: ", result["source"])
        println(io, "\nScope: 7 species x 5 chunks x 2 bands = 70 files, " *
                    "~330 GB; cfc/rayleigh/ssi excluded (see JSON).")
        println(io, "\nFollow-on: ", result["followon"])
        println(io, "\nProvenance: branch `$branch`, generated_from_head " *
                    "`$ghead` (pre-own-commit).")
        isempty(fails) || (println(io, "\n## Failures\n");
                           foreach(f -> println(io, "- ", f), fails))
    end
    println("gate4_g2c_eval2_fetch_checkpoint: $status")
    for k in sort(collect(keys(gates)))
        println("  $k: $(gates[k])")
    end
    isempty(fails) || foreach(f -> println("  FAIL: $f"), fails)
    return status == "g2c_checkpoint_ready" ? 0 : 1
end

exit(main())
