# Gate-4 G2d EVALUATION2 REL-415 FLUX checkpoint (dry-run generation; NO
# submission). Final Option A data unit: produce the two TRAINING_BOTH=yes
# training flux files from the G2c-fetched evaluation2 spectra.
#
# PATH CONTRACT (monitor-specified, two-phase): GENERATE in the quarantined
# work-eval2 tree, exact-2/hash gate there, then INSTALL only the verified
# outputs into the EXISTING executor trees (inits/gpoints untouched):
#   $G4WORK/work/lw_lbl_fluxes/ckdmip_evaluation2_lw_fluxes_rel-415.h5
#   $G4WORK/work/sw_lbl_fluxes/ckdmip_evaluation2_sw_fluxes-rgb_rel-415.h5
#   + $G4WORK/work-v14/sw_lbl_fluxes/<same SW file> (dual-install: the SW
#     G3 executor may run with WORK_DIR=work-v14 where the accepted scaled
#     init and ecckd-1.4 prefix live; disjoint filenames, cmp-verified)
# G3 keeps WORK_DIR=work (LW) / work-v14 (SW): no repointing, no symlinks.
# Resolution is via the WORK_*_LBL_FLUX_DIR half of append_path (never
# EVALUATION_*_FLUXES_DIR, which optimize_lut does not append).
#
# Mechanism facts (verified in the pinned scripts):
#   run_sw_lbl_evaluation.sh: SET=evaluation1 (INDIR=${CKDMIP_DATA_DIR}/
#     ${SET}/sw_spectra, OUTPREFIX=ckdmip_${SET}_sw_${BANDCODE}) -> one sed
#     SET=evaluation2 retargets both; BANDCODE/9-band edits as G2a/G2b.
#   run_lw_lbl_evaluation.sh: SET=evaluation1 but INDIR=$TRAINING_LW_
#     SPECTRA_DIR -> needs SET sed PLUS an explicit INDIR sed; TRAINING_CODE
#     stays evaluation1 so TRAINING_SW_SSI keeps resolving to the local
#     evaluation1 ckdmip_ssi.h5.
#   OUTDIR=$WORK_*_LBL_FLUX_DIR; WORK_DIR=work-eval2 in the testcopy config
#     -> LBL outputs land in the QUARANTINE tree; stage 6 then installs the
#     exact-2/hash-gated files into the executor trees per the contract.
#   SW rel-415 additionally reads ckdmip_evaluation2_sw_spectra_rayleigh_
#     present_<chunk>.h5 -- NOT published upstream for eval2 at all (S3 and
#     ECPDS both lack it); generated in-job by the upstream author's own
#     recipe (ckdmip-1.0/work/sw/make_rayleigh_evaluation.sh: ckdmip_tool
#     --grid <eval2 h2o_present chunk> --rayleigh), 5 chunks ~4.5 GB,
#     written into the fetched eval2 tree mirroring evaluation1's layout,
#     sha256s echoed for provenance.
#
# NO optimizer, create_lut, scale_lut, or find_g_points executable lines.

include(joinpath(@__DIR__, "validation_results.jl"))

using Dates
import JSON

const ECCKD_SRC = "/shared/home/greg/.julia/artifacts/" *
    "7b210aef53e908cfe3c709945f0763c37ca82aaa/" *
    "ecckd-6115f9b8e29a55cb0f48916857bdc77fec41badd"
const G4WORK = "/shared/home/greg/ecckd-derived-flux-work/g4-init-generation"
const CKDMIP_ROOT = "/shared/home/greg/data/ckdmip"
const CKDMIP_BIN_ROOT = "/shared/home/greg/build/ckdmip-1.0"
const PROJECT_ROOT = "/shared/home/greg/Projects/AnalyticBandRadiation-platform"
const SPECIES = ["h2o_present", "o3_present", "co2_present", "ch4_present",
                 "n2o_present", "n2_constant", "o2_constant"]
const CHUNKS = ["1-10", "11-20", "21-30", "31-40", "41-50"]
const LW_OUT = "$G4WORK/work-eval2/lw_lbl_fluxes/ckdmip_evaluation2_lw_fluxes_rel-415.h5"
const SW_OUT = "$G4WORK/work-eval2/sw_lbl_fluxes/ckdmip_evaluation2_sw_fluxes-rgb_rel-415.h5"
const LW_INSTALL = "$G4WORK/work/lw_lbl_fluxes/ckdmip_evaluation2_lw_fluxes_rel-415.h5"
const SW_INSTALL = "$G4WORK/work/sw_lbl_fluxes/ckdmip_evaluation2_sw_fluxes-rgb_rel-415.h5"
const SW_INSTALL_V14 = "$G4WORK/work-v14/sw_lbl_fluxes/ckdmip_evaluation2_sw_fluxes-rgb_rel-415.h5"

const GD_RESULTS_JSON = validation_results_path("gate4_g2d_eval2_rel415_flux_checkpoint.json")
const GD_RESULTS_MD = validation_results_path("gate4_g2d_eval2_rel415_flux_checkpoint.md")
const GD_SBATCH = validation_results_path("gate4_g2d_eval2_rel415_flux.sbatch")

const SBATCH_TEXT = """
#!/bin/bash
#SBATCH --job-name=g4-g2d-eval2-rel415
#SBATCH --output=/shared/home/greg/data/ckdmip-logs/g4-g2d-%j.log
#SBATCH --time=08:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=60G
#SBATCH --partition=cpu-large

# Gate-4 G2d: evaluation2 rel-415 LBL fluxes ONLY (rayleigh generation +
# two LBL runs; no optimizer, no create/scale/find stages). Generated by
# gate4_g2d_eval2_rel415_flux_checkpoint.jl.
set -euo pipefail
if [ -z "\${SLURM_JOB_ID:-}" ]; then
    echo "REFUSED: head-node execution is not permitted; submit via sbatch." >&2
    exit 64
fi

G4WORK=$G4WORK
TESTCOPY="\$G4WORK/testcopy-eval2"
WORKEVAL2="\$G4WORK/work-eval2"
E2=$CKDMIP_ROOT/evaluation2

echo "=== G2d stage 0: preflight ==="
for b in ckdmip_lw ckdmip_sw ckdmip_tool; do
    test -x "$CKDMIP_BIN_ROOT/bin/\$b" || { echo "MISSING binary \$b" >&2; exit 65; }
done
test -s "$CKDMIP_ROOT/evaluation1/sw_spectra/ckdmip_ssi.h5" || { echo "MISSING evaluation1 SSI" >&2; exit 65; }
for band in lw sw; do
    for sp in $(join(SPECIES, " ")); do
        for chunk in $(join(CHUNKS, " ")); do
            test -s "\$E2/\${band}_spectra/ckdmip_evaluation2_\${band}_spectra_\${sp}_\${chunk}.h5" || { echo "MISSING eval2 spectra: \$band \$sp \$chunk (G2c incomplete?)" >&2; exit 65; }
        done
    done
done
test ! -e "$LW_OUT" || { echo "REFUSED: stale LW output exists" >&2; exit 70; }
test ! -e "$SW_OUT" || { echo "REFUSED: stale SW output exists" >&2; exit 70; }
test ! -e "$LW_INSTALL" || { echo "REFUSED: stale LW install exists" >&2; exit 70; }
test ! -e "$SW_INSTALL" || { echo "REFUSED: stale SW install exists" >&2; exit 70; }
test ! -e "$SW_INSTALL_V14" || { echo "REFUSED: stale SW v14 install exists" >&2; exit 70; }
# partial-RAW guard (G2b lesson): wipe any prior quarantine work tree
if [ -e "\$WORKEVAL2" ]; then
    echo "clearing pre-existing work-eval2 (partial-RAW guard)"
    find "\$WORKEVAL2" -name 'RAW_*.h5' -printf '  partial: %p (%s B)\\n' 2>/dev/null || true
    rm -rf "\$WORKEVAL2"
fi

echo "=== G2d stage 1: eval2 SW rayleigh (upstream recipe; 5 chunks) ==="
for chunk in $(join(CHUNKS, " ")); do
    R="\$E2/sw_spectra/ckdmip_evaluation2_sw_spectra_rayleigh_present_\$chunk.h5"
    if [ ! -s "\$R" ]; then
        $CKDMIP_BIN_ROOT/bin/ckdmip_tool --grid "\$E2/sw_spectra/ckdmip_evaluation2_sw_spectra_h2o_present_\$chunk.h5" --rayleigh -o "\$R"
    fi
    test -s "\$R" || { echo "MISSING rayleigh after generation: \$chunk" >&2; exit 66; }
done
echo "rayleigh provenance:"
sha256sum "\$E2/sw_spectra/"ckdmip_evaluation2_sw_spectra_rayleigh_present_*.h5

echo "=== G2d stage 2: isolated testcopy-eval2 from the PINNED artifact ==="
rm -rf "\$TESTCOPY"
cp -r "$ECCKD_SRC/test" "\$TESTCOPY"
cd "\$TESTCOPY"
sed 's/@PACKAGE_VERSION@/1.2/g' version.h.in > version.h
sed -i \\
  -e 's|^CKDMIP_DIR=.*|CKDMIP_DIR=$CKDMIP_BIN_ROOT|' \\
  -e 's|^CKDMIP_DATA_DIR=.*|CKDMIP_DATA_DIR=$CKDMIP_ROOT|' \\
  -e 's|^WORK_DIR=.*|WORK_DIR=\$WORKEVAL2|' \\
  -e 's|^BINDIR=.*|BINDIR=/shared/home/greg/ecckd-derived-flux-work/ecckd/src/ecckd|' \\
  config.h
grep -E "^(CKDMIP_DIR|CKDMIP_DATA_DIR|WORK_DIR|BINDIR)=" config.h
# LW retarget: SET + explicit INDIR (INDIR is TRAINING-wired in the pristine
# script) + rel-415-only SCENARIOS
sed -i \\
  -e 's|^SET=evaluation1\$|SET=evaluation2|' \\
  -e 's|^INDIR=\$TRAINING_LW_SPECTRA_DIR\$|INDIR=\${CKDMIP_DATA_DIR}/evaluation2/lw_spectra|' \\
  run_lw_lbl_evaluation.sh
sed -i -E "0,/^SCENARIOS=\\"[^\\"]*\\"/s||SCENARIOS=\\"rel-415\\"|" run_lw_lbl_evaluation.sh
grep -E "^SET=|^INDIR=|^SCENARIOS=" run_lw_lbl_evaluation.sh
grep -qE "^SET=evaluation2\$" run_lw_lbl_evaluation.sh || { echo "BAD edit: LW SET" >&2; exit 68; }
grep -qE "^SCENARIOS=\\"rel-415\\"\$" run_lw_lbl_evaluation.sh || { echo "BAD edit: LW SCENARIOS" >&2; exit 68; }
# SW retarget: SET (fixes INDIR+OUTPREFIX) + rel-415 + rgb band edits (as G2a/G2b)
sed -i \\
  -e 's|^SET=evaluation1\$|SET=evaluation2|' \\
  -e 's|^BANDCODE=fluxes\$|BANDCODE=fluxes-rgb|' \\
  -e 's|^band_wavenumber1(1:13)|!band_wavenumber1(1:13)|' \\
  -e 's|^band_wavenumber2(1:13)|!band_wavenumber2(1:13)|' \\
  -e 's|^!band_wavenumber1(1:9) = 250, 2500, 4000, 8000, 14300, 16650, 20000, 25000, 31750,|band_wavenumber1(1:9) = 250, 2500, 4000, 8000, 14300, 16650, 20000, 25000, 31750,|' \\
  -e 's|^!band_wavenumber2(1:9) = 2500, 4000, 8000, 14300, 16650, 20000, 25000, 31750, 50000,|band_wavenumber2(1:9) = 2500, 4000, 8000, 14300, 16650, 20000, 25000, 31750, 50000,|' \\
  run_sw_lbl_evaluation.sh
sed -i -E "0,/^SCENARIOS=\\"[^\\"]*\\"/s||SCENARIOS=\\"rel-415\\"|" run_sw_lbl_evaluation.sh
grep -E "^SET=|^SCENARIOS=|^BANDCODE=|^band_wavenumber" run_sw_lbl_evaluation.sh
grep -qE "^SET=evaluation2\$" run_sw_lbl_evaluation.sh || { echo "BAD edit: SW SET" >&2; exit 68; }
grep -qE "^BANDCODE=fluxes-rgb\$" run_sw_lbl_evaluation.sh || { echo "BAD edit: SW BANDCODE" >&2; exit 68; }
test \$(grep -cE "^band_wavenumber1" run_sw_lbl_evaluation.sh) -eq 1 || { echo "BAD edit: SW band grid" >&2; exit 68; }
# pipeline parity (both scripts): no nco module, quieter, Julia concat, reuse-skip
sed -i '/^module load nco\$/s/^/# /' run_lw_lbl_evaluation.sh run_sw_lbl_evaluation.sh
sed -i 's/iverbose = 3/iverbose = 1/g' run_lw_lbl_evaluation.sh run_sw_lbl_evaluation.sh
sed -i -E 's|ncrcat -O \\\$OUTFILES \\\$OUTFILE|julia --project=$PROJECT_ROOT/test $PROJECT_ROOT/validation/concat_ckdmip_flux_chunks.jl \$OUTFILES \$OUTFILE|' run_lw_lbl_evaluation.sh run_sw_lbl_evaluation.sh
sed -i '/OUTFILES="\$OUTFILES \$OUTFILE"/a\\
\\tif [ -s "\$OUTFILE" ]\\
\\tthen\\
\\t    echo "*** REUSING \$OUTFILE ***"\\
\\t    continue\\
\\tfi' run_lw_lbl_evaluation.sh run_sw_lbl_evaluation.sh

echo "=== G2d stage 3: LW rel-415 LBL evaluation ==="
bash run_lw_lbl_evaluation.sh
echo "=== G2d stage 4: SW rel-415 RGB LBL evaluation ==="
bash run_sw_lbl_evaluation.sh

echo "=== G2d stage 5: exact-2 completeness gate (quarantine) ==="
test -s "$LW_OUT" || { echo "MISSING LW output" >&2; exit 71; }
test -s "$SW_OUT" || { echo "MISSING SW output" >&2; exit 71; }

echo "=== G2d stage 6: install verified outputs into executor trees ==="
mkdir -p "$G4WORK/work/lw_lbl_fluxes" "$G4WORK/work/sw_lbl_fluxes" "$G4WORK/work-v14/sw_lbl_fluxes"
install -m 0644 "$LW_OUT" "$LW_INSTALL"
install -m 0644 "$SW_OUT" "$SW_INSTALL"
install -m 0644 "$SW_OUT" "$SW_INSTALL_V14"
cmp -s "$LW_OUT" "$LW_INSTALL" || { echo "INSTALL IDENTITY MISMATCH lw" >&2; exit 72; }
cmp -s "$SW_OUT" "$SW_INSTALL" || { echo "INSTALL IDENTITY MISMATCH sw" >&2; exit 72; }
cmp -s "$SW_OUT" "$SW_INSTALL_V14" || { echo "INSTALL IDENTITY MISMATCH sw-v14" >&2; exit 72; }

echo "=== G2d outputs ==="
sha256sum "$LW_OUT" "$SW_OUT" "$LW_INSTALL" "$SW_INSTALL" "$SW_INSTALL_V14"
echo "=== G2d done rc=\$? \$(date -u +%FT%TZ) ==="
"""

function main()
    fails = String[]
    gates = Dict{String, String}()

    # prerequisite: the 70 G2c spectra on disk (checkpoint-side mirror of
    # the in-job stage-0 guard)
    n_present = count(isfile(joinpath(CKDMIP_ROOT, "evaluation2",
                          "$(band)_spectra",
                          "ckdmip_evaluation2_$(band)_spectra_$(sp)_$(chunk).h5"))
                      for band in ("lw", "sw"), sp in SPECIES, chunk in CHUNKS)
    gates["g2c_spectra_prerequisite"] = n_present == 70 ? "passed" : "failed"
    n_present == 70 ||
        push!(fails, "eval2 spectra incomplete: $n_present/70 (G2c pending?)")

    open(GD_SBATCH, "w") do io
        write(io, SBATCH_TEXT)
    end
    gates["sbatch_written_not_submitted"] = "passed"
    self_src = read(@__FILE__, String)
    sb_tok = "sb" * "atch "
    isempty(collect(eachmatch(Regex("run\\(`" * sb_tok), self_src))) ||
        (gates["sbatch_written_not_submitted"] = "failed";
         push!(fails, "sbatch invocation found in checkpoint unit"))
    gates["headnode_refusal_guard"] =
        occursin("REFUSED: head-node execution", SBATCH_TEXT) ? "passed" : "failed"
    exec_lines = join([l for l in split(SBATCH_TEXT, '\n')
                       if !occursin(r"^\s*#", l)], '\n')
    gates["lbl_and_rayleigh_only"] =
        occursin("run_lw_lbl_evaluation.sh", exec_lines) &&
        occursin("run_sw_lbl_evaluation.sh", exec_lines) &&
        occursin("--rayleigh", exec_lines) &&
        !occursin("optimize_lut", exec_lines) &&
        !occursin("create_lut", exec_lines) &&
        !occursin("scale_lut", exec_lines) &&
        !occursin("find_g_points", exec_lines) ? "passed" : "failed"
    gates["lbl_and_rayleigh_only"] == "passed" ||
        push!(fails, "forbidden stage invocation in executable lines")
    gates["path_contract_honored"] =
        occursin(LW_OUT, SBATCH_TEXT) && occursin(SW_OUT, SBATCH_TEXT) &&
        occursin(LW_INSTALL, SBATCH_TEXT) &&
        occursin(SW_INSTALL, SBATCH_TEXT) &&
        occursin(SW_INSTALL_V14, SBATCH_TEXT) &&
        occursin("INSTALL IDENTITY MISMATCH", SBATCH_TEXT) &&
        occursin("WORK_DIR=\$WORKEVAL2", SBATCH_TEXT) ? "passed" : "failed"
    gates["lw_indir_retarget"] =
        occursin("INDIR=\${CKDMIP_DATA_DIR}/evaluation2/lw_spectra", SBATCH_TEXT) ?
        "passed" : "failed"
    gates["rgb_band_grid_14300_variant"] =
        occursin("14300, 16650, 20000, 25000, 31750", SBATCH_TEXT) ? "passed" : "failed"
    gates["stale_output_refusal_and_partial_raw_guard"] =
        occursin("stale LW output", SBATCH_TEXT) &&
        occursin("partial-RAW guard", SBATCH_TEXT) ? "passed" : "failed"
    gates["pipeline_parity"] =
        occursin("concat_ckdmip_flux_chunks.jl", SBATCH_TEXT) &&
        occursin("REUSING", SBATCH_TEXT) ? "passed" : "failed"
    gates["ssi_stays_evaluation1"] =
        !occursin("TRAINING_CODE", SBATCH_TEXT) ? "passed" : "failed"

    status = if !isempty(fails) && gates["g2c_spectra_prerequisite"] == "failed" &&
                all(k -> k == "g2c_spectra_prerequisite" || gates[k] == "passed",
                    keys(gates)) && length(fails) == 1
        "g2d_checkpoint_waiting_for_g2c"
    elseif isempty(fails) && all(v -> v == "passed", values(gates))
        "g2d_checkpoint_ready"
    else
        "g2d_checkpoint_failed"
    end
    branch = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --abbrev-ref HEAD`, String)) catch; "unknown" end
    ghead = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --short HEAD`, String)) catch; "unknown" end

    result = Dict(
        "case" => "gate4_g2d_eval2_rel415_flux_checkpoint",
        "data_mode" => "dry_run_script_generation_only",
        "status" => status,
        "timestamp_utc" => string(Dates.now(Dates.UTC)),
        "gates" => gates, "failures" => fails,
        "sbatch_path" => GD_SBATCH,
        "path_contract" => Dict(
            "generate_lw" => LW_OUT, "generate_sw" => SW_OUT,
            "install_lw" => LW_INSTALL, "install_sw" => SW_INSTALL,
            "install_sw_v14" => SW_INSTALL_V14,
            "rationale" => "monitor-specified two-phase: generate in " *
                "quarantined work-eval2, exact-2/hash gate, install only " *
                "verified outputs into the EXISTING executor trees so G3 " *
                "keeps WORK_DIR=work (LW) with inits/gpoints untouched; " *
                "optimizer resolves via append_path TRAINING_*_FLUXES_DIR:" *
                "WORK_*_LBL_FLUX_DIR (EVALUATION_*_FLUXES_DIR never " *
                "appended); SW dual-installed into work-v14/sw_lbl_fluxes " *
                "too because the SW executor may run WORK_DIR=work-v14 " *
                "(accepted scaled init + ecckd-1.4 prefix live there) -- " *
                "final SW wiring decided at the G3 spec review"),
        "rayleigh_note" => "eval2 SW rayleigh is not published anywhere " *
            "(S3 archive and ECPDS both lack it); generated in-job by the " *
            "upstream author's make_rayleigh_evaluation.sh recipe into the " *
            "fetched eval2 tree, mirroring evaluation1's official layout; " *
            "sha256s echoed in the job log",
        "eval2_spectra_present" => "$n_present/70",
        "provenance" => Dict("branch" => branch, "generated_from_head" => ghead,
            "provenance_note" => "artifact generated from the working tree " *
                "before its own commit"),
        "disclaimer" => "script generation only; nothing submitted by this " *
                        "unit; rayleigh + LBL evaluation only; no optimizer, " *
                        "objective, floor, or recovery computation.",
    )
    mkpath(dirname(GD_RESULTS_JSON))
    open(GD_RESULTS_JSON, "w") do io
        JSON.print(io, result, 2)
    end
    open(GD_RESULTS_MD, "w") do io
        println(io, "# Gate-4 G2d evaluation2 rel-415 flux checkpoint\n")
        println(io, "Status: **$status**\n")
        println(io, result["disclaimer"], "\n")
        println(io, "| Gate | Result |")
        println(io, "|---|---|")
        for k in sort(collect(keys(gates)))
            println(io, "| $k | $(gates[k]) |")
        end
        println(io, "\nPath contract (two-phase): generate in work-eval2, " *
                    "install to `$(LW_INSTALL)`, `$(SW_INSTALL)`, and " *
                    "`$(SW_INSTALL_V14)` (see JSON rationale).")
        println(io, "\nRayleigh: ", result["rayleigh_note"])
        println(io, "\neval2 spectra present at generation: $n_present/70")
        println(io, "\nProvenance: branch `$branch`, generated_from_head " *
                    "`$ghead` (pre-own-commit).")
        isempty(fails) || (println(io, "\n## Failures\n");
                           foreach(f -> println(io, "- ", f), fails))
    end
    println("gate4_g2d_eval2_rel415_flux_checkpoint: $status")
    for k in sort(collect(keys(gates)))
        println("  $k: $(gates[k])")
    end
    isempty(fails) || foreach(f -> println("  FAIL: $f"), fails)
    return status in ("g2d_checkpoint_ready", "g2d_checkpoint_waiting_for_g2c") ? 0 : 1
end

exit(main())
