# Gate-4 G2c EVALUATION2 SPECTRA FETCH checkpoint (dry-run generation; NO
# submission). Option A data gate: faithful TRAINING_BOTH=yes recovery needs
# ckdmip_evaluation2_{lw,sw}_fluxes_rel-415 flux files, generated from the
# evaluation2 LBL spectra. This unit fetches ONLY the spectra a rel-415 run
# reads (recon-verified): 7 species x 5 chunks per band = 70 files, ~330 GB
# (LW 219.6 GB + SW 110.4 GB). cfc11/cfc12 are skipped (rel-415 RELATIVE
# branch never reads them); SW rayleigh is NOT on S3/ECPDS and is generated
# in the follow-on flux unit; SSI reuses evaluation1's local copy.
#
# Source: s3://aeolus-dev/users/greg@aeolus.earth/ckdmip/evaluation2/
# (byte-verified archive of the ECPDS originals per archive_to_s3.log
# 2026-05-27; ECPDS itself confirmed live as fallback). Greg re-authed SSO
# and said "keep going" (2026-08-12). The fetch is manifest-driven per
# object: exact-size finals are h5-verified then skipped; an interrupted
# .part RESUMES via ECPDS Range requests (wget --continue), while the S3
# path cannot resume and restarts that object from 0; a wrong-size FINAL
# refuses (never overwrite). A flock under DEST serializes publishers.
# Source selection is autonomous: authenticated S3 preferred, exact
# ECPDS fallback otherwise (HEAD-audited 70/70 by Codex, 2026-08-13),
# with mid-run S3->ECPDS failover; refuse only when both are down.
#
# NO optimizer, LBL, create/scale/find stages. Fetch + verify only.

include(joinpath(@__DIR__, "validation_results.jl"))

using Dates
import JSON

const S3_BASE = "s3://aeolus-dev/users/greg@aeolus.earth/ckdmip/evaluation2"
const ECPDS_BASE = "https://aux.ecmwf.int/ecpds/home/ckdmip"
# fixed probe object for source availability checks (monitor-verified
# 2026-08-13: ECPDS HEAD 200, Accept-Ranges: bytes, exact manifest size)
const PROBE_NAME = "ckdmip_evaluation2_lw_spectra_o3_present_1-10.h5"
const PROBE_BYTES = 8841345967
const DEST = "/shared/home/greg/data/ckdmip/evaluation2"
const PROJECT_ROOT = "/shared/home/greg/Projects/AnalyticBandRadiation-platform"
const SPECIES = ["h2o_present", "o3_present", "co2_present", "ch4_present",
                 "n2o_present", "n2_constant", "o2_constant"]
const CHUNKS = ["1-10", "11-20", "21-30", "31-40", "41-50"]

const GC_RESULTS_JSON = validation_results_path("gate4_g2c_eval2_fetch_checkpoint.json")
const GC_RESULTS_MD = validation_results_path("gate4_g2c_eval2_fetch_checkpoint.md")
const GC_SBATCH = validation_results_path("gate4_g2c_eval2_fetch.sbatch")

# standing reserve below the SOFT limit (2026-08-13 resume review:
# reserve is 50 GiB, soft is the primary ceiling, df is not consulted)
const RESERVE_BYTES = 50 * 1024^3   # 53,687,091,200

const SBATCH_TEXT = """
#!/bin/bash
#SBATCH --job-name=g4-g2c-eval2-fetch
#SBATCH --output=/shared/home/greg/data/ckdmip-logs/g4-g2c-%j.log
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16G
#SBATCH --partition=cpu-large

# Gate-4 G2c: evaluation2 spectra fetch ONLY (no LBL, no optimizer, no
# create/scale/find stages). Generated by gate4_g2c_eval2_fetch_checkpoint.jl.
# Manifest-driven per-object pipeline: skip exact-size finals; SOFT-quota
# recheck before each allocation and again before each publish; fetch to
# a hidden same-directory .part; exact-size + h5 open sanity; atomic mv.
# Restart behavior: an interrupted .part RESUMES via ECPDS Range requests
# (wget --continue); the S3 path cannot resume and restarts the object
# from 0. Exact-size finals are h5-verified then skipped. If S3 fails
# mid-run the job fails over to ECPDS (fresh .part re-stat + quota
# recheck first) and stays on ECPDS for the remaining objects.
set -euo pipefail
if [ -z "\${SLURM_JOB_ID:-}" ]; then
    echo "REFUSED: head-node execution is not permitted; submit via sbatch." >&2
    exit 64
fi

DEST=$DEST
MANIFEST=$PROJECT_ROOT/validation/gate4_eval2_selected_manifest.tsv
RESERVE=$RESERVE_BYTES  # 50 GiB standing reserve below the SOFT limit

echo "=== G2c stage 0: preflight ==="
command -v flock >/dev/null || { echo "MISSING flock on compute node" >&2; exit 65; }
if command -v h5ls >/dev/null; then H5CHECK=h5ls
elif python3 -c "import h5py" 2>/dev/null; then H5CHECK=py
else echo "REFUSED: no h5 sanity tool (need h5ls or python3+h5py)" >&2; exit 65; fi
echo "h5 sanity tool: \$H5CHECK"
h5_sanity() {
    if [ "\$H5CHECK" = h5ls ]; then h5ls "\$1" >/dev/null
    else python3 -c "import sys, h5py; h5py.File(sys.argv[1], 'r').close()" "\$1"; fi
}
# source selection: prefer authenticated S3; otherwise the exact ECPDS
# fallback (probe must return the pinned manifest size). Both verdicts
# are logged; refusal only when NEITHER source is available.
PROBE_NAME=$PROBE_NAME
PROBE_SIZE=\$(awk -F'\\t' -v n="\$PROBE_NAME" '\$1==n{print \$2; exit}' "\$MANIFEST")
# fail closed on probe-row drift: the manifest row must equal the
# hard-pinned probe size before any network verdict can count
[ "\$PROBE_SIZE" = "$PROBE_BYTES" ] || { echo "REFUSED: probe row missing/drifted in manifest (got '\$PROBE_SIZE', pinned $PROBE_BYTES)" >&2; exit 69; }
S3_OK=0; ECPDS_OK=0
if command -v aws >/dev/null && aws sts get-caller-identity >/dev/null 2>&1; then S3_OK=1; fi
if command -v wget >/dev/null && command -v curl >/dev/null; then
    # conditional assignment: a down ECPDS (curl failure under pipefail)
    # must leave ECPDS_OK=0, not kill the script -- S3 may still be up
    if HDRS=\$(curl -fsSI --max-time 60 "$ECPDS_BASE/lw_spectra/evaluation2/\$PROBE_NAME" 2>/dev/null | tr -d '\\r'); then
        CL=\$(echo "\$HDRS" | awk 'tolower(\$1)=="content-length:"{print \$2; exit}')
        AR=\$(echo "\$HDRS" | awk 'tolower(\$1)=="accept-ranges:"{print tolower(\$2); exit}')
        [ "\$CL" = "\$PROBE_SIZE" ] && [ "\$AR" = "bytes" ] && ECPDS_OK=1
    fi
fi
echo "source probes: s3_auth=\$S3_OK ecpds_exact=\$ECPDS_OK"
if [ "\$S3_OK" = 1 ]; then FETCHER=s3
elif [ "\$ECPDS_OK" = 1 ]; then FETCHER=ecpds
else echo "REFUSED: no source available (S3 auth failed AND ECPDS probe failed)" >&2; exit 66; fi
echo "fetcher: \$FETCHER"
# uid-quota headroom guard, SOFT limit primary (job 4440 lesson: df
# cannot see Lustre uid quotas, so df is not consulted at all). Audited
# selected-source total: 329,989,234,896 B; standing reserve 50 GiB.
source $PROJECT_ROOT/validation/gate4_quota_guard.sh
mkdir -p "\$DEST/lw_spectra" "\$DEST/sw_spectra"
# single-run lock: only one G2c publisher may run against DEST at a time
# (protects the skip/refuse/publish logic from concurrent-writer races)
exec 9>"\$DEST/.g2c.fetch.lock"
flock -n 9 || { echo "REFUSED: another G2c fetch holds the lock on \$DEST" >&2; exit 68; }
quota_guard "\$DEST" "\$MANIFEST" "\$RESERVE" || { echo "REFUSED: quota headroom insufficient" >&2; exit 67; }

echo "=== G2c stage 1: manifest-driven per-object fetch (concurrency 1) ==="
while IFS=\$'\\t' read -r name size _rest; do
    case "\$name" in ''|'#'*) continue;; esac
    case "\$name" in
        *_lw_spectra_*) sub=lw_spectra;;
        *_sw_spectra_*) sub=sw_spectra;;
        *) echo "REFUSED: manifest name without band dir: \$name" >&2; exit 70;;
    esac
    final="\$DEST/\$sub/\$name"
    part="\$DEST/\$sub/.g2c.part.\$name"
    if [ -e "\$final" ]; then
        sz=\$(stat -c %s "\$final")
        if [ "\$sz" = "\$size" ]; then
            # verify BEFORE skipping: a corrupt exact-size pre-existing
            # final must refuse now, not after all remaining transfer
            h5_sanity "\$final" || { echo "REFUSED: pre-existing exact-size final fails h5 sanity: \$final (will not overwrite; investigate)" >&2; exit 78; }
            echo "SKIP exact-size final (h5-verified): \$name"
            continue
        fi
        echo "REFUSED: wrong-size existing final \$final local=\$sz manifest=\$size (will not overwrite; investigate)" >&2
        exit 73
    fi
    # .part continuation: larger-than-manifest refuses; exact size skips
    # the network and goes straight to verification; smaller resumes
    pz=0
    if [ -e "\$part" ]; then
        pz=\$(stat -c %s "\$part")
        if [ "\$pz" -gt "\$size" ]; then
            echo "REFUSED: .part larger than manifest \$name part=\$pz manifest=\$size (corrupt; investigate)" >&2
            exit 77
        fi
    fi
    if [ "\$pz" -lt "\$size" ]; then
        # allocation recheck: only the bytes NOT already in the .part
        # (existing .part bytes already count in used)
        quota_object_recheck "\$((size - pz))" "\$RESERVE" || { echo "REFUSED: per-object quota recheck before \$name" >&2; exit 67; }
        if [ "\$FETCHER" = s3 ]; then
            [ "\$pz" = 0 ] || echo "note: aws s3 cp cannot resume; re-fetching \$name from 0"
            if ! aws s3 cp "$S3_BASE/\$sub/\$name" "\$part" --no-progress; then
                # input-independent progress: S3 auth can expire mid-run;
                # fall back to the startup-validated ECPDS source rather
                # than dying, resuming whatever .part bytes exist
                if [ "\$ECPDS_OK" = 1 ]; then
                    echo "note: S3 fetch failed mid-run; falling back to ECPDS resume for \$name"
                    # the failed AWS attempt may have truncated/rewritten
                    # the .part, and quota may have moved meanwhile:
                    # re-stat and run a FRESH allocation recheck first
                    new_pz=0; [ -e "\$part" ] && new_pz=\$(stat -c %s "\$part")
                    [ "\$new_pz" -le "\$size" ] || { echo "REFUSED: .part larger than manifest after failed S3 attempt \$name part=\$new_pz manifest=\$size" >&2; exit 77; }
                    quota_object_recheck "\$((size - new_pz))" "\$RESERVE" || { echo "REFUSED: quota recheck before ECPDS failover \$name" >&2; exit 67; }
                    wget --continue --tries=20 --timeout=60 --no-verbose -O "\$part" "$ECPDS_BASE/\$sub/evaluation2/\$name" || { echo "FETCH FAILED (S3 then ECPDS): \$name" >&2; exit 74; }
                    # stay on ECPDS for the remaining objects rather than
                    # repeatedly timing out against a dead S3 session
                    FETCHER=ecpds
                    echo "note: fetcher switched to ecpds for remaining objects"
                else
                    echo "FETCH FAILED: \$name (S3 failed; ECPDS was not validated at startup)" >&2; exit 74
                fi
            fi
        else
            wget --continue --tries=20 --timeout=60 --no-verbose -O "\$part" "$ECPDS_BASE/\$sub/evaluation2/\$name" || { echo "FETCH FAILED: \$name" >&2; exit 74; }
        fi
    else
        echo "part already complete: \$name (verifying without network)"
    fi
    psz=\$(stat -c %s "\$part")
    [ "\$psz" = "\$size" ] || { echo "REFUSED: part size mismatch \$name part=\$psz manifest=\$size" >&2; exit 75; }
    h5_sanity "\$part" || { echo "REFUSED: h5 open sanity failed: \$name" >&2; exit 76; }
    # publish recheck: .part bytes already count in used, so next=0 --
    # the rename allocates nothing; this verifies the reserve is intact
    quota_object_recheck 0 "\$RESERVE" || { echo "REFUSED: pre-publish quota recheck at \$name" >&2; exit 67; }
    mv "\$part" "\$final"
    echo "FINALIZED \$name (\$size B)"
done < "\$MANIFEST"

echo "=== G2c stage 2: final exact-70 verification (size + h5 sanity vs manifest) ==="
BAD=0
while IFS=\$'\\t' read -r name size _rest; do
    case "\$name" in ''|'#'*) continue;; esac
    case "\$name" in
        *_lw_spectra_*) sub=lw_spectra;;
        *_sw_spectra_*) sub=sw_spectra;;
        *) echo "REFUSED: manifest name without band dir: \$name" >&2; exit 70;;
    esac
    f="\$DEST/\$sub/\$name"
    if [ ! -e "\$f" ]; then echo "MISSING \$f" >&2; BAD=1; continue; fi
    sz=\$(stat -c %s "\$f")
    [ "\$sz" = "\$size" ] || { echo "SIZE MISMATCH \$f local=\$sz manifest=\$size" >&2; BAD=1; continue; }
    # h5 sanity on EVERY final, covering pre-existing finals this run
    # never touched, not only the ones published above
    h5_sanity "\$f" || { echo "H5 SANITY FAILED \$f" >&2; BAD=1; }
done < "\$MANIFEST"
[ "\$BAD" = 0 ] || { echo "REFUSED: final verification failed" >&2; exit 71; }

echo "=== G2c outputs ==="
echo "lw files: \$(ls "\$DEST/lw_spectra/" | wc -l)  bytes: \$(du -sb "\$DEST/lw_spectra" | cut -f1)"
echo "sw files: \$(ls "\$DEST/sw_spectra/" | wc -l)  bytes: \$(du -sb "\$DEST/sw_spectra" | cut -f1)"
echo "=== G2c done \$(date -u +%FT%TZ) ==="
"""

function main()
    fails = String[]
    gates = Dict{String, String}()

    # source availability: authenticated S3 OR the exact ECPDS fallback
    # (HEAD content-length must equal the pinned probe size). Both probe
    # verdicts are recorded; only BOTH failing blocks the checkpoint.
    s3_ok = try
        occursin("aeolus", read(pipeline(`aws sts get-caller-identity`,
                                         stderr=devnull), String))
    catch; false end
    ecpds_cl, ecpds_ar = try
        h = read(pipeline(`curl -fsSI --max-time 60 $ECPDS_BASE/lw_spectra/evaluation2/$PROBE_NAME`,
                          stderr=devnull), String)
        m = match(r"(?i)content-length:\s*(\d+)", h)
        (m === nothing ? -1 : parse(Int, m.captures[1]),
         match(r"(?i)accept-ranges:\s*bytes", h) !== nothing)
    catch; (-1, false) end
    ecpds_ok = ecpds_cl == PROBE_BYTES && ecpds_ar
    gates["source_available_at_generation"] = (s3_ok || ecpds_ok) ? "passed" : "failed"
    (s3_ok || ecpds_ok) ||
        push!(fails, "no source available at generation: S3 auth failed AND " *
                     "ECPDS probe failed (content-length $ecpds_cl != $PROBE_BYTES)")

    open(GC_SBATCH, "w") do io
        write(io, SBATCH_TEXT)
    end
    gates["sbatch_written_not_submitted"] = "passed"
    self_src = read(@__FILE__, String)
    sb_tok = "sb" * "atch "
    isempty(collect(eachmatch(Regex("run\\(`" * sb_tok), self_src))) ||
        (gates["sbatch_written_not_submitted"] = "failed";
         push!(fails, "sbatch invocation found in checkpoint unit"))
    gates["headnode_refusal_guard"] =
        occursin("REFUSED: head-node execution", SBATCH_TEXT) ? "passed" : "failed"
    exec_lines = join([l for l in split(SBATCH_TEXT, '\n')
                       if !occursin(r"^\s*#", l)], '\n')
    gates["fetch_only"] =
        occursin("aws s3 cp", exec_lines) &&
        occursin("wget --continue", exec_lines) &&
        !occursin("aws s3 sync", exec_lines) &&
        !occursin("optimize_lut", exec_lines) &&
        !occursin("create_lut", exec_lines) &&
        !occursin("scale_lut", exec_lines) &&
        !occursin("find_g_points", exec_lines) &&
        !occursin("lbl_evaluation", exec_lines) &&
        !occursin("ckdmip_lw", exec_lines) &&
        !occursin("ckdmip_sw", exec_lines) ? "passed" : "failed"
    gates["fetch_only"] == "passed" ||
        push!(fails, "forbidden stage invocation in executable lines")
    gates["species_scope_correct"] =
        length(SPECIES) == 7 && !occursin("cfc", join(SPECIES)) &&
        occursin("n2_constant", join(SPECIES)) ? "passed" : "failed"
    gates["exact70_gate"] =
        occursin("final verification failed", SBATCH_TEXT) &&
        occursin("SIZE MISMATCH", SBATCH_TEXT) &&
        occursin("MISSING", SBATCH_TEXT) ? "passed" : "failed"
    # 2026-08-13 resume review: df gate REMOVED (df cannot see Lustre uid
    # quotas); the soft-primary quota guard is the only headroom gate
    gates["df_gate_removed"] =
        !occursin(r"\bdf\b", exec_lines) ? "passed" : "failed"
    gates["per_object_pipeline"] =
        occursin("quota_object_recheck \"\$((size - pz))\" \"\$RESERVE\"", SBATCH_TEXT) &&
        occursin("quota_object_recheck 0 \"\$RESERVE\"", SBATCH_TEXT) &&
        occursin(".g2c.part.", SBATCH_TEXT) &&
        occursin("h5_sanity \"\$part\"", SBATCH_TEXT) &&
        occursin("h5_sanity \"\$final\"", SBATCH_TEXT) &&
        occursin("pre-existing exact-size final fails h5 sanity", SBATCH_TEXT) &&
        occursin("mv \"\$part\" \"\$final\"", SBATCH_TEXT) &&
        occursin("wrong-size existing final", SBATCH_TEXT) ? "passed" : "failed"
    gates["ecpds_fallback"] =
        occursin("if HDRS=\$(curl -fsSI", SBATCH_TEXT) &&
        occursin("wget --continue --tries=20 --timeout=60 --no-verbose -O", SBATCH_TEXT) &&
        occursin("aux.ecmwf.int/ecpds/home/ckdmip", SBATCH_TEXT) &&
        occursin("falling back to ECPDS resume", SBATCH_TEXT) &&
        occursin("quota_object_recheck \"\$((size - new_pz))\" \"\$RESERVE\"", SBATCH_TEXT) &&
        occursin("fetcher switched to ecpds", SBATCH_TEXT) &&
        occursin("probe row missing/drifted", SBATCH_TEXT) &&
        occursin("accept-ranges:", SBATCH_TEXT) &&
        occursin(".part larger than manifest", SBATCH_TEXT) &&
        occursin("part already complete", SBATCH_TEXT) &&
        occursin("REFUSED: no source available", SBATCH_TEXT) ? "passed" : "failed"
    gates["single_run_lock"] =
        occursin("command -v flock", SBATCH_TEXT) &&
        occursin("flock -n 9", SBATCH_TEXT) &&
        occursin(".g2c.fetch.lock", SBATCH_TEXT) ? "passed" : "failed"
    gates["soft_primary_reserve"] =
        RESERVE_BYTES == 53687091200 &&
        occursin("RESERVE=53687091200", SBATCH_TEXT) &&
        occursin("quota_guard \"\$DEST\" \"\$MANIFEST\" \"\$RESERVE\"", SBATCH_TEXT) ? "passed" : "failed"
    gates["quota_aware_preflight"] =
        occursin("gate4_quota_guard.sh", SBATCH_TEXT) &&
        occursin("gate4_eval2_selected_manifest.tsv", SBATCH_TEXT) ? "passed" : "failed"
    # audited manifest integrity (checkpoint-side mirror of the guard's check)
    manifest_path = joinpath(PROJECT_ROOT, "validation/gate4_eval2_selected_manifest.tsv")
    mrows = [split(l, '\t') for l in eachline(manifest_path)
             if !startswith(l, '#') && !isempty(strip(l))]
    mnames = [r[1] for r in mrows]
    msizes = Dict(r[1] => parse(Int, r[2]) for r in mrows)
    gates["manifest_integrity"] =
        (length(mrows) == 70 && length(unique(mnames)) == 70 &&
         sum(values(msizes)) == 329989234896) ? "passed" : "failed"
    gates["manifest_integrity"] == "passed" ||
        push!(fails, "manifest count/uniqueness/sum drift")
    gates["probe_size_matches_manifest"] =
        get(msizes, PROBE_NAME, -1) == PROBE_BYTES ? "passed" : "failed"
    gates["probe_size_matches_manifest"] == "passed" ||
        push!(fails, "probe object/size drift vs pinned manifest")

    # --- quota-guard fixture tests (same sourced logic the sbatch runs) ---
    guard = joinpath(PROJECT_ROOT, "validation/gate4_quota_guard.sh")
    run_guard(pathdir, destdir; mani=manifest_path) = success(pipeline(
        `/usr/bin/env PATH=$pathdir /bin/bash -c "source $guard; quota_guard $destdir $mani $RESERVE_BYTES"`,
        stdout=devnull, stderr=devnull))
    run_recheck(pathdir, next) = success(pipeline(
        `/usr/bin/env PATH=$pathdir /bin/bash -c "source $guard; quota_object_recheck $next $RESERVE_BYTES"`,
        stdout=devnull, stderr=devnull))
    fx = mktempdir()
    bin_min = joinpath(fx, "bin_min"); mkpath(bin_min)   # awk/stat/id, NO lfs
    for t in ("awk", "stat", "id", "grep", "sed", "sort", "wc")
        tp = Sys.which(t); tp === nothing || symlink(tp, joinpath(bin_min, t))
    end
    mkfix(name, rowscript) = begin
        d = joinpath(fx, name); mkpath(d)
        for t in readdir(bin_min); symlink(joinpath(bin_min, t), joinpath(d, t)); end
        lf = joinpath(d, "lfs")
        write(lf, "#!/bin/bash\n" * rowscript * "\n"); chmod(lf, 0o755)
        d
    end
    emptydest = joinpath(fx, "dest"); mkpath(joinpath(emptydest, "lw_spectra")); mkpath(joinpath(emptydest, "sw_spectra"))
    # (a) live-fixture: today's actual lfs row baked into a stub; expected
    #     verdict computed independently in Julia from the same row
    live_row = try
        uid = strip(read(`id -u`, String))
        strip(split(read(`lfs quota -q -u $uid /shared`, String), "\n")[1])
    catch; "" end
    tests = Dict{String, Bool}()
    need_empty = 329989234896 + RESERVE_BYTES   # manifest total + reserve
    if !isempty(live_row)
        d = mkfix("live", "echo \"$live_row\"")
        flds = split(live_row)
        used_kib = parse(Int, replace(flds[2], "*" => ""))
        soft_kib = parse(Int, replace(flds[3], "*" => ""))
        hard_kib = parse(Int, replace(flds[4], "*" => ""))
        grace = String(flds[5])
        soft_head = max(soft_kib - used_kib, 0) * 1024
        hard_head = max(hard_kib - used_kib, 0) * 1024
        expect_pass = soft_kib > 0 && hard_kib > 0 && grace == "-" &&
                      used_kib <= soft_kib &&
                      soft_head >= need_empty && hard_head >= need_empty
        tests["live_fixture_matches_independent_computation"] =
            run_guard(d, emptydest) == expect_pass
    else
        tests["live_fixture_matches_independent_computation"] = false
    end
    # (b) sufficient quota (healthy soft/hard, no grace) -> pass
    d = mkfix("sufficient", "echo \"/shared 100 900000000 2000000000 - 1 0 0 -\"")
    tests["sufficient_quota_passes"] = run_guard(d, emptydest) == true
    # (c) missing lfs -> refusal
    tests["missing_lfs_refuses"] = run_guard(bin_min, emptydest) == false
    # (d) malformed output -> refusal
    d = mkfix("malformed", "echo \"/shared abc* def ghi -\"")
    tests["malformed_refuses"] = run_guard(d, emptydest) == false
    # (e) soft or hard reading 0/unlimited -> deliberate refusal, each alone
    d = mkfix("zerosoft", "echo \"/shared 12345 0 2000000000 - 1 0 0 -\"")
    tests["zero_soft_limit_refuses"] = run_guard(d, emptydest) == false
    d = mkfix("zerohard", "echo \"/shared 12345 900000000 0 - 1 0 0 -\"")
    tests["zero_hard_limit_refuses"] = run_guard(d, emptydest) == false
    # (e2) active grace clock (already over soft) -> refusal even though
    # hard headroom alone would suffice
    d = mkfix("grace", "echo \"/shared 950000000* 943718400 2000000000 6d23h56m 1 0 0 -\"")
    tests["active_grace_refuses"] = run_guard(d, emptydest) == false
    # (e3) SOFT boundary: smallest soft-headroom that fits need(empty) =
    # total + reserve passes; 1 KiB less refuses. Boundary computed from
    # the same constants the guard enforces.
    bk = cld(need_empty, 1024)
    d = mkfix("softpass", "echo \"/shared 100 $(100 + bk) 2000000000 - 1 0 0 -\"")
    tests["soft_boundary_passes"] = run_guard(d, emptydest) == true
    d = mkfix("softfail", "echo \"/shared 100 $(100 + bk - 1) 2000000000 - 1 0 0 -\"")
    tests["soft_boundary_refuses"] = run_guard(d, emptydest) == false
    # (e4) the reserve does the refusing: soft headroom covers the
    # remaining bytes alone but NOT remaining + 50 GiB reserve
    rk = cld(329989234896, 1024) + 1000
    d = mkfix("reserveonly", "echo \"/shared 100 $(100 + rk) 2000000000 - 1 0 0 -\"")
    tests["reserve_refuses_when_only_remaining_fits"] = run_guard(d, emptydest) == false
    # (e5) hard is a SECONDARY ceiling: huge soft, hard below need -> refuse
    d = mkfix("hardsecondary", "echo \"/shared 100 1900000000 360000000 - 1 0 0 -\"")
    tests["hard_secondary_ceiling_refuses"] = run_guard(d, emptydest) == false
    # (f) finalized-file subtraction changes the VERDICT, exact-size only:
    # sparse file of EXACTLY the manifest size for lw h2o_present_1-10;
    # stub soft-headroom sits strictly between need(empty) = total +
    # reserve (-> REFUSE) and need(with exact file) = need(empty) -
    # manifest_size (-> PASS). Bounds computed, then asserted.
    fsz = msizes["ckdmip_evaluation2_lw_spectra_h2o_present_1-10.h5"]
    hb_kib = fld(need_empty - fld(fsz, 2), 1024)
    @assert need_empty - fsz < hb_kib * 1024 < need_empty
    d2 = joinpath(fx, "dest2"); mkpath(joinpath(d2, "lw_spectra")); mkpath(joinpath(d2, "sw_spectra"))
    open(joinpath(d2, "lw_spectra/ckdmip_evaluation2_lw_spectra_h2o_present_1-10.h5"), "w") do io
        seek(io, fsz - 1); write(io, UInt8(0))
    end
    d = mkfix("between", "echo \"/shared 100 $(100 + hb_kib) 2000000000 - 1 0 0 -\"")
    tests["subtraction_refuses_on_empty_dest"] = run_guard(d, emptydest) == false
    tests["subtraction_passes_with_exact_size_file"] = run_guard(d, d2) == true
    # (g) present-but-WRONG-size file must REFUSE even under huge quota
    # (10 GiB bogus at an expected name; the fetch would replace it)
    d3 = joinpath(fx, "dest3"); mkpath(joinpath(d3, "lw_spectra")); mkpath(joinpath(d3, "sw_spectra"))
    open(joinpath(d3, "lw_spectra/ckdmip_evaluation2_lw_spectra_h2o_present_1-10.h5"), "w") do io
        seek(io, 10 * 1024^3 - 1); write(io, UInt8(0))
    end
    d = mkfix("hugequota", "echo \"/shared 100 1900000000 2000000000 - 1 0 0 -\"")
    tests["wrong_size_file_refuses"] = run_guard(d, d3) == false
    # (h) per-object recheck: same soft-primary fail-closed policy per call
    d = mkfix("recheck_ok", "echo \"/shared 100 900000000 2000000000 - 1 0 0 -\"")
    tests["recheck_passes_with_headroom"] = run_recheck(d, 5000000000) == true
    # soft headroom EXACTLY equals the reserve: a 5 GB next object no
    # longer fits on top of it -> refuse (the reserve does the work) ...
    d = mkfix("recheck_low", "echo \"/shared 100 $(100 + 52428800) 2000000000 - 1 0 0 -\"")
    tests["recheck_refuses_when_reserve_would_be_breached"] = run_recheck(d, 5000000000) == false
    # ... while the publish-time call shape (next=0, .part bytes already
    # in `used`) still passes at exactly-reserve headroom
    tests["recheck_zero_next_passes_at_exact_reserve"] = run_recheck(d, 0) == true
    d = mkfix("recheck_grace", "echo \"/shared 950000000* 943718400 2000000000 6d23h56m 1 0 0 -\"")
    tests["recheck_refuses_active_grace"] = run_recheck(d, 0) == false
    # malformed next byte count must refuse BEFORE shell arithmetic
    d = mkfix("recheck_badnext", "echo \"/shared 100 900000000 2000000000 - 1 0 0 -\"")
    tests["recheck_refuses_malformed_next"] = success(pipeline(
        `/usr/bin/env PATH=$d /bin/bash -c "source $guard; quota_object_recheck 12abc $RESERVE_BYTES"`,
        stdout=devnull, stderr=devnull)) == false
    # (i) source-selection fixtures: the EXACT preflight block from the
    # generated sbatch, run under set -euo pipefail with stubbed
    # aws/curl/wget. The down-fallback/up-primary case is the one the
    # conditional curl assignment exists for.
    selstart = findfirst("S3_OK=0; ECPDS_OK=0", SBATCH_TEXT)
    selend = findfirst("echo \"fetcher: \$FETCHER\"", SBATCH_TEXT)
    if selstart !== nothing && selend !== nothing
        snippet = SBATCH_TEXT[first(selstart):last(selend)]
        mksel(name, awsrc, curlbody) = begin
            sd = joinpath(fx, name); mkpath(sd)
            for t in readdir(bin_min); symlink(joinpath(bin_min, t), joinpath(sd, t)); end
            tp = Sys.which("tr"); tp === nothing || symlink(tp, joinpath(sd, "tr"))
            write(joinpath(sd, "aws"), "#!/bin/bash\nexit $awsrc\n")
            write(joinpath(sd, "curl"), "#!/bin/bash\n" * curlbody * "\n")
            write(joinpath(sd, "wget"), "#!/bin/bash\nexit 0\n")
            foreach(t -> chmod(joinpath(sd, t), 0o755), ("aws", "curl", "wget"))
            sd
        end
        okhdrs = "printf 'HTTP/1.1 200 OK\\r\\nContent-Length: 1\\r\\nAccept-Ranges: bytes\\r\\n\\r\\n'"
        selscript(check) = "set -euo pipefail\nPROBE_NAME=probe.h5\nPROBE_SIZE=1\n" *
                           snippet * "\n" * check * "\n"
        run_sel(sd, check) = run(pipeline(ignorestatus(
            `/usr/bin/env PATH=$sd /bin/bash -c $(selscript(check))`),
            stdout=devnull, stderr=devnull)).exitcode
        # ECPDS down (curl exit 22) + S3 up: must survive and pick s3
        tests["source_selection_survives_ecpds_down_with_s3_up"] =
            run_sel(mksel("sel_s3", 0, "exit 22"),
                    "[ \"\$FETCHER\" = s3 ] && [ \"\$ECPDS_OK\" = 0 ]") == 0
        # S3 down + ECPDS exact: must pick ecpds
        tests["source_selection_falls_back_to_ecpds"] =
            run_sel(mksel("sel_ecpds", 1, okhdrs),
                    "[ \"\$FETCHER\" = ecpds ] && [ \"\$S3_OK\" = 0 ]") == 0
        # both down: must refuse with the dedicated no-source exit 66
        tests["source_selection_refuses_when_both_down"] =
            run_sel(mksel("sel_none", 1, "exit 22"), "true") == 66
    else
        tests["source_selection_survives_ecpds_down_with_s3_up"] = false
        tests["source_selection_falls_back_to_ecpds"] = false
        tests["source_selection_refuses_when_both_down"] = false
    end
    gates["quota_guard_fixture_tests"] =
        all(values(tests)) ? "passed" : "failed"
    all(values(tests)) ||
        push!(fails, "quota-guard fixture failures: " *
                     join([k for (k, v) in tests if !v], ", "))

    # LIVE guard evaluation (real lfs row, real DEST, pinned manifest):
    # a deployed-guard refusal must never be masked by a 'ready' label.
    live_buf = IOBuffer()
    live_ok = success(pipeline(
        `/bin/bash -c "source $guard; quota_guard $DEST $manifest_path $RESERVE_BYTES"`,
        stdout=live_buf, stderr=live_buf))
    live_report = strip(String(take!(live_buf)))
    gates["live_quota_headroom"] = live_ok ? "passed" : "failed"

    others_pass = all(k -> k == "live_quota_headroom" || gates[k] == "passed",
                      keys(gates))
    status = if others_pass && live_ok && isempty(fails)
        "g2c_checkpoint_ready"
    elseif others_pass && isempty(fails)
        "g2c_checkpoint_blocked_by_quota"
    else
        "g2c_checkpoint_failed"
    end
    branch = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --abbrev-ref HEAD`, String)) catch; "unknown" end
    ghead = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --short HEAD`, String)) catch; "unknown" end

    result = Dict(
        "case" => "gate4_g2c_eval2_fetch_checkpoint",
        "data_mode" => "dry_run_script_generation_only",
        "status" => status,
        "timestamp_utc" => string(Dates.now(Dates.UTC)),
        "gates" => gates, "failures" => fails,
        "authorization" => "Greg: 'go with option A' (2026-07-30) + SSO " *
            "re-auth and 'keep going' (2026-08-12) + G2c resume: Greg via " *
            "campaign coordinator 'of course, keep going; the fetch/job " *
            "gate is lifted', relay reviewed and accepted as durable " *
            "authorization by the Codex monitor (2026-08-13); submission " *
            "itself additionally gated on Codex diff review",
        "sbatch_path" => GC_SBATCH,
        "source" => "$S3_BASE (byte-verified ECPDS archive per " *
                    "archive_to_s3.log 2026-05-27; ECPDS live as fallback, " *
                    "HEAD-audited 70/70 exact vs pinned manifest by the " *
                    "Codex monitor 2026-08-13)",
        "source_probes" => Dict(
            "s3_auth" => s3_ok,
            "ecpds_probe_object" => PROBE_NAME,
            "ecpds_probe_expected_bytes" => PROBE_BYTES,
            "ecpds_probe_content_length" => ecpds_cl,
            "ecpds_accept_ranges_bytes" => ecpds_ar,
            "ecpds_exact" => ecpds_ok,
            "selection_rule" => "prefer authenticated S3; else exact ECPDS " *
                "fallback; refuse only when both unavailable (mirrored in " *
                "the sbatch stage-0 preflight)"),
        "quota_guard_fixture_verdicts" => tests,
        "live_quota_guard" => Dict(
            "verdict" => live_ok ? "pass" : "refused",
            "report" => live_report),
        "scope" => Dict(
            "species" => SPECIES, "chunks" => CHUNKS,
            "expected_files" => 70,
            "expected_bytes_approx" => "LW 219.6 GB + SW 110.4 GB = ~330 GB",
            "skipped" => "cfc11/cfc12 (rel-415 never reads them); rayleigh " *
                "(not on S3/ECPDS -- generated in the follow-on flux unit); " *
                "ssi (evaluation1 local copy reused)"),
        "followon" => "G2d: rayleigh generation (make_rayleigh_evaluation.sh " *
            "recipe, ckdmip_tool --rayleigh on the 5 eval2 h2o_present SW " *
            "chunks) + rel-415 LBL runs (LW plain, SW rgb-banded) -> 2 flux " *
            "files -> ledger -> G3",
        "provenance" => Dict("branch" => branch, "generated_from_head" => ghead,
            "provenance_note" => "artifact generated from the working tree " *
                "before its own commit"),
        "disclaimer" => "script generation only; nothing submitted by this " *
                        "unit; fetch+verify only; no LBL, optimizer, " *
                        "objective, floor, or recovery computation.",
    )
    mkpath(dirname(GC_RESULTS_JSON))
    open(GC_RESULTS_JSON, "w") do io
        JSON.print(io, result, 2)
    end
    open(GC_RESULTS_MD, "w") do io
        println(io, "# Gate-4 G2c evaluation2 spectra fetch checkpoint\n")
        println(io, "Status: **$status**\n")
        println(io, result["disclaimer"], "\n")
        println(io, "Authorization: ", result["authorization"], "\n")
        println(io, "| Gate | Result |")
        println(io, "|---|---|")
        for k in sort(collect(keys(gates)))
            println(io, "| $k | $(gates[k]) |")
        end
        println(io, "\nLive quota guard: **" *
                    (live_ok ? "pass" : "REFUSED") * "** -- " * live_report)
        println(io, "\nSource: ", result["source"])
        println(io, "\nScope: 7 species x 5 chunks x 2 bands = 70 files, " *
                    "~330 GB; cfc/rayleigh/ssi excluded (see JSON).")
        println(io, "\nFollow-on: ", result["followon"])
        println(io, "\nProvenance: branch `$branch`, generated_from_head " *
                    "`$ghead` (pre-own-commit).")
        isempty(fails) || (println(io, "\n## Failures\n");
                           foreach(f -> println(io, "- ", f), fails))
    end
    println("gate4_g2c_eval2_fetch_checkpoint: $status")
    for k in sort(collect(keys(gates)))
        println("  $k: $(gates[k])")
    end
    isempty(fails) || foreach(f -> println("  FAIL: $f"), fails)
    return status in ("g2c_checkpoint_ready",
                      "g2c_checkpoint_blocked_by_quota") ? 0 : 1
end

exit(main())
