# Gate-4 A2 EXECUTION CHECKPOINT + proof scaffold (dry-run; NO submission).
#
# Generates the exact Slurm batch script for the A2 reorder + find_g_points
# run (LW fsck tol 0.0161, SW rgb tol 0.047 FIRST, per the pinned do_all
# lists) and records the follow-on exact-reproduction proof plan. The batch
# script is WRITTEN but never submitted by this unit; it refuses head-node
# execution by guard. No find_g_points/create_lut/objective/floor execution.

include(joinpath(@__DIR__, "validation_results.jl"))

using Dates
import JSON

const WORKCOPY = "/shared/home/greg/ecckd-derived-flux-work/ecckd"
const G4WORK = "/shared/home/greg/ecckd-derived-flux-work/g4-init-generation"
const CKDMIP_ROOT = "/shared/home/greg/data/ckdmip"

const AX_RESULTS_JSON = validation_results_path("gate4_a2_execution_checkpoint.json")
const AX_RESULTS_MD = validation_results_path("gate4_a2_execution_checkpoint.md")
const AX_SBATCH = validation_results_path("gate4_a2_dryrun.sbatch")

const SBATCH_TEXT = """
#!/bin/bash
#SBATCH --job-name=g4-a2-find-g-points
#SBATCH --output=/shared/home/greg/data/ckdmip-logs/g4-a2-%j.log
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=60G
#SBATCH --partition=cpu-large

# Gate-4 A2: reorder_spectrum + find_g_points ONLY (no LUT-creation, no
# optimisation, no objective stages). Generated by gate4_a2_execution_checkpoint.jl;
# DO NOT run outside Slurm.
set -euo pipefail
if [ -z "\${SLURM_JOB_ID:-}" ]; then
    echo "REFUSED: head-node execution is not permitted; submit via sbatch." >&2
    exit 64
fi

WORKCOPY=$WORKCOPY
G4WORK=$G4WORK
mkdir -p "\$G4WORK"

# scoped test-dir copy with WORK_DIR redirected to the quarantined g4 tree
# ISOLATED test-copy: never mutate the 4078 working copy; config.h
# hard-codes CKDMIP_DATA_DIR/WORK_DIR/BINDIR, so env-only localization is
# INSUFFICIENT -- all three are sed-patched ABSOLUTE in the copy (BINDIR in
# the pristine file is ../src/ecckd relative to test/, which would break in
# a relocated copy).
TESTCOPY="\$G4WORK/testcopy"
rm -rf "\$TESTCOPY"
cp -r "\$WORKCOPY/test" "\$TESTCOPY"
sed -i \
  -e 's|^CKDMIP_DATA_DIR=.*|CKDMIP_DATA_DIR=$CKDMIP_ROOT|' \
  -e 's|^WORK_DIR=.*|WORK_DIR=$G4WORK/work|' \
  -e 's|^BINDIR=.*|BINDIR=$WORKCOPY/src/ecckd|' \
  "\$TESTCOPY/config.h"
grep -E "^(CKDMIP_DATA_DIR|WORK_DIR|BINDIR)=" "\$TESTCOPY/config.h"
cd "\$TESTCOPY"

echo "=== A2 LW: reorder (fsck) ==="
APPLICATION=climate BAND_STRUCTURE=fsck bash reorder_spectrum_lw.sh
echo "=== A2 LW: find_g_points (fsck, TOLERANCE=0.0161) ==="
APPLICATION=climate BAND_STRUCTURE=fsck TOLERANCE=0.0161 bash find_g_points_lw.sh
echo "=== A2 SW: reorder (rgb) ==="
APPLICATION=climate BAND_STRUCTURE=rgb bash reorder_spectrum_sw.sh
echo "=== A2 SW: find_g_points (rgb, TOLERANCE=0.047) ==="
APPLICATION=climate BAND_STRUCTURE=rgb TOLERANCE=0.047 bash find_g_points_sw.sh

echo "=== A2 outputs ==="
find "$G4WORK/work" -name "*gpoints*" -o -name "*order*" | head -40
echo "=== A2 done rc=\$? \$(date -u +%FT%TZ) ==="
"""

function main()
    fails = String[]
    gates = Dict{String, String}()

    a2 = JSON.parsefile(
        validation_results_path("gate4_a2_find_g_points_rerun_manifest.json"))
    a2["status"] == "a2_manifest_ready" ||
        push!(fails, "A2 manifest not ready: $(a2["status"])")

    # write the dry-run sbatch (artifact; never submitted here)
    open(AX_SBATCH, "w") do io
        write(io, SBATCH_TEXT)
    end

    # gates
    gates["sbatch_written_not_submitted"] = "passed"   # structural: this
    # script contains no `sbatch` invocation (self-scan with split token)
    self_src = read(@__FILE__, String)
    sb_tok = "sb" * "atch "
    n_direct = length(collect(eachmatch(Regex("run\\(`" * sb_tok), self_src)))
    n_direct == 0 || (gates["sbatch_written_not_submitted"] = "failed";
                      push!(fails, "sbatch invocation found in checkpoint unit"))
    gates["headnode_refusal_guard"] =
        occursin("REFUSED: head-node execution", SBATCH_TEXT) ? "passed" : "failed"
    # scan EXECUTABLE lines only (comments stripped) so the script may
    # mention forbidden stages in prose without failing itself
    exec_lines = join([l for l in split(SBATCH_TEXT, '\n')
                       if !occursin(r"^\s*#", l)], '\n')
    gates["reorder_and_find_only"] =
        !occursin("create_lut", exec_lines) &&
        !occursin("create_look_up_table", exec_lines) &&
        !occursin("optimize_lut", exec_lines) ? "passed" : "failed"
    gates["reorder_and_find_only"] == "passed" ||
        push!(fails, "forbidden stage invocation in executable sbatch lines")
    gates["target_tolerances_narrowed"] =
        occursin("TOLERANCE=0.0161", SBATCH_TEXT) &&
        occursin("TOLERANCE=0.047", SBATCH_TEXT) ? "passed" : "failed"
    gates["workdir_quarantined"] =
        occursin("g4-init-generation/work", SBATCH_TEXT) ? "passed" : "failed"
    running_4078 = try
        !isempty(strip(read(`squeue -j 4078 -h -o "%T"`, String)))
    catch; false end
    contention = Dict(
        "job_4078_running" => running_4078,
        "policy" => "A2 may run CONCURRENTLY with 4078 on a different " *
                    "cpu-large node (partition has 4 nodes); do not submit " *
                    "if the partition is saturated; never share the node " *
                    "running 4078",
    )
    gates["contention_policy_recorded"] = "passed"
    gates["config_copy_patched_not_env_only"] =
        occursin("sed -i", SBATCH_TEXT) &&
        occursin("CKDMIP_DATA_DIR=", SBATCH_TEXT) &&
        occursin("BINDIR=" * WORKCOPY * "/src/ecckd", SBATCH_TEXT) &&
        occursin("INSUFFICIENT", SBATCH_TEXT) ? "passed" : "failed"
    gates["config_copy_patched_not_env_only"] == "passed" ||
        push!(fails, "config.h copy-patch of all three path vars not present")
    gates["no_mutation_of_4078_workcopy"] =
        !occursin(Regex("sed -i[^\n]*\\\$WORKCOPY/test/config"), SBATCH_TEXT) &&
        occursin("cp -r \"\$WORKCOPY/test\"", SBATCH_TEXT) ? "passed" : "failed"

    proof_plan = Dict(
        "unit" => "gate4_a2_reproduction_proof (follow-on; not implemented here)",
        "inputs" => ["rerun gpoints candidates: " *
                     "$G4WORK/work/**/ecckd-*_{lw,sw}_gpoints_*tol{0.0161,0.047}*.h5",
                     "raw create_lut outputs built FROM those candidates " *
                     "(init-generation manifest commands)",
                     "published LW32/SW32 definitions (verification targets)"],
        "gates" => ["g-counts exactly 32/32",
                    "gpoint_fraction elementwise EXACT vs published",
                    "wavenumber1_band/wavenumber2_band/band_number EXACT",
                    "on any mismatch: candidates are sensitivity-only; " *
                    "report, do not proceed to floor"],
        "refusal" => "proof runner refuses when candidate files are absent",
    )

    status = isempty(fails) ? "a2_execution_checkpoint_ready" :
                              "a2_execution_checkpoint_failed"
    branch = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --abbrev-ref HEAD`, String)) catch; "unknown" end
    head = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --short HEAD`, String)) catch; "unknown" end

    result = Dict(
        "case" => "gate4_a2_execution_checkpoint",
        "data_mode" => "dry_run_script_generation_only",
        "status" => status,
        "timestamp_utc" => string(Dates.now(Dates.UTC)),
        "gates" => gates, "failures" => fails,
        "sbatch_path" => AX_SBATCH,
        "env_localization" => Dict(
            "mechanism" => "ALL THREE hard-coded config.h path variables " *
                "are sed-patched ABSOLUTE inside the isolated TESTCOPY; " *
                "env-only localization is insufficient and gated; the " *
                "active 4078 working copy is read only as a copy source, " *
                "never mutated",
            "CKDMIP_DATA_DIR" => "$CKDMIP_ROOT (sed-patched in TESTCOPY)",
            "WORK_DIR" => "$G4WORK/work (sed-patched in TESTCOPY; " *
                          "quarantined from 4078's workdir)",
            "BINDIR" => "$WORKCOPY/src/ecckd (sed-patched ABSOLUTE in " *
                        "TESTCOPY; pristine relative ../src/ecckd would " *
                        "break in a relocated copy)",
            "APPLICATION" => "climate",
            "BAND_STRUCTURE/TOLERANCE" => "fsck/0.0161 (LW), rgb/0.047 (SW) " *
                                          "first; 16-g sanity later"),
        "expected_outputs" => Dict(
            "gpoints" => "$G4WORK/work/**/ecckd-*_gpoints_climate_" *
                         "{fsck-tol0.0161,rgb-tol0.047}.h5",
            "reorder" => "$G4WORK/work/**/{lw,sw}_order_*_*.h5",
            "log" => "/shared/home/greg/data/ckdmip-logs/g4-a2-<jobid>.log"),
        "contention" => contention,
        "proof_plan" => proof_plan,
        "provenance" => Dict("branch" => branch, "generated_from_head" => head,
            "provenance_note" => "artifact generated from the working tree " *
                "before its own commit"),
        "disclaimer" => "dry-run script generation only; nothing submitted; " *
                        "no find_g_points/create_lut/objective/floor " *
                        "execution; submission requires explicit " *
                        "authorization per the standing protocol.",
    )
    mkpath(dirname(AX_RESULTS_JSON))
    open(AX_RESULTS_JSON, "w") do io
        JSON.print(io, result, 2)
    end
    open(AX_RESULTS_MD, "w") do io
        println(io, "# Gate-4 A2 execution checkpoint (dry-run)\n")
        println(io, "Status: **$status**\n")
        println(io, result["disclaimer"], "\n")
        println(io, "| Gate | Result |")
        println(io, "|---|---|")
        for k in sort(collect(keys(gates)))
            println(io, "| $k | $(gates[k]) |")
        end
        println(io, "\nGenerated (unsubmitted) batch script: `$(AX_SBATCH)`")
        println(io, "\nContention: 4078 running = $(contention["job_4078_running"]); " *
                    contention["policy"])
        println(io, "\nFollow-on proof plan: g-counts 32/32; gpoint_fraction " *
                    "and band arrays elementwise EXACT vs published; any " *
                    "mismatch -> sensitivity-only, no floor.")
        println(io, "\nProvenance: branch `$branch`, generated_from_head " *
                    "`$head` (pre-own-commit).")
        isempty(fails) || (println(io, "\n## Failures\n");
                           foreach(f -> println(io, "- ", f), fails))
    end
    println("gate4_a2_execution_checkpoint: $status")
    for k in sort(collect(keys(gates)))
        println("  $k: $(gates[k])")
    end
    isempty(fails) || foreach(f -> println("  FAIL: $f"), fails)
    return status == "a2_execution_checkpoint_ready" ? 0 : 1
end

exit(main())
