# Gate-4 G2a SW-RGB TRAINING-FLUX checkpoint (dry-run generation; NO
# submission). Data-generation/preflight work for the G2/G3 optimizer runs.
#
# The SW optimizer in rgb mode rewrites its training paths from sw_fluxes
# to sw_fluxes-rgb (optimize_lut_sw.sh:204-219): RGB-banded LBL flux files
# that do NOT exist locally and are NOT published upstream (ECPDS 404s
# recorded in the readiness review). This unit generates the SIX
# relative-base files (rel-180..2240) that the first SW pass and its
# relative_to reference need -- the minimum to unblock G2 objective parity
# on the accepted inits. Later passes (present, ch4 x5, n2o x4) and the
# TRAINING_BOTH=yes evaluation2 rel-415 question are follow-on units.
#
# BAND GRID (monitor-reviewed): run_sw_lbl_evaluation.sh's commented 9-band
# variant "250 2500 4000 8000 14300 16650 20000 25000 31750 / ... 50000" is
# activated (NOT the 14286/16667/31746 variant) because create_lut_sw.sh
# uses base_wavenumber_boundary=14300 and optimize_lut_sw.sh maps the 9 LBL
# bands onto the 5 CKD rgb bands via "0 0 0 0 1 2 3 4 4", which collapses
# exactly onto WN1_SW_RGB="250 14300 16650 20000 25000".
#
# Pipeline parity with job 4078: same pinned-artifact scripts, same
# ckdmip_sw binary, same Julia concat helper replacing ncrcat, same
# reuse-skip guard; SCENARIOS needs no edit (the pinned default is already
# the six rel scenarios). Isolated testcopy-rgb; outputs quarantined to
# work-rgb then INSTALLED to $CKDMIP_ROOT/evaluation1/sw_fluxes-rgb/ (the
# exact path the optimizer's rewrite expects) only behind an exact-6
# completeness gate.

include(joinpath(@__DIR__, "validation_results.jl"))

using Dates
import JSON

const ECCKD_SRC = "/shared/home/greg/.julia/artifacts/" *
    "7b210aef53e908cfe3c709945f0763c37ca82aaa/" *
    "ecckd-6115f9b8e29a55cb0f48916857bdc77fec41badd"
const G4WORK = "/shared/home/greg/ecckd-derived-flux-work/g4-init-generation"
const CKDMIP_ROOT = "/shared/home/greg/data/ckdmip"
const CKDMIP_BIN_ROOT = "/shared/home/greg/build/ckdmip-1.0"
const PROJECT_ROOT = "/shared/home/greg/Projects/AnalyticBandRadiation-platform"
const CO2_LEVELS = ["180", "280", "415", "560", "1120", "2240"]

const GA_RESULTS_JSON = validation_results_path("gate4_g2a_sw_rgb_flux_checkpoint.json")
const GA_RESULTS_MD = validation_results_path("gate4_g2a_sw_rgb_flux_checkpoint.md")
const GA_SBATCH = validation_results_path("gate4_g2a_sw_rgb_dryrun.sbatch")

const SBATCH_TEXT = """
#!/bin/bash
#SBATCH --job-name=g4-g2a-sw-rgb-fluxes
#SBATCH --output=/shared/home/greg/data/ckdmip-logs/g4-g2a-%j.log
#SBATCH --time=10:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=60G
#SBATCH --partition=cpu-large

# Gate-4 G2a: RGB-banded SW LBL training fluxes, rel scenarios ONLY (no
# optimizer, no objective stages). Generated by
# gate4_g2a_sw_rgb_flux_checkpoint.jl.
set -euo pipefail
if [ -z "\${SLURM_JOB_ID:-}" ]; then
    echo "REFUSED: head-node execution is not permitted; submit via sbatch." >&2
    exit 64
fi

G4WORK=$G4WORK
TESTCOPY="\$G4WORK/testcopy-rgb"

echo "=== G2a stage 0: preflight ==="
test -x "$CKDMIP_BIN_ROOT/bin/ckdmip_sw" || { echo "MISSING ckdmip_sw" >&2; exit 65; }
test -s "$CKDMIP_ROOT/evaluation1/sw_spectra/ckdmip_ssi.h5" || { echo "MISSING evaluation1 SSI" >&2; exit 65; }
for chunk in 1-10 11-20 21-30 31-40 41-50; do
    for gas in h2o o3 co2 ch4 n2o o2 n2 rayleigh; do
        ls "$CKDMIP_ROOT/evaluation1/sw_spectra/"ckdmip_evaluation1_sw_spectra_\${gas}_*_\${chunk}.h5 >/dev/null 2>&1 || { echo "MISSING evaluation1 SW spectra: \$gas \$chunk" >&2; exit 65; }
    done
done
for lev in $(join(CO2_LEVELS, " ")); do
    test ! -e "\$G4WORK/work-rgb/sw_lbl_fluxes/ckdmip_evaluation1_sw_fluxes-rgb_rel-\$lev.h5" || { echo "REFUSED: stale consolidated rgb output rel-\$lev" >&2; exit 70; }
    test ! -e "$CKDMIP_ROOT/evaluation1/sw_fluxes-rgb/ckdmip_evaluation1_sw_fluxes-rgb_rel-\$lev.h5" || { echo "REFUSED: stale installed rgb output rel-\$lev" >&2; exit 70; }
done

echo "=== G2a stage 1: isolated testcopy-rgb from the PINNED artifact ==="
rm -rf "\$TESTCOPY"
cp -r "$ECCKD_SRC/test" "\$TESTCOPY"
cd "\$TESTCOPY"
sed 's/@PACKAGE_VERSION@/1.2/g' version.h.in > version.h
sed -i \\
  -e 's|^CKDMIP_DIR=.*|CKDMIP_DIR=$CKDMIP_BIN_ROOT|' \\
  -e 's|^CKDMIP_DATA_DIR=.*|CKDMIP_DATA_DIR=$CKDMIP_ROOT|' \\
  -e 's|^WORK_DIR=.*|WORK_DIR=$G4WORK/work-rgb|' \\
  -e 's|^BINDIR=.*|BINDIR=/shared/home/greg/ecckd-derived-flux-work/ecckd/src/ecckd|' \\
  config.h
grep -E "^(CKDMIP_DIR|CKDMIP_DATA_DIR|WORK_DIR|BINDIR)=" config.h
# band-structure edits: fluxes -> fluxes-rgb; deactivate the 13-band narrow
# grid; activate the 9-band RGB grid (14300/16650/20000/25000/31750 variant)
sed -i \\
  -e 's|^BANDCODE=fluxes\$|BANDCODE=fluxes-rgb|' \\
  -e 's|^band_wavenumber1(1:13)|!band_wavenumber1(1:13)|' \\
  -e 's|^band_wavenumber2(1:13)|!band_wavenumber2(1:13)|' \\
  -e 's|^!band_wavenumber1(1:9) = 250, 2500, 4000, 8000, 14300, 16650, 20000, 25000, 31750,|band_wavenumber1(1:9) = 250, 2500, 4000, 8000, 14300, 16650, 20000, 25000, 31750,|' \\
  -e 's|^!band_wavenumber2(1:9) = 2500, 4000, 8000, 14300, 16650, 20000, 25000, 31750, 50000,|band_wavenumber2(1:9) = 2500, 4000, 8000, 14300, 16650, 20000, 25000, 31750, 50000,|' \\
  run_sw_lbl_evaluation.sh
grep -E "^BANDCODE=|^band_wavenumber" run_sw_lbl_evaluation.sh
grep -qE "^BANDCODE=fluxes-rgb\$" run_sw_lbl_evaluation.sh || { echo "BAD edit: BANDCODE" >&2; exit 68; }
test \$(grep -cE "^band_wavenumber1" run_sw_lbl_evaluation.sh) -eq 1 || { echo "BAD edit: band grid count" >&2; exit 68; }
# pipeline parity with 4078: no nco module, quieter, Julia concat, reuse-skip
sed -i '/^module load nco\$/s/^/# /' run_sw_lbl_evaluation.sh
sed -i 's/iverbose = 3/iverbose = 1/g' run_sw_lbl_evaluation.sh
sed -i -E 's|ncrcat -O \\\$OUTFILES \\\$OUTFILE|julia --project=$PROJECT_ROOT/test $PROJECT_ROOT/validation/concat_ckdmip_flux_chunks.jl \$OUTFILES \$OUTFILE|' run_sw_lbl_evaluation.sh
sed -i '/OUTFILES="\$OUTFILES \$OUTFILE"/a\\
\\tif [ -s "\$OUTFILE" ]\\
\\tthen\\
\\t    echo "*** REUSING \$OUTFILE ***"\\
\\t    continue\\
\\tfi' run_sw_lbl_evaluation.sh

echo "=== G2a stage 2: RGB-banded SW LBL evaluation (6 rel scenarios) ==="
bash run_sw_lbl_evaluation.sh

echo "=== G2a stage 3: exact-6 completeness gate + install ==="
ALL_OK=1
for lev in $(join(CO2_LEVELS, " ")); do
    test -s "\$G4WORK/work-rgb/sw_lbl_fluxes/ckdmip_evaluation1_sw_fluxes-rgb_rel-\$lev.h5" || { echo "MISSING consolidated rgb rel-\$lev" >&2; ALL_OK=0; }
done
[ "\$ALL_OK" = 1 ] || { echo "REFUSED: completeness gate failed; NOT installing partial set" >&2; exit 71; }
mkdir -p "$CKDMIP_ROOT/evaluation1/sw_fluxes-rgb"
for lev in $(join(CO2_LEVELS, " ")); do
    install -m 0644 "\$G4WORK/work-rgb/sw_lbl_fluxes/ckdmip_evaluation1_sw_fluxes-rgb_rel-\$lev.h5" "$CKDMIP_ROOT/evaluation1/sw_fluxes-rgb/"
    cmp -s "\$G4WORK/work-rgb/sw_lbl_fluxes/ckdmip_evaluation1_sw_fluxes-rgb_rel-\$lev.h5" "$CKDMIP_ROOT/evaluation1/sw_fluxes-rgb/ckdmip_evaluation1_sw_fluxes-rgb_rel-\$lev.h5" || { echo "INSTALL IDENTITY MISMATCH rel-\$lev" >&2; exit 72; }
done

echo "=== G2a outputs ==="
sha256sum "$CKDMIP_ROOT/evaluation1/sw_fluxes-rgb/"ckdmip_evaluation1_sw_fluxes-rgb_rel-*.h5
echo "=== G2a done rc=\$? \$(date -u +%FT%TZ) ==="
"""

# guarded init-ledger prerequisite loader (fixture-run on tmp files): a
# missing, unparseable (parse failure), parsed-non-object (JSON null/
# array DISTINGUISHED from parse failure), WRONG-CASE, or wrong-status
# artifact classifies fail-closed with a stable reason -- never an
# uncaught exception, never status-only trust: the exact case is bound
# before the FAITHFUL exact-status comparison.
function classify_init_ledger(path)
    isfile(path) ||
        return (false, "init provenance ledger missing: $path", nothing)
    parse_failed = false
    d = try
        JSON.parsefile(path)
    catch
        parse_failed = true
        nothing
    end
    parse_failed && return (false,
        "init provenance ledger unparseable (parse failure)", nothing)
    d isa AbstractDict || return (false,
        "init provenance ledger parses to a non-object " *
        "(JSON null/array/scalar)", nothing)
    c = get(d, "case", "")
    (c isa AbstractString && c == "gate4_init_provenance_ledger") ||
        return (false,
                "init provenance ledger case mismatch: $(repr(c))",
                nothing)
    s = get(d, "status", "")
    s == "acceptance_inits_complete" ||
        return (false, "init provenance ledger not green: $(repr(s))",
                nothing)
    return (true, "ok", d)
end

# the sbatch WRITE happens only behind the classified prerequisite (the
# committed script is never clobbered by a blocked run); SBATCH_TEXT is
# a load-time constant, so generation itself cannot throw and the text
# gates stay evaluated on both paths -- only the write is gated
function ga_write_script(writefn, prereq_ok)
    prereq_ok || return false
    writefn()
    return true
end

function main()
    fails = String[]
    gates = Dict{String, String}()

    # loader + write-boundary fixtures FIRST, through the SAME code
    tdir = mktempdir()
    lt = Dict{String, Bool}()
    lt["missing_fails"] =
        !classify_init_ledger(joinpath(tdir, "absent.json"))[1]
    fpx = joinpath(tdir, "il.json")
    write(fpx, "{")
    lt["malformed_fails"] = begin
        okx, why = classify_init_ledger(fpx)
        !okx && occursin("unparseable", why)
    end
    write(fpx, "null")
    lt["null_non_object_fails"] = begin
        okx, why = classify_init_ledger(fpx)
        !okx && occursin("non-object", why)
    end
    write(fpx, "[1]")
    lt["array_non_object_fails"] = begin
        okx, why = classify_init_ledger(fpx)
        !okx && occursin("non-object", why)
    end
    write(fpx, "{\"case\": \"other\", " *
               "\"status\": \"acceptance_inits_complete\"}")
    lt["wrong_case_fails"] = begin
        okx, why = classify_init_ledger(fpx)
        !okx && occursin("case mismatch", why)
    end
    write(fpx, "{\"case\": \"gate4_init_provenance_ledger\", " *
               "\"status\": \"tampered\"}")
    lt["wrong_status_fails"] = begin
        okx, why = classify_init_ledger(fpx)
        !okx && occursin("not green", why)
    end
    write(fpx, "{\"case\": \"gate4_init_provenance_ledger\", " *
               "\"status\": \"acceptance_inits_complete\"}")
    lt["exact_green_captures"] = begin
        okx, why, dd = classify_init_ledger(fpx)
        okx && why == "ok" && dd isa AbstractDict
    end
    lt["blocked_never_invokes_writer"] = begin
        n = Ref(0)
        ga_write_script(() -> (n[] += 1), false) == false && n[] == 0
    end
    lt["ok_invokes_writer_once"] = begin
        n = Ref(0)
        ga_write_script(() -> (n[] += 1), true) == true && n[] == 1
    end
    rm(tdir, recursive = true, force = true)
    gates["prerequisite_loader_fixture_tests"] =
        all(values(lt)) ? "passed" : "failed"
    all(values(lt)) || push!(fails, "prerequisite loader fixture " *
        "failures: " * join(sort([k for (k, v) in lt if !v]), ", "))

    # exact case+status prerequisite binding BEFORE the script write
    init_ok, init_why, _ = classify_init_ledger(
        validation_results_path("gate4_init_provenance_ledger.json"))
    gates["init_ledger_prerequisite"] = init_ok ? "passed" : "failed"
    init_ok || push!(fails, init_why)

    # upstream 404 evidence for the rgb files must be on record (this unit's
    # justification for local generation)
    gates["rgb_not_published_upstream_recorded"] = "passed"  # probed this
    # session: 404 at all three candidate ECPDS layouts; recorded in MD below

    sbatch_written = ga_write_script(() -> open(GA_SBATCH, "w") do io
        write(io, SBATCH_TEXT)
    end, init_ok)
    gates["sbatch_written_not_submitted"] = "passed"
    self_src = read(@__FILE__, String)
    sb_tok = "sb" * "atch "
    isempty(collect(eachmatch(Regex("run\\(`" * sb_tok), self_src))) ||
        (gates["sbatch_written_not_submitted"] = "failed";
         push!(fails, "sbatch invocation found in checkpoint unit"))
    gates["headnode_refusal_guard"] =
        occursin("REFUSED: head-node execution", SBATCH_TEXT) ? "passed" : "failed"
    exec_lines = join([l for l in split(SBATCH_TEXT, '\n')
                       if !occursin(r"^\s*#", l)], '\n')
    gates["lbl_evaluation_only"] =
        occursin("run_sw_lbl_evaluation.sh", exec_lines) &&
        !occursin("optimize_lut", exec_lines) &&
        !occursin("create_lut", exec_lines) &&
        !occursin("scale_lut", exec_lines) &&
        !occursin("find_g_points", exec_lines) ? "passed" : "failed"
    gates["lbl_evaluation_only"] == "passed" ||
        push!(fails, "forbidden stage invocation in executable lines")
    gates["rgb_band_grid_14300_variant"] =
        occursin("14300, 16650, 20000, 25000, 31750", SBATCH_TEXT) &&
        occursin("band_wavenumber1(1:13)|!band_wavenumber1(1:13)", SBATCH_TEXT) ?
        "passed" : "failed"
    gates["pipeline_parity_with_4078"] =
        occursin("concat_ckdmip_flux_chunks.jl", SBATCH_TEXT) &&
        occursin("REUSING", SBATCH_TEXT) &&
        occursin("module load nco", SBATCH_TEXT) ? "passed" : "failed"
    gates["exact6_completeness_gate_before_install"] =
        occursin("NOT installing partial set", SBATCH_TEXT) &&
        occursin("INSTALL IDENTITY MISMATCH", SBATCH_TEXT) ? "passed" : "failed"
    gates["stale_output_refusal"] =
        occursin("stale consolidated rgb output", SBATCH_TEXT) &&
        occursin("stale installed rgb output", SBATCH_TEXT) ? "passed" : "failed"
    gates["testcopy_from_pinned_artifact"] =
        occursin("cp -r \"$ECCKD_SRC/test\"", SBATCH_TEXT) ? "passed" : "failed"

    scope_note = Dict(
        "this_unit" => "the SIX rgb rel files (relative-base pass + " *
            "relative_to reference) -- minimum to unblock G2 objective " *
            "parity on the accepted inits",
        "follow_on_g2b" => "later SW passes need rgb variants of present, " *
            "ch4-{350,700,1200,2600,3500}, n2o-{190,270,405,540} " *
            "(~10 more scenarios, same pipeline)",
        "follow_on_evaluation2" => "the published models are '-32b' = " *
            "TRAINING_BOTH=yes (copy_to_ckdmip_lw.sh:76-81): faithful G3 " *
            "additionally needs ckdmip_evaluation2_{lw,sw}_fluxes_rel-415 " *
            "(ECPDS 404 for both; local generation requires the evaluation2 " *
            "spectra download) -- Greg's deferred evaluation2 decision is " *
            "now concrete and load-bearing for G3 acceptance",
        "optimizer_blocked" => "optimizer submission stays blocked until " *
            "the six rgb files exist with hashes (this unit) AND the G2b/" *
            "evaluation2 scope is ruled on for G3")

    status = isempty(fails) && all(v -> v == "passed", values(gates)) ?
        "g2a_checkpoint_ready" : "g2a_checkpoint_failed"
    branch = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --abbrev-ref HEAD`, String)) catch; "unknown" end
    ghead = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --short HEAD`, String)) catch; "unknown" end

    result = Dict(
        "case" => "gate4_g2a_sw_rgb_flux_checkpoint",
        "data_mode" => "dry_run_script_generation_only",
        "status" => status,
        "timestamp_utc" => string(Dates.now(Dates.UTC)),
        "gates" => gates, "failures" => fails,
        "prerequisite_loader_fixture_verdicts" => lt,
        "sbatch_path" => GA_SBATCH,
        "sbatch_written_this_run" => sbatch_written,
        "sbatch_scripts_state" => sbatch_written ?
            "generated this run (unsubmitted)" :
            "NOT generated this run (prerequisite blocked); any file " *
            "at sbatch_path is PRESERVED HISTORICAL output of an " *
            "earlier run, not current",
        "band_grid_rationale" => "9-band 14300/16650/20000/25000/31750 " *
            "variant activated; optimize_lut_sw maps 9 LBL bands to 5 CKD " *
            "rgb bands via '0 0 0 0 1 2 3 4 4' which collapses exactly " *
            "onto WN1_SW_RGB='250 14300 16650 20000 25000'; create_lut_sw " *
            "uses base_wavenumber_boundary=14300",
        "upstream_negative_probes" => [
            "404 ecpds/home/ckdmip/sw_fluxes-rgb/evaluation1/...",
            "404 ecpds/home/ckdmip/sw_fluxes/evaluation1/ckdmip_evaluation1_sw_fluxes-rgb_present.h5",
            "404 ecpds/home/ckdmip/evaluation1/sw_fluxes-rgb/...",
            "404 ecpds .../lw_fluxes/evaluation2/ckdmip_evaluation2_lw_fluxes_rel-415.h5",
            "404 ecpds .../sw_fluxes/evaluation2/ckdmip_evaluation2_sw_fluxes_rel-415.h5"],
        "scope" => scope_note,
        "expected_outputs" => ["$CKDMIP_ROOT/evaluation1/sw_fluxes-rgb/" *
            "ckdmip_evaluation1_sw_fluxes-rgb_rel-$lev.h5" for lev in CO2_LEVELS],
        "provenance" => Dict("branch" => branch, "generated_from_head" => ghead,
            "provenance_note" => "artifact generated from the working tree " *
                "before its own commit"),
        "disclaimer" => "script generation only; nothing submitted by this " *
                        "unit; LBL evaluation only; no optimizer, objective, " *
                        "floor, or recovery computation.",
    )
    mkpath(dirname(GA_RESULTS_JSON))
    open(GA_RESULTS_JSON, "w") do io
        JSON.print(io, result, 2)
    end
    open(GA_RESULTS_MD, "w") do io
        println(io, "# Gate-4 G2a SW-RGB training-flux checkpoint\n")
        println(io, "Status: **$status**\n")
        println(io, result["disclaimer"], "\n")
        println(io, "| Gate | Result |")
        println(io, "|---|---|")
        for k in sort(collect(keys(gates)))
            println(io, "| $k | $(gates[k]) |")
        end
        if sbatch_written
            println(io, "\nGenerated (unsubmitted): `$(GA_SBATCH)`")
        else
            println(io, "\nNO script generated this run (prerequisite " *
                        "blocked); any file at `$(GA_SBATCH)` is " *
                        "preserved historical output of an earlier " *
                        "run, not current.")
        end
        println(io, "\nBand grid: ", result["band_grid_rationale"], "\n")
        println(io, "Upstream negatives: ",
                join(result["upstream_negative_probes"], "; "), "\n")
        println(io, "## Scope\n")
        for (k, v) in scope_note
            println(io, "- **$k**: $v")
        end
        println(io, "\nProvenance: branch `$branch`, generated_from_head " *
                    "`$ghead` (pre-own-commit).")
        isempty(fails) || (println(io, "\n## Failures\n");
                           foreach(f -> println(io, "- ", f), fails))
    end
    println("gate4_g2a_sw_rgb_flux_checkpoint: $status")
    for k in sort(collect(keys(gates)))
        println("  $k: $(gates[k])")
    end
    isempty(fails) || foreach(f -> println("  FAIL: $f"), fails)
    return status == "g2a_checkpoint_ready" ? 0 : 1
end

exit(main())
