# Gate-4 R2 EXECUTION CHECKPOINT (dry-run generation; NO submission).
#
# AUTHORIZED: Greg issued the R2 go ("go for R2", 2026-07-20), satisfying
# the r2_matching_version_go token required by the R2 scaffold.
#
# Generates the Slurm batch script that (1) builds ecCKD at 23adaca (v1.4)
# in the quarantined tree with toolchain parity to the pinned v1.2 build,
# and (2) reruns the SW raw create_lut proof with the hash-pinned 4082 SW
# candidate placed mechanism-1 style under the v1.4-derived filename, in an
# isolated testcopy-v14 with a fresh work-v14 subtree. create_lut ONLY.
# Post-checkout verifications already confirmed on the cloned tree:
# configure.ac AC_INIT 1.4; ChangeLog v1.4 = SSI save; ckd_model.cpp has 6
# solar_spectral_irradiance references (v1.2: 0).

include(joinpath(@__DIR__, "validation_results.jl"))

using Dates
import JSON

const V14_COMMIT = "23adaca3344f4b53f109f3bd9533a5ed62998ec0"
const V14_TREE = "/shared/home/greg/ecckd-derived-flux-work/ecckd-v1.4-23adaca"
const G4WORK = "/shared/home/greg/ecckd-derived-flux-work/g4-init-generation"
const CKDMIP_ROOT = "/shared/home/greg/data/ckdmip"
const SW_CANDIDATE = "$G4WORK/work/sw_gpoints/ecckd-1.2_sw_gpoints_climate_rgb-tol0.047.h5"
const SW_CANDIDATE_SHA = "13dd686acd0c3ca2201775270f876ce3e3a326576b58b24323b5ce95659b9b57"
const SW_RAW_V14 = "$G4WORK/work-v14/sw_raw-ckd-definition/ecckd-1.4_sw_raw-ckd-definition_climate_rgb-tol0.047.nc"
const ADEPT = "/shared/home/greg/local/adept-2-install"
const NETCDF = "/shared/home/greg/local/ckdmip-stack"

const RX_RESULTS_JSON = validation_results_path("gate4_r2_execution_checkpoint.json")
const RX_RESULTS_MD = validation_results_path("gate4_r2_execution_checkpoint.md")
const RX_SBATCH = validation_results_path("gate4_r2_dryrun.sbatch")

const SBATCH_TEXT = """
#!/bin/bash
#SBATCH --job-name=g4-r2-v14-sw-proof
#SBATCH --output=/shared/home/greg/data/ckdmip-logs/g4-r2-%j.log
#SBATCH --time=04:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=60G
#SBATCH --partition=cpu-large

# Gate-4 R2: build ecCKD v1.4 (23adaca) + SW raw create_lut proof ONLY (no
# find_g_points, no optimisation, no objective stages). Generated by
# gate4_r2_execution_checkpoint.jl under Greg's R2 authorization.
set -euo pipefail
if [ -z "\${SLURM_JOB_ID:-}" ]; then
    echo "REFUSED: head-node execution is not permitted; submit via sbatch." >&2
    exit 64
fi

V14=$V14_TREE
G4WORK=$G4WORK

echo "=== R2 stage 0: tree/commit/candidate checks ==="
test -d "\$V14" || { echo "REFUSED: v1.4 tree missing" >&2; exit 68; }
test "\$(git -C "\$V14" rev-parse HEAD)" = "$V14_COMMIT" || { echo "REFUSED: v1.4 tree not at 23adaca" >&2; exit 68; }
grep -q 'AC_INIT(\\[ecCKD\\], \\[1.4\\]' "\$V14/configure.ac" || { echo "REFUSED: configure.ac not 1.4" >&2; exit 68; }
sha256sum -c <<'HASHES' || { echo "REFUSED: SW candidate hash mismatch vs 4082 ledger" >&2; exit 69; }
$SW_CANDIDATE_SHA  $SW_CANDIDATE
HASHES
test ! -e "$SW_RAW_V14" || { echo "REFUSED: stale v1.4 SW raw output already exists" >&2; exit 70; }
test -d "$CKDMIP_ROOT/idealized/sw_spectra" || { echo "MISSING idealized SW spectra" >&2; exit 65; }
test -s "$CKDMIP_ROOT/mmm/conc/ckdmip_mmm-const_concentrations.nc" || { echo "MISSING mmm-const conc" >&2; exit 65; }
test -s "$CKDMIP_ROOT/mmm/sw_spectra_extras/ckdmip_ssi.h5" || { echo "MISSING MMM SSI" >&2; exit 65; }

echo "=== R2 stage 1: build v1.4 (toolchain parity with pinned v1.2 build) ==="
cd "\$V14"
if [ ! -x src/ecckd/create_look_up_table ]; then
    [ -x ./configure ] || autoreconf -i
    ./configure --with-adept=$ADEPT --with-netcdf=$NETCDF
    make -j16
fi
echo "build provenance:"
gcc --version | head -1
git -C "\$V14" rev-parse HEAD
sha256sum src/ecckd/create_look_up_table

echo "=== R2 stage 2: isolated testcopy-v14 (pinned v1.2 workcopy untouched) ==="
TESTCOPY="\$G4WORK/testcopy-v14"
rm -rf "\$TESTCOPY"
cp -r "\$V14/test" "\$TESTCOPY"
sed -i \\
  -e 's|^CKDMIP_DATA_DIR=.*|CKDMIP_DATA_DIR=$CKDMIP_ROOT|' \\
  -e 's|^WORK_DIR=.*|WORK_DIR=$G4WORK/work-v14|' \\
  -e 's|^BINDIR=.*|BINDIR=$V14_TREE/src/ecckd|' \\
  -e 's|^MMM_SW_SPECTRA_DIR=.*|MMM_SW_SPECTRA_DIR=$G4WORK/input/mmm/sw_spectra|' \\
  -e 's|^CLOUD_SPECTRUM=.*|CLOUD_SPECTRUM=$V14_TREE/data/mie_droplet_scattering.nc|' \\
  "\$TESTCOPY/config.h"
grep -E "^(CKDMIP_DATA_DIR|WORK_DIR|BINDIR|MMM_SW_SPECTRA_DIR|CLOUD_SPECTRUM)=" "\$TESTCOPY/config.h"

echo "=== R2 stage 3: mechanism-1 candidate placement under v1.4 name ==="
mkdir -p "\$G4WORK/work-v14/sw_gpoints"
ln -sf "$SW_CANDIDATE" "\$G4WORK/work-v14/sw_gpoints/ecckd-1.4_sw_gpoints_climate_rgb-tol0.047.h5"
ls -la "\$G4WORK/work-v14/sw_gpoints/"

echo "=== R2 stage 4: SW raw create_lut (rgb, TOLERANCE=0.047) ==="
cd "\$TESTCOPY"
APPLICATION=climate BAND_STRUCTURE=rgb TOLERANCE=0.047 bash create_lut_sw.sh

echo "=== R2 outputs ==="
sha256sum "$SW_RAW_V14"
echo "=== R2 done rc=\$? \$(date -u +%FT%TZ) ==="
"""

function main()
    fails = String[]
    gates = Dict{String, String}()

    scaffold = JSON.parsefile(
        validation_results_path("gate4_r2_sw_matching_version_proof_scaffold.json"))
    gates["scaffold_prerequisite"] =
        scaffold["status"] == "r2_scaffold_ready_awaiting_authorization" ?
        "passed" : "failed"
    gates["authorization_recorded"] = "passed"  # Greg: "go for R2" 2026-07-20

    # post-checkout verifications (tree exists now; scaffold's
    # v14_tree_not_yet_created gate is superseded by authorization)
    tree_ok = isdir(V14_TREE) &&
        strip(read(`git -C $V14_TREE rev-parse HEAD`, String)) == V14_COMMIT
    gates["v14_tree_at_pinned_commit"] = tree_ok ? "passed" : "failed"
    tree_ok || push!(fails, "v1.4 tree missing or wrong commit")
    if tree_ok
        gates["configure_ac_is_14"] =
            occursin("AC_INIT([ecCKD], [1.4]",
                     read(joinpath(V14_TREE, "configure.ac"), String)) ?
            "passed" : "failed"
        gates["ckd_model_has_ssi_persistence"] =
            count(l -> occursin("solar_spectral_irradiance", l),
                  readlines(joinpath(V14_TREE, "src/ecckd/ckd_model.cpp"))) > 0 ?
            "passed" : "failed"
    end

    cand_ok = isfile(SW_CANDIDATE) &&
        split(strip(read(`sha256sum $SW_CANDIDATE`, String)))[1] == SW_CANDIDATE_SHA
    gates["sw_candidate_hash_pinned"] = cand_ok ? "passed" : "failed"
    gates["v14_raw_output_absent"] = !isfile(SW_RAW_V14) ? "passed" : "failed"

    open(RX_SBATCH, "w") do io
        write(io, SBATCH_TEXT)
    end
    gates["sbatch_written_not_submitted"] = "passed"
    self_src = read(@__FILE__, String)
    sb_tok = "sb" * "atch "
    isempty(collect(eachmatch(Regex("run\\(`" * sb_tok), self_src))) ||
        (gates["sbatch_written_not_submitted"] = "failed";
         push!(fails, "sbatch invocation found in checkpoint unit"))
    gates["headnode_refusal_guard"] =
        occursin("REFUSED: head-node execution", SBATCH_TEXT) ? "passed" : "failed"
    exec_lines = join([l for l in split(SBATCH_TEXT, '\n')
                       if !occursin(r"^\s*#", l)], '\n')
    gates["create_lut_only"] =
        occursin("create_lut_sw.sh", exec_lines) &&
        !occursin("optimize_lut", exec_lines) &&
        !occursin("scale_lut", exec_lines) &&
        !occursin("find_g_points", exec_lines) &&
        !occursin("run_ckd", exec_lines) &&
        !occursin("reorder_spectrum", exec_lines) &&
        !occursin("create_lut_lw", exec_lines) ? "passed" : "failed"
    gates["create_lut_only"] == "passed" ||
        push!(fails, "forbidden stage invocation in executable lines")
    gates["quarantine_isolation"] =
        occursin("testcopy-v14", SBATCH_TEXT) &&
        occursin("work-v14", SBATCH_TEXT) &&
        occursin("BINDIR=$V14_TREE/src/ecckd", SBATCH_TEXT) &&
        !occursin(Regex("sed -i[^\n]*ecckd-derived-flux-work/ecckd/test"),
                  SBATCH_TEXT) ? "passed" : "failed"
    gates["mechanism1_placement"] =
        occursin("ecckd-1.4_sw_gpoints_climate_rgb-tol0.047.h5", SBATCH_TEXT) &&
        occursin("ln -sf", SBATCH_TEXT) ? "passed" : "failed"
    gates["stale_output_refusal"] =
        occursin("stale v1.4 SW raw output", SBATCH_TEXT) ? "passed" : "failed"
    gates["candidate_identity_pinned"] =
        occursin(SW_CANDIDATE_SHA, SBATCH_TEXT) &&
        occursin("sha256sum -c", SBATCH_TEXT) ? "passed" : "failed"
    gates["toolchain_parity_flags"] =
        occursin("--with-adept=$ADEPT", SBATCH_TEXT) &&
        occursin("--with-netcdf=$NETCDF", SBATCH_TEXT) ? "passed" : "failed"

    status = isempty(fails) && all(v -> v == "passed", values(gates)) ?
        "r2_execution_checkpoint_ready" : "r2_execution_checkpoint_failed"
    branch = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --abbrev-ref HEAD`, String)) catch; "unknown" end
    ghead = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --short HEAD`, String)) catch; "unknown" end

    result = Dict(
        "case" => "gate4_r2_execution_checkpoint",
        "data_mode" => "dry_run_script_generation_only",
        "status" => status,
        "timestamp_utc" => string(Dates.now(Dates.UTC)),
        "gates" => gates, "failures" => fails,
        "authorization" => "Greg: 'go for R2' (2026-07-20) = " *
                           "r2_matching_version_go per the scaffold",
        "sbatch_path" => RX_SBATCH,
        "v14_tree" => Dict("path" => V14_TREE, "commit" => V14_COMMIT,
            "post_checkout_verifications" => "configure.ac 1.4; ChangeLog " *
                "v1.4 SSI entry; ckd_model.cpp 6 SSI references (v1.2: 0)"),
        "expected_output" => SW_RAW_V14,
        "provenance" => Dict("branch" => branch, "generated_from_head" => ghead,
            "provenance_note" => "artifact generated from the working tree " *
                "before its own commit"),
        "disclaimer" => "script generation only; nothing submitted by this " *
                        "unit; build+create_lut only; no objective, floor, " *
                        "acceptance, or promotion.",
    )
    mkpath(dirname(RX_RESULTS_JSON))
    open(RX_RESULTS_JSON, "w") do io
        JSON.print(io, result, 2)
    end
    open(RX_RESULTS_MD, "w") do io
        println(io, "# Gate-4 R2 execution checkpoint\n")
        println(io, "Status: **$status**\n")
        println(io, result["disclaimer"], "\n")
        println(io, "Authorization: ", result["authorization"], "\n")
        println(io, "| Gate | Result |")
        println(io, "|---|---|")
        for k in sort(collect(keys(gates)))
            println(io, "| $k | $(gates[k]) |")
        end
        println(io, "\nGenerated (unsubmitted) batch script: `$(RX_SBATCH)`")
        println(io, "\nExpected v1.4 SW raw output: `$(SW_RAW_V14)`")
        println(io, "\nProvenance: branch `$branch`, generated_from_head " *
                    "`$ghead` (pre-own-commit).")
        isempty(fails) || (println(io, "\n## Failures\n");
                           foreach(f -> println(io, "- ", f), fails))
    end
    println("gate4_r2_execution_checkpoint: $status")
    for k in sort(collect(keys(gates)))
        println("  $k: $(gates[k])")
    end
    isempty(fails) || foreach(f -> println("  FAIL: $f"), fails)
    return status == "r2_execution_checkpoint_ready" ? 0 : 1
end

exit(main())
