# Gate-4 R2 EXECUTION CHECKPOINT (dry-run generation; NO submission) --
# HISTORICAL POST-EXECUTION MODE when the v1.4 SW raw output exists.
#
# EXECUTED (monitor-directed marking, 2026-08-12): the generated sbatch
# ran as jobs 4094/4095 (configure failures, root causes recorded below
# at write time) and 4096 (COMPLETED rc=0); outcomes are pinned by
# gate4_r2_finding_ledger (r2_ssi_resolved_drift_version_independent).
# When the v1.4 raw output exists, this unit runs HISTORICAL VERIFICATION
# that is read-only WITH RESPECT TO EXECUTION ARTIFACTS (it still writes
# its own JSON/MD results): the executed sbatch is PRESERVED -- never
# rewritten, and byte-verified against the git blob at the finding-ledger
# head commit 6937d473c4cb22daea38f38cd5bbaaed7dd98416 (pinned sha
# 30d0a2ce...; committed 16:27:59Z, before job 4096 completed 16:43:13Z)
# -- the REPOSITORY-PINNED FINAL SUBMITTED-SCRIPT RECORD, the strongest
# available anchor since no scheduler ledger records the sbatch hash;
# consistency with the current SBATCH_TEXT is checked separately as a
# generator-integrity property, not as execution identity. Output and attempt history are verified
# against the finding ledger with fail-closed structure handling. The
# at-write attempt_1/attempt_2 root-cause records below are preserved
# verbatim as execution evidence. The pre-execution generation path is
# retained for the output-absent world.
#
# AUTHORIZED: Greg issued the R2 go ("go for R2", 2026-07-20), satisfying
# the r2_matching_version_go token required by the R2 scaffold.
#
# Generates the Slurm batch script that (1) builds ecCKD at 23adaca (v1.4)
# in the quarantined tree with toolchain parity to the pinned v1.2 build,
# and (2) reruns the SW raw create_lut proof with the hash-pinned 4082 SW
# candidate placed mechanism-1 style under the v1.4-derived filename, in an
# isolated testcopy-v14 with a fresh work-v14 subtree. create_lut ONLY.
# Post-checkout verifications already confirmed on the cloned tree:
# configure.ac AC_INIT 1.4; ChangeLog v1.4 = SSI save; ckd_model.cpp has 6
# solar_spectral_irradiance references (v1.2: 0).

include(joinpath(@__DIR__, "validation_results.jl"))

using Dates
import JSON

const V14_COMMIT = "23adaca3344f4b53f109f3bd9533a5ed62998ec0"
const V14_TREE = "/shared/home/greg/ecckd-derived-flux-work/ecckd-v1.4-23adaca"
const G4WORK = "/shared/home/greg/ecckd-derived-flux-work/g4-init-generation"
const CKDMIP_ROOT = "/shared/home/greg/data/ckdmip"
const SW_CANDIDATE = "$G4WORK/work/sw_gpoints/ecckd-1.2_sw_gpoints_climate_rgb-tol0.047.h5"
const SW_CANDIDATE_SHA = "13dd686acd0c3ca2201775270f876ce3e3a326576b58b24323b5ce95659b9b57"
const SW_RAW_V14 = "$G4WORK/work-v14/sw_raw-ckd-definition/ecckd-1.4_sw_raw-ckd-definition_climate_rgb-tol0.047.nc"
const ADEPT = "/shared/home/greg/local/adept-2-install"
const NETCDF = "/shared/home/greg/local/ckdmip-stack"

const RX_RESULTS_JSON = validation_results_path("gate4_r2_execution_checkpoint.json")
const RX_RESULTS_MD = validation_results_path("gate4_r2_execution_checkpoint.md")
const RX_SBATCH = validation_results_path("gate4_r2_dryrun.sbatch")

# the REPOSITORY-PINNED FINAL SUBMITTED-SCRIPT RECORD: the script blob at
# the finding-ledger head commit (committed 2026-07-20T16:27:59Z, BEFORE
# job 4096 completed at 16:43:13Z). No scheduler/submission ledger
# independently records the R2 sbatch hash, so this is the strongest
# available identity anchor: the repository's final record of the
# submitted script, not a scheduler-verified hash.
const RX_LEDGER_HEAD_COMMIT = "6937d473c4cb22daea38f38cd5bbaaed7dd98416"
const RX_EXECUTED_SBATCH_SHA =
    "30d0a2ce4735f9d52d36b3e23789824cbc058ab3167dff17e6e921ba7624839c"
const RX_SBATCH_REPO_PATH = "validation/results/gate4_r2_dryrun.sbatch"

const SBATCH_TEXT = """
#!/bin/bash
#SBATCH --job-name=g4-r2-v14-sw-proof
#SBATCH --output=/shared/home/greg/data/ckdmip-logs/g4-r2-%j.log
#SBATCH --time=04:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=60G
#SBATCH --partition=cpu-large

# Gate-4 R2: build ecCKD v1.4 (23adaca) + SW raw create_lut proof ONLY (no
# find_g_points, no optimisation, no objective stages). Generated by
# gate4_r2_execution_checkpoint.jl under Greg's R2 authorization.
set -euo pipefail
if [ -z "\${SLURM_JOB_ID:-}" ]; then
    echo "REFUSED: head-node execution is not permitted; submit via sbatch." >&2
    exit 64
fi

V14=$V14_TREE
G4WORK=$G4WORK

echo "=== R2 stage 0: tree/commit/candidate checks ==="
test -d "\$V14" || { echo "REFUSED: v1.4 tree missing" >&2; exit 68; }
test "\$(git -C "\$V14" rev-parse HEAD)" = "$V14_COMMIT" || { echo "REFUSED: v1.4 tree not at 23adaca" >&2; exit 68; }
grep -q 'AC_INIT(\\[ecCKD\\], \\[1.4\\]' "\$V14/configure.ac" || { echo "REFUSED: configure.ac not 1.4" >&2; exit 68; }
sha256sum -c <<'HASHES' || { echo "REFUSED: SW candidate hash mismatch vs 4082 ledger" >&2; exit 69; }
$SW_CANDIDATE_SHA  $SW_CANDIDATE
HASHES
test ! -e "$SW_RAW_V14" || { echo "REFUSED: stale v1.4 SW raw output already exists" >&2; exit 70; }
test -d "$CKDMIP_ROOT/idealized/sw_spectra" || { echo "MISSING idealized SW spectra" >&2; exit 65; }
test -s "$CKDMIP_ROOT/mmm/conc/ckdmip_mmm-const_concentrations.nc" || { echo "MISSING mmm-const conc" >&2; exit 65; }
test -s "$CKDMIP_ROOT/mmm/sw_spectra_extras/ckdmip_ssi.h5" || { echo "MISSING MMM SSI" >&2; exit 65; }

echo "=== R2 stage 1: build v1.4 (toolchain parity with pinned v1.2 build) ==="
# LIBS=-ladept works around an upstream m4 ordering bug exposed at v1.4:
# adept.m4 puts -ladept in LDFLAGS (before the conftest object), which
# Ubuntu's --as-needed linker drops; v1.2's weaker Adept>=1.1 conftest was
# header-only satisfiable so the bug was latent there. LIBS is placed after
# the object by autoconf/automake, resolving adept::compiler_version().
# Attempt 1 (job 4094) failed at exactly this configure check.
# LIBS applies to EVERY conftest incl. the initial compiler sanity check,
# which runs before --with-adept adds any -L path -- so the adept lib dir
# must also be in user LDFLAGS (attempt 2, job 4095, failed there with
# "C++ compiler cannot create executables" / cannot find -ladept).
cd "\$V14"
if [ ! -x src/ecckd/create_look_up_table ]; then
    [ -x ./configure ] || autoreconf -i
    ./configure --with-adept=$ADEPT --with-netcdf=$NETCDF \\
        LDFLAGS="-L$ADEPT/lib -Wl,-rpath,$ADEPT/lib" LIBS=-ladept
    make -j16
fi
echo "build provenance:"
gcc --version | head -1
git -C "\$V14" rev-parse HEAD
sha256sum src/ecckd/create_look_up_table

echo "=== R2 stage 2: isolated testcopy-v14 (pinned v1.2 workcopy untouched) ==="
TESTCOPY="\$G4WORK/testcopy-v14"
rm -rf "\$TESTCOPY"
cp -r "\$V14/test" "\$TESTCOPY"
sed -i \\
  -e 's|^CKDMIP_DATA_DIR=.*|CKDMIP_DATA_DIR=$CKDMIP_ROOT|' \\
  -e 's|^WORK_DIR=.*|WORK_DIR=$G4WORK/work-v14|' \\
  -e 's|^BINDIR=.*|BINDIR=$V14_TREE/src/ecckd|' \\
  -e 's|^MMM_SW_SPECTRA_DIR=.*|MMM_SW_SPECTRA_DIR=$G4WORK/input/mmm/sw_spectra|' \\
  -e 's|^CLOUD_SPECTRUM=.*|CLOUD_SPECTRUM=$V14_TREE/data/mie_droplet_scattering.nc|' \\
  "\$TESTCOPY/config.h"
grep -E "^(CKDMIP_DATA_DIR|WORK_DIR|BINDIR|MMM_SW_SPECTRA_DIR|CLOUD_SPECTRUM)=" "\$TESTCOPY/config.h"

echo "=== R2 stage 3: mechanism-1 candidate placement under v1.4 name ==="
mkdir -p "\$G4WORK/work-v14/sw_gpoints"
ln -sf "$SW_CANDIDATE" "\$G4WORK/work-v14/sw_gpoints/ecckd-1.4_sw_gpoints_climate_rgb-tol0.047.h5"
ls -la "\$G4WORK/work-v14/sw_gpoints/"

echo "=== R2 stage 4: SW raw create_lut (rgb, TOLERANCE=0.047) ==="
cd "\$TESTCOPY"
APPLICATION=climate BAND_STRUCTURE=rgb TOLERANCE=0.047 bash create_lut_sw.sh

echo "=== R2 outputs ==="
sha256sum "$SW_RAW_V14"
echo "=== R2 done rc=\$? \$(date -u +%FT%TZ) ==="
"""

# fail-closed JSON normalizers: every level of an external artifact is
# coerced to a known shape before use; wrong types yield empty values and
# controlled failed gates, never a thrown MethodError
as_obj(x) = x isa AbstractDict ? x : Dict{String, Any}()
as_str(x) = x isa AbstractString ? String(x) : ""

function parse_artifact!(fails, name)
    # absolute paths pass through so tmp fixtures exercise the SAME
    # helper. THREE stable, distinct refusal classes with FIXED reasons
    # (no OS/parser exception text embedded): missing; unparseable
    # (parse failure); parsed-non-object (JSON null/array/scalar).
    path = isabspath(name) ? name : validation_results_path(name)
    isfile(path) || (push!(fails, "$name missing"); return nothing)
    raw = try
        JSON.parsefile(path)
    catch
        push!(fails, "$name unparseable (parse failure)")
        return nothing
    end
    raw isa AbstractDict ||
        push!(fails, "$name parses to a non-object " *
                     "(JSON null/array/scalar)")
    return raw
end

# nonthrowing hash for the OUTPUT boundary: a vanished/unreadable file
# classifies as a failed gate with a reason, never a crash
rx_try_sha(p) = try
    split(strip(read(`sha256sum $p`, String)))[1]
catch
    nothing
end

# nonthrowing text read for residual file checks inside the pinned tree
rx_try_read(p) = try
    read(p, String)
catch
    nothing
end

# scaffold prerequisite classification (pure; fixture-run): the EXACT
# case is bound alongside the FAITHFUL mode-dependent status sets (the
# pre-execution branch still rejects the historical token)
function rx_classify_scaffold(scaffold_obj, historical)
    c = as_str(get(scaffold_obj, "case", ""))
    c == "gate4_r2_sw_matching_version_proof_scaffold" ||
        return (false, "scaffold case mismatch: " *
                       (isempty(c) ? "(missing/non-string)" : c))
    s = as_str(get(scaffold_obj, "status", ""))
    ok = historical ?
        s in ("r2_scaffold_ready_awaiting_authorization",
              "r2_scaffold_historical_executed") :
        s == "r2_scaffold_ready_awaiting_authorization"
    ok || return (false, "scaffold status: " *
                         (isempty(s) ? "(missing/non-string)" : s))
    return (true, "ok")
end

# the pre-execution sbatch write happens ONLY behind the classified
# prerequisite (historical mode structurally contains no write; a
# blocked pre-execution run never clobbers the committed script)
rx_should_write(historical, scaffold_ok) = !historical && scaffold_ok
function rx_write_script(writefn, historical, scaffold_ok)
    rx_should_write(historical, scaffold_ok) || return false
    writefn()
    return true
end

function main()
    fails = String[]
    gates = Dict{String, String}()

    # POST-EXECUTION detection: the v1.4 raw output on disk selects
    # historical verification (read-only w.r.t. execution artifacts)
    historical = isfile(SW_RAW_V14)

    # loader/classifier/writer fixtures FIRST, through the SAME code
    tdir = mktempdir()
    lt = Dict{String, Bool}()
    lt["missing_fails"] = begin
        fx = String[]
        parse_artifact!(fx, joinpath(tdir, "absent.json")) === nothing &&
            length(fx) == 1 && endswith(fx[1], "missing")
    end
    lt["malformed_distinguished"] = begin
        fx = String[]
        fp = joinpath(tdir, "m.json"); write(fp, "{")
        parse_artifact!(fx, fp) === nothing &&
            length(fx) == 1 &&
            endswith(fx[1], "unparseable (parse failure)")
    end
    lt["null_and_array_distinguished"] = begin
        fx = String[]
        fp = joinpath(tdir, "n.json"); write(fp, "null")
        r1 = parse_artifact!(fx, fp)
        fp2 = joinpath(tdir, "a.json"); write(fp2, "[1]")
        r2 = parse_artifact!(fx, fp2)
        r1 === nothing && r2 isa AbstractVector &&
            count(occursin("parses to a non-object", f) for f in fx) == 2 &&
            !any(occursin("unreadable", f) for f in fx)
    end
    lt["valid_object_no_reason"] = begin
        fx = String[]
        fp = joinpath(tdir, "g.json"); write(fp, "{\"case\": \"x\"}")
        parse_artifact!(fx, fp) isa AbstractDict && isempty(fx)
    end
    lt["scaffold_wrong_case_fails"] =
        !rx_classify_scaffold(Dict("case" => "other",
            "status" => "r2_scaffold_ready_awaiting_authorization"),
            true)[1]
    lt["scaffold_mode_dependent_sets"] = begin
        hist_tok = Dict(
            "case" => "gate4_r2_sw_matching_version_proof_scaffold",
            "status" => "r2_scaffold_historical_executed")
        ready_tok = Dict(
            "case" => "gate4_r2_sw_matching_version_proof_scaffold",
            "status" => "r2_scaffold_ready_awaiting_authorization")
        rx_classify_scaffold(hist_tok, true)[1] &&
            !rx_classify_scaffold(hist_tok, false)[1] &&
            rx_classify_scaffold(ready_tok, true)[1] &&
            rx_classify_scaffold(ready_tok, false)[1] &&
            !rx_classify_scaffold(Dict{String, Any}(), true)[1]
    end
    lt["scaffold_valid_and_tampered_status"] = begin
        tam = Dict("case" => "gate4_r2_sw_matching_version_proof_scaffold",
                   "status" => "totally_bogus")
        ok_h = rx_classify_scaffold(Dict(
            "case" => "gate4_r2_sw_matching_version_proof_scaffold",
            "status" => "r2_scaffold_historical_executed"), true)
        ok_h == (true, "ok") &&
            !rx_classify_scaffold(tam, true)[1] &&
            !rx_classify_scaffold(tam, false)[1]
    end
    lt["writer_only_preexecution_green"] = begin
        n = Ref(0)
        w = () -> (n[] += 1)
        rx_write_script(w, false, true) == true && n[] == 1 &&
            rx_write_script(w, false, false) == false &&
            rx_write_script(w, true, true) == false &&
            rx_write_script(w, true, false) == false && n[] == 1
    end
    lt["try_sha_and_read_nonthrowing"] =
        rx_try_sha(joinpath(tdir, "gone.bin")) === nothing &&
        rx_try_read(joinpath(tdir, "gone.txt")) === nothing &&
        rx_try_sha(joinpath(tdir, "g.json")) isa AbstractString
    rm(tdir, recursive = true, force = true)
    gates["prerequisite_loader_fixture_tests"] =
        all(values(lt)) ? "passed" : "failed"
    all(values(lt)) || push!(fails, "prerequisite loader fixture " *
        "failures: " * join(sort([k for (k, v) in lt if !v]), ", "))

    # controlled external-JSON dependency: malformed scaffold artifact is
    # a failed gate, not an exception; EXACT case bound alongside the
    # faithful mode-dependent status sets
    scaffold_obj = as_obj(parse_artifact!(fails,
        "gate4_r2_sw_matching_version_proof_scaffold.json"))
    scaffold_ok, scaffold_why = rx_classify_scaffold(scaffold_obj,
                                                     historical)
    gates["scaffold_prerequisite"] = scaffold_ok ? "passed" : "failed"
    scaffold_ok || push!(fails, scaffold_why)
    gates["authorization_recorded"] = "passed"  # Greg: "go for R2" 2026-07-20

    # post-checkout verifications (tree exists now; scaffold's
    # v14_tree_not_yet_created gate is superseded by authorization);
    # every residual read is NONTHROWING -- a missing/broken tree or
    # file is a failed gate with a reason, never a crash
    tree_head = isdir(V14_TREE) ? (try
        strip(read(`git -C $V14_TREE rev-parse HEAD`, String))
    catch
        nothing
    end) : nothing
    tree_ok = tree_head == V14_COMMIT
    gates["v14_tree_at_pinned_commit"] = tree_ok ? "passed" : "failed"
    tree_ok || push!(fails, "v1.4 tree missing, unreadable, or wrong " *
                            "commit")
    if tree_ok
        cfg_txt = rx_try_read(joinpath(V14_TREE, "configure.ac"))
        gates["configure_ac_is_14"] =
            (cfg_txt !== nothing &&
             occursin("AC_INIT([ecCKD], [1.4]", cfg_txt)) ?
            "passed" : "failed"
        gates["configure_ac_is_14"] == "passed" ||
            push!(fails, cfg_txt === nothing ?
                "configure.ac missing/unreadable in the pinned tree" :
                "configure.ac does not carry AC_INIT([ecCKD], [1.4]")
        ckd_txt = rx_try_read(joinpath(V14_TREE, "src/ecckd/ckd_model.cpp"))
        gates["ckd_model_has_ssi_persistence"] =
            (ckd_txt !== nothing &&
             occursin("solar_spectral_irradiance", ckd_txt)) ?
            "passed" : "failed"
        gates["ckd_model_has_ssi_persistence"] == "passed" ||
            push!(fails, ckd_txt === nothing ?
                "ckd_model.cpp missing/unreadable in the pinned tree" :
                "ckd_model.cpp lacks solar_spectral_irradiance persistence")
    end

    cand_ok = rx_try_sha(SW_CANDIDATE) == SW_CANDIDATE_SHA
    gates["sw_candidate_hash_pinned"] = cand_ok ? "passed" : "failed"
    cand_ok || push!(fails, "SW candidate missing, unreadable, or " *
                            "hash-mismatched")

    executed = Dict{String, Any}()
    if historical
        # (3) fail-closed structure handling: EVERY level is normalized
        # (top-level array, non-dict r2_run/output/attempts, non-string
        # sha/attempt values) into controlled failed gates, never a throw
        fin_obj = as_obj(parse_artifact!(fails,
            "gate4_r2_finding_ledger.json"))
        fin_ok = as_str(get(fin_obj, "case", "")) ==
                     "gate4_r2_finding_ledger" &&
                 as_str(get(fin_obj, "status", "")) ==
                     "r2_ssi_resolved_drift_version_independent"
        gates["r2_finding_ledger_verified"] = fin_ok ? "passed" : "failed"
        fin_ok || push!(fails, "R2 finding ledger missing/wrong " *
                               "case/status (or non-object JSON)")
        r2run_obj = as_obj(get(fin_obj, "r2_run", nothing))
        output_obj = as_obj(get(r2run_obj, "output", nothing))
        exp_out = as_str(get(output_obj, "sha256", nothing))
        attempts_obj = as_obj(get(r2run_obj, "attempts", nothing))
        exp_out_wellformed = occursin(r"^[0-9a-f]{64}$", exp_out)
        structure_ok = fin_ok && exp_out_wellformed &&
                       !isempty(attempts_obj)
        gates["finding_ledger_structure_valid"] =
            structure_ok ? "passed" : "failed"
        structure_ok || push!(fails,
            "finding ledger structure invalid: output.sha256 " *
            (exp_out_wellformed ? "ok" : "missing/malformed/non-string") *
            "; attempts " *
            (isempty(attempts_obj) ? "missing/non-object" : "ok"))
        out_ok = exp_out_wellformed &&
            rx_try_sha(SW_RAW_V14) == exp_out
        gates["v14_raw_output_matches_finding_ledger"] =
            out_ok ? "passed" : "failed"
        out_ok || push!(fails, "v1.4 raw output != finding-ledger sha " *
            "(a real integrity problem, not a stale-output refusal)")
        a1 = as_str(get(attempts_obj, "attempt_1", nothing))
        a2 = as_str(get(attempts_obj, "attempt_2", nothing))
        a3 = as_str(get(attempts_obj, "attempt_3", nothing))
        attempts_ok = occursin("4094", a1) && occursin("FAILED", a1) &&
                      occursin("4095", a2) && occursin("FAILED", a2) &&
                      occursin("4096", a3) && occursin("COMPLETED", a3) &&
                      occursin("rc=0", a3)
        gates["attempt_history_ledger_verified"] =
            attempts_ok ? "passed" : "failed"
        attempts_ok || push!(fails, "finding-ledger attempt strings do not " *
            "carry 4094 FAILED / 4095 FAILED / 4096 COMPLETED rc=0")
        # (2) submitted-script identity: the live sbatch bytes must equal
        # the pinned sha of the git blob at the finding-ledger head commit
        # -- the repository-pinned final submitted-script record (committed
        # before job 4096 completed; no scheduler ledger records the hash,
        # so this is the strongest available anchor); both the blob and
        # the live file are hashed here, nothing is assumed
        gates["sbatch_preserved_not_regenerated"] = "passed"  # structural:
        # this branch contains no write to RX_SBATCH
        blob_sha = try
            split(strip(read(pipeline(
                `git -C $(dirname(@__DIR__)) show $(RX_LEDGER_HEAD_COMMIT):$(RX_SBATCH_REPO_PATH)`,
                `sha256sum`), String)))[1]
        catch; "blob-unreadable" end
        live_hash = rx_try_sha(RX_SBATCH)
        live_sha = live_hash === nothing ? "missing/unreadable" : live_hash
        exec_ok = blob_sha == RX_EXECUTED_SBATCH_SHA &&
                  live_sha == RX_EXECUTED_SBATCH_SHA
        gates["preserved_sbatch_matches_executed_blob"] =
            exec_ok ? "passed" : "failed"
        exec_ok || push!(fails, "sbatch identity vs executed blob failed: " *
            "blob=$blob_sha live=$live_sha expected=$RX_EXECUTED_SBATCH_SHA")
        # generator-integrity CONSISTENCY property (not execution identity:
        # both this source and the file are mutable in a working tree);
        # nonthrowing read -- a vanished file is a failed gate with a
        # reason, never a crash
        preserved_txt = rx_try_read(RX_SBATCH)
        gates["preserved_sbatch_consistent_with_current_generator_text"] =
            preserved_txt == SBATCH_TEXT ? "passed" : "failed"
        preserved_txt == SBATCH_TEXT ||
            push!(fails, preserved_txt === nothing ?
                "preserved sbatch missing/unreadable" :
                "preserved sbatch not byte-identical to the current " *
                "generator text")
        executed = Dict(
            "attempt_1_ledger_verified" => a1,
            "attempt_2_ledger_verified" => a2,
            "attempt_3_ledger_verified" => a3,
            "outcome_verified" => "finding ledger status " *
                "$(as_str(get(fin_obj, "status", "")))",
            "executed_sbatch_sha256" => RX_EXECUTED_SBATCH_SHA,
            "executed_sbatch_provenance" => "repository-pinned final " *
                "submitted-script record: git blob at " *
                "$(RX_LEDGER_HEAD_COMMIT):$(RX_SBATCH_REPO_PATH) " *
                "(committed 2026-07-20T16:27:59Z, before job 4096 " *
                "completed 16:43:13Z), hash-verified this run; no " *
                "scheduler ledger independently records the sbatch hash",
            "v14_raw_output_sha256" => exp_out)
    else
        gates["v14_raw_output_absent"] = !isfile(SW_RAW_V14) ?
            "passed" : "failed"
    end
    # the pre-execution write is allowlist-gated on the classified
    # scaffold prerequisite (historical never writes; a blocked
    # pre-execution run never clobbers the committed script)
    sbatch_written = rx_write_script(() -> open(RX_SBATCH, "w") do io
        write(io, SBATCH_TEXT)
    end, historical, scaffold_ok)
    # (1) mode-appropriate gate name; the structural no-submission check
    # applies in all modes, and a blocked pre-execution run never claims
    # "written" -- it names the blocked-preserved state
    sb_gate = historical ? "sbatch_not_regenerated_or_submitted" :
              sbatch_written ? "sbatch_written_not_submitted" :
              "sbatch_blocked_preserved_not_submitted"
    gates[sb_gate] = "passed"
    self_src = read(@__FILE__, String)
    sb_tok = "sb" * "atch "
    isempty(collect(eachmatch(Regex("run\\(`" * sb_tok), self_src))) ||
        (gates[sb_gate] = "failed";
         push!(fails, "sbatch invocation found in checkpoint unit"))
    gates["headnode_refusal_guard"] =
        occursin("REFUSED: head-node execution", SBATCH_TEXT) ? "passed" : "failed"
    exec_lines = join([l for l in split(SBATCH_TEXT, '\n')
                       if !occursin(r"^\s*#", l)], '\n')
    gates["create_lut_only"] =
        occursin("create_lut_sw.sh", exec_lines) &&
        !occursin("optimize_lut", exec_lines) &&
        !occursin("scale_lut", exec_lines) &&
        !occursin("find_g_points", exec_lines) &&
        !occursin("run_ckd", exec_lines) &&
        !occursin("reorder_spectrum", exec_lines) &&
        !occursin("create_lut_lw", exec_lines) ? "passed" : "failed"
    gates["create_lut_only"] == "passed" ||
        push!(fails, "forbidden stage invocation in executable lines")
    gates["quarantine_isolation"] =
        occursin("testcopy-v14", SBATCH_TEXT) &&
        occursin("work-v14", SBATCH_TEXT) &&
        occursin("BINDIR=$V14_TREE/src/ecckd", SBATCH_TEXT) &&
        !occursin(Regex("sed -i[^\n]*ecckd-derived-flux-work/ecckd/test"),
                  SBATCH_TEXT) ? "passed" : "failed"
    gates["mechanism1_placement"] =
        occursin("ecckd-1.4_sw_gpoints_climate_rgb-tol0.047.h5", SBATCH_TEXT) &&
        occursin("ln -sf", SBATCH_TEXT) ? "passed" : "failed"
    gates["stale_output_refusal"] =
        occursin("stale v1.4 SW raw output", SBATCH_TEXT) ? "passed" : "failed"
    gates["candidate_identity_pinned"] =
        occursin(SW_CANDIDATE_SHA, SBATCH_TEXT) &&
        occursin("sha256sum -c", SBATCH_TEXT) ? "passed" : "failed"
    gates["toolchain_parity_flags"] =
        occursin("--with-adept=$ADEPT", SBATCH_TEXT) &&
        occursin("--with-netcdf=$NETCDF", SBATCH_TEXT) ? "passed" : "failed"
    gates["adept_link_workaround_documented"] =
        occursin("LIBS=-ladept", SBATCH_TEXT) &&
        occursin("as-needed", SBATCH_TEXT) ? "passed" : "failed"

    status = !(isempty(fails) && all(v -> v == "passed", values(gates))) ?
        "r2_execution_checkpoint_failed" :
        historical ? "r2_execution_checkpoint_historical_executed" :
                     "r2_execution_checkpoint_ready"
    branch = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --abbrev-ref HEAD`, String)) catch; "unknown" end
    ghead = try strip(read(`git -C $(dirname(@__DIR__)) rev-parse --short HEAD`, String)) catch; "unknown" end

    result = Dict(
        "case" => "gate4_r2_execution_checkpoint",
        "executed" => executed,
        "data_mode" => historical ?
            "historical_post_execution_verification_only" :
            "dry_run_script_generation_only",
        "status" => status,
        "timestamp_utc" => string(Dates.now(Dates.UTC)),
        "gates" => gates, "failures" => fails,
        "prerequisite_loader_fixture_verdicts" => lt,
        "sbatch_written_this_run" => sbatch_written,
        "sbatch_scripts_state" => sbatch_written ?
            "generated this run (unsubmitted)" :
            isfile(RX_SBATCH) ?
            "NOT generated this run " *
            "($(historical ? "historical mode preserves the executed " *
                             "script bytes" :
                             "prerequisite blocked")); the file at " *
            "sbatch path is PRESERVED output of an earlier run" :
            "NOT generated this run; NO file exists at the sbatch path",
        "authorization" => "Greg: 'go for R2' (2026-07-20) = " *
                           "r2_matching_version_go per the scaffold",
        "attempt_history" => Dict("attempt_1" => Dict(
            "job_id" => 4094,
            "outcome" => "FAILED at ./configure: 'Unable to find Adept " *
                "library version >= 2.1'",
            "root_cause" => "upstream m4 ordering bug exposed at v1.4: " *
                "adept.m4 places -ladept in LDFLAGS (before the conftest " *
                "object) and Ubuntu's --as-needed drops it; the v1.4 " *
                "Adept>=2.1 conftest links adept::compiler_version() " *
                "(undefined reference), while v1.2's Adept>=1.1 conftest " *
                "was header-only satisfiable so the same command shape " *
                "passed in May. Verified on the head node: identical " *
                "failure lib-before-obj, success obj-before-lib.",
            "fix" => "configure invoked with LIBS=-ladept (autoconf places " *
                "LIBS after the test object); no source patch, toolchain " *
                "flags otherwise identical",
            "no_partial_state" => "configure failed before make; " *
                "testcopy-v14/work-v14 never created; stage-0 guards " *
                "unaffected for the retry"),
        "attempt_2" => Dict(
            "job_id" => 4095,
            "outcome" => "FAILED at configure's initial sanity check: " *
                "'C++ compiler cannot create executables' (cannot find " *
                "-ladept)",
            "root_cause" => "the attempt-1 fix LIBS=-ladept applies to " *
                "EVERY conftest including the first compiler check, which " *
                "runs before --with-adept contributes any -L path; " *
                "verified on the head node (trivial main fails with " *
                "-ladept alone, passes with -L<adept>/lib)",
            "fix" => "add the adept lib dir to user LDFLAGS alongside " *
                "LIBS: LDFLAGS='-L<adept>/lib -Wl,-rpath,<adept>/lib' " *
                "LIBS=-ladept; user LDFLAGS is prepended to every " *
                "conftest so -ladept resolves everywhere",
            "no_partial_state" => "same as attempt 1: failed before make; " *
                "no testcopy-v14/work-v14 state")),
        "sbatch_path" => RX_SBATCH,
        "v14_tree" => Dict("path" => V14_TREE, "commit" => V14_COMMIT,
            "post_checkout_verifications" => "configure.ac 1.4; ChangeLog " *
                "v1.4 SSI entry; ckd_model.cpp 6 SSI references (v1.2: 0)"),
        (historical ? "verified_output" : "expected_output") => SW_RAW_V14,
        "provenance" => Dict("branch" => branch, "generated_from_head" => ghead,
            "provenance_note" => "artifact generated from the working tree " *
                "before its own commit"),
        "disclaimer" => historical ?
            "HISTORICAL post-execution record: the generated sbatch was " *
            "executed as jobs 4094/4095/4096 (ledger-verified); the " *
            "executed script is preserved byte-identically, never " *
            "regenerated; nothing executed or submitted by this unit." :
            "script generation only; nothing submitted by this " *
            "unit; build+create_lut only; no objective, floor, " *
            "acceptance, or promotion.",
    )
    mkpath(dirname(RX_RESULTS_JSON))
    open(RX_RESULTS_JSON, "w") do io
        JSON.print(io, result, 2)
    end
    open(RX_RESULTS_MD, "w") do io
        println(io, historical ?
            "# Gate-4 R2 execution checkpoint — HISTORICAL (executed as " *
            "jobs 4094/4095/4096)\n" :
            "# Gate-4 R2 execution checkpoint\n")
        println(io, "Status: **$status**\n")
        println(io, result["disclaimer"], "\n")
        println(io, "Authorization: ", result["authorization"], "\n")
        println(io, "| Gate | Result |")
        println(io, "|---|---|")
        for k in sort(collect(keys(gates)))
            println(io, "| $k | $(gates[k]) |")
        end
        if historical
            println(io, "\nExecuted batch script (preserved; byte-verified " *
                        "against the repository-pinned final " *
                        "submitted-script record, the git blob at " *
                        "`$(RX_LEDGER_HEAD_COMMIT)` committed " *
                        "2026-07-20T16:27:59Z before job 4096 completed " *
                        "16:43:13Z): `$(RX_SBATCH)` sha256 " *
                        "`$(RX_EXECUTED_SBATCH_SHA)`")
            println(io, "\nLedger-verified attempts:")
            for k in ("attempt_1_ledger_verified", "attempt_2_ledger_verified",
                      "attempt_3_ledger_verified")
                println(io, "- ", executed[k])
            end
            println(io, "\nVerified v1.4 SW raw output: `$(SW_RAW_V14)` " *
                        "sha256 `$(executed["v14_raw_output_sha256"])`")
        elseif sbatch_written
            println(io, "\nGenerated (unsubmitted) batch script: `$(RX_SBATCH)`")
            println(io, "\nExpected v1.4 SW raw output: `$(SW_RAW_V14)`")
        else
            println(io, "\nNO script generated this run (prerequisite " *
                        "blocked); any file at `$(RX_SBATCH)` is " *
                        "preserved output of an earlier run, not " *
                        "current.")
            println(io, "\nExpected v1.4 SW raw output: `$(SW_RAW_V14)`")
        end
        println(io, "\nProvenance: branch `$branch`, generated_from_head " *
                    "`$ghead` (pre-own-commit).")
        isempty(fails) || (println(io, "\n## Failures\n");
                           foreach(f -> println(io, "- ", f), fails))
    end
    println("gate4_r2_execution_checkpoint: $status")
    for k in sort(collect(keys(gates)))
        println("  $k: $(gates[k])")
    end
    isempty(fails) || foreach(f -> println("  FAIL: $f"), fails)
    return status in ("r2_execution_checkpoint_ready",
                      "r2_execution_checkpoint_historical_executed") ? 0 : 1
end

exit(main())
